approval_policy = "on-request"
model_provider = "oca"
preferred_auth_method = "apikey"
model = "gpt-5.4"
profile = "gpt-5-4"
sandbox_mode = "workspace-write"
web_search_request = true

trust_level = "trusted"

[model_providers.oca]
base_url = "https://code-internal.aiservice.us-chicago-1.oci.oraclecloud.com/20250206/app/litellm"
http_headers = { "client" = "codex-cli", "client-version" = "0" }
model = "gpt5"
name = "Oracle Code Assist"
wire_api = "responses"


[profiles.gpt-4-1]
model = "gpt-4.1"
model_provider = "oca"
review_model = "gpt-4.1"

[profiles.gpt-5]
model = "gpt5"
model_provider = "oca"
review_model = "gpt5"

[profiles.gpt-5-2]
model = "gpt-5.2"
model_provider = "oca"
review_model = "gpt-5.2"

[profiles.gpt-5-codex]
model = "gpt-5-codex"
model_provider = "oca"
review_model = "gpt-5-codex"
personality = "pragmatic"

[profiles.gpt-5-1-codex]
model = "gpt-5.1-codex"
model_provider = "oca"
review_model = "gpt-5.1-codex"
personality = "pragmatic"

[profiles.gpt-5-1-codex-mini]
model = "gpt-5.1-codex-mini"
model_provider = "oca"
review_model = "gpt-5.1-codex-mini"
personality = "pragmatic"

[profiles.gpt-5-1-codex-max]
model = "gpt-5.1-codex-max"
model_provider = "oca"
review_model = "gpt-5.1-codex-max"
personality = "pragmatic"

[profiles.gpt-5-2-codex]
model = "gpt-5.2-codex"
model_provider = "oca"
review_model = "gpt-5.2-codex"
personality = "pragmatic"

[profiles.gpt-5-3-codex]
model = "gpt-5.3-codex"
model_provider = "oca"
review_model = "gpt-5.3-codex"
personality = "pragmatic"

[profiles.gpt-5-4]
model = "gpt-5.4"
model_provider = "oca"
review_model = "gpt-5.4"
personality = "pragmatic"

[profiles.gpt-5-4-pro]
model = "gpt-5.4-pro"
model_provider = "oca"
review_model = "gpt-5.4-pro"
personality = "pragmatic"
