import type { PermissionCode } from '#/features/auth/rbac-catalog'

// Plain-data bootstrap catalog for the dynamic RBAC registry (modules / screens /
// actions / permission links). Intentionally free of React or Lucide imports so it
// is safe to import from the `tsx prisma/seed.ts` runner. `icon` values are Lucide
// icon *names* (strings), decoupled from the component references used in
// `src/lib/navigation/app-nav.ts`. In the DB-authoritative model this is bootstrap
// input for the seed, not the runtime source of truth.

export type PermissionKindCode =
  | 'screen'
  | 'menu'
  | 'action'
  | 'api'
  | 'data'
  | 'admin'

export type ModuleDefinition = {
  code: string
  name: string
  description: string
  icon: string
  displayOrder: number
  titleKey: string
  rootPath: string
}

export type ScreenDefinition = {
  moduleCode: string
  code: string
  name: string
  path: string
  titleKey: string
  icon: string
  displayOrder: number
  keywords: Array<string>
  defaultPermissionCode: PermissionCode | null
}

export type ScreenActionDefinition = {
  screenCode: string
  code: string
  name: string
  actionKey: string
  description: string
  displayOrder: number
}

export type PermissionLink = {
  moduleCode: string
  screenCode: string | null
  actionCode: string | null
  kind: PermissionKindCode
}

export const MODULE_DEFINITIONS: ReadonlyArray<ModuleDefinition> = [
  {
    code: 'overview',
    name: 'Overview',
    description: 'Cross-tenant control room and dashboards.',
    icon: 'LayoutDashboard',
    displayOrder: 0,
    titleKey: 'nav.dashboard',
    rootPath: '/dashboard',
  },
  {
    code: 'inventory',
    name: 'Inventory',
    description: 'Stock, catalog, outlets, and supply coverage.',
    icon: 'Boxes',
    displayOrder: 1,
    titleKey: 'nav.inventory',
    rootPath: '/inventory',
  },
  {
    code: 'purchase',
    name: 'Purchasing',
    description:
      'Procurement: suppliers, RFQs, orders, receipts, invoices, and payments.',
    icon: 'ShoppingCart',
    displayOrder: 2,
    titleKey: 'nav.purchase',
    rootPath: '/purchase',
  },
  {
    code: 'restaurant',
    name: 'Restaurant',
    description: 'Kitchen, menu engineering, and floor service.',
    icon: 'ChefHat',
    displayOrder: 3,
    titleKey: 'nav.restaurant',
    rootPath: '/restaurant/kitchen',
  },
  {
    code: 'pos',
    name: 'POS',
    description: 'Checkout, orders, and returns.',
    icon: 'ShoppingBasket',
    displayOrder: 4,
    titleKey: 'nav.pos',
    rootPath: '/pos',
  },
  {
    code: 'crm',
    name: 'CRM',
    description:
      'Customer intelligence: profiles, loyalty, segments, and analytics.',
    icon: 'HeartHandshake',
    displayOrder: 5,
    titleKey: 'nav.crm',
    rootPath: '/crm/customers',
  },
  {
    code: 'finance',
    name: 'Financial Management',
    description:
      'Accounting engine: general ledger, receivables, payables, cash, banking, budgets, assets, closing, and reports.',
    icon: 'Landmark',
    displayOrder: 6,
    titleKey: 'nav.finance',
    rootPath: '/finance/dashboard',
  },
  {
    code: 'hr',
    name: 'Human Resources',
    description:
      'Human Capital Management: organization, employees, recruitment, time, leave, payroll, and performance.',
    icon: 'UsersRound',
    displayOrder: 7,
    titleKey: 'nav.hr',
    rootPath: '/hr',
  },
  {
    code: 'system_admin',
    name: 'System Admin',
    description: 'Users, roles, access control, and configuration.',
    icon: 'ShieldCheck',
    displayOrder: 8,
    titleKey: 'nav.systemAdmin',
    rootPath: '/settings/security',
  },
] as const

export const SCREEN_DEFINITIONS: ReadonlyArray<ScreenDefinition> = [
  {
    moduleCode: 'overview',
    code: 'dashboard',
    name: 'Dashboard',
    path: '/dashboard',
    titleKey: 'nav.dashboard',
    icon: 'LayoutDashboard',
    displayOrder: 0,
    keywords: ['dashboard', 'overview', 'control room', 'briefing'],
    defaultPermissionCode: 'dashboard.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-overview',
    name: 'Overview',
    path: '/inventory',
    titleKey: 'nav.inventoryOverview',
    icon: 'PackageSearch',
    displayOrder: 0,
    keywords: ['inventory overview', 'coverage', 'reorder', 'stock'],
    defaultPermissionCode: 'inventory.view_stock',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-catalog',
    name: 'Catalog',
    path: '/inventory/catalog',
    titleKey: 'nav.inventoryCatalog',
    icon: 'ClipboardList',
    displayOrder: 1,
    keywords: ['catalog', 'products', 'assortment', 'sku'],
    defaultPermissionCode: 'product.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-pricing',
    name: 'Product Pricing',
    path: '/inventory/pricing',
    titleKey: 'nav.inventoryPricing',
    icon: 'BadgePercent',
    displayOrder: 2,
    keywords: ['pricing', 'price lists', 'tiers', 'currency'],
    defaultPermissionCode: 'product.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-categories',
    name: 'Categories',
    path: '/inventory/categories',
    titleKey: 'nav.inventoryCategories',
    icon: 'FolderTree',
    displayOrder: 3,
    keywords: ['categories', 'hierarchy', 'tree', 'classification'],
    defaultPermissionCode: 'product.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-brands',
    name: 'Brands',
    path: '/inventory/brands',
    titleKey: 'nav.inventoryBrands',
    icon: 'Tags',
    displayOrder: 4,
    keywords: ['brands', 'manufacturers', 'labels'],
    defaultPermissionCode: 'product.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-units',
    name: 'Units',
    path: '/inventory/units',
    titleKey: 'nav.inventoryUnits',
    icon: 'Ruler',
    displayOrder: 5,
    keywords: ['units', 'uom', 'measure', 'conversions'],
    defaultPermissionCode: 'product.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-outlets',
    name: 'Outlets',
    path: '/outlets',
    titleKey: 'nav.inventoryOutlets',
    icon: 'MapPinned',
    displayOrder: 6,
    keywords: ['outlets', 'stores', 'locations', 'coverage'],
    defaultPermissionCode: 'warehouse.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-locations',
    name: 'Warehouse Locations',
    path: '/inventory/locations',
    titleKey: 'nav.inventoryLocations',
    icon: 'MapPinned',
    displayOrder: 7,
    keywords: ['locations', 'zones', 'racks', 'shelves', 'bins'],
    defaultPermissionCode: 'warehouse.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-stock',
    name: 'Stock Ledger',
    path: '/inventory/stock',
    titleKey: 'nav.inventoryStock',
    icon: 'ReceiptText',
    displayOrder: 8,
    keywords: ['stock ledger', 'movements', 'thresholds', 'balance'],
    defaultPermissionCode: 'inventory.view_stock',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-movements',
    name: 'Movements',
    path: '/inventory/movements',
    titleKey: 'nav.inventoryMovements',
    icon: 'ArrowLeftRight',
    displayOrder: 9,
    keywords: ['movements', 'ledger', 'transactions', 'history', 'audit'],
    defaultPermissionCode: 'inventory.view_movements',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-reservations',
    name: 'Stock Reservations',
    path: '/inventory/reservations',
    titleKey: 'nav.inventoryReservations',
    icon: 'PackageCheck',
    displayOrder: 10,
    keywords: ['reservations', 'holds', 'allocation', 'reserved'],
    defaultPermissionCode: 'inventory.view_stock',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-adjustments',
    name: 'Adjustments',
    path: '/inventory/adjustments',
    titleKey: 'nav.inventoryAdjustments',
    icon: 'SlidersHorizontal',
    displayOrder: 11,
    keywords: ['adjustments', 'damage', 'expiry', 'write off', 'shrinkage'],
    defaultPermissionCode: 'adjustment.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-transfers',
    name: 'Transfers',
    path: '/inventory/transfers',
    titleKey: 'nav.inventoryTransfers',
    icon: 'Truck',
    displayOrder: 12,
    keywords: ['transfers', 'ship', 'receive', 'in transit', 'warehouse'],
    defaultPermissionCode: 'transfer.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-counts',
    name: 'Stock Counts',
    path: '/inventory/counts',
    titleKey: 'nav.inventoryCounts',
    icon: 'ClipboardCheck',
    displayOrder: 13,
    keywords: ['stock count', 'cycle count', 'variance', 'physical count'],
    defaultPermissionCode: 'inventory.count_view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-reports',
    name: 'Reports',
    path: '/inventory/reports',
    titleKey: 'nav.inventoryReports',
    icon: 'ChartSpline',
    displayOrder: 14,
    keywords: ['reports', 'valuation', 'reorder', 'analytics', 'snapshots'],
    defaultPermissionCode: 'inventory.view_valuation',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-settings',
    name: 'Settings',
    path: '/inventory/settings',
    titleKey: 'nav.inventorySettings',
    icon: 'SlidersHorizontal',
    displayOrder: 15,
    keywords: ['settings', 'reorder rules', 'snapshots', 'housekeeping'],
    defaultPermissionCode: 'inventory.view_stock',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-overview',
    name: 'Overview',
    path: '/purchase',
    titleKey: 'nav.purchaseOverview',
    icon: 'ShoppingCart',
    displayOrder: 0,
    keywords: ['purchasing', 'procurement', 'overview', 'buyer'],
    defaultPermissionCode: 'purchase.po_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-suppliers',
    name: 'Suppliers',
    path: '/purchase/suppliers',
    titleKey: 'nav.purchaseSuppliers',
    icon: 'Truck',
    displayOrder: 1,
    keywords: ['suppliers', 'vendors', 'contacts', 'bank accounts'],
    defaultPermissionCode: 'supplier.view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-requisitions',
    name: 'Requisitions',
    path: '/purchase/requisitions',
    titleKey: 'nav.purchaseRequisitions',
    icon: 'ClipboardList',
    displayOrder: 2,
    keywords: ['requisitions', 'purchase requests', 'pr'],
    defaultPermissionCode: 'purchase.requisition_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-rfqs',
    name: 'RFQs',
    path: '/purchase/rfqs',
    titleKey: 'nav.purchaseRfqs',
    icon: 'FileQuestion',
    displayOrder: 3,
    keywords: ['rfq', 'request for quotation', 'tender'],
    defaultPermissionCode: 'purchase.rfq_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-quotations',
    name: 'Quotations',
    path: '/purchase/quotations',
    titleKey: 'nav.purchaseQuotations',
    icon: 'FileText',
    displayOrder: 4,
    keywords: ['quotations', 'supplier quotes', 'comparison'],
    defaultPermissionCode: 'purchase.quotation_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-orders',
    name: 'Purchase Orders',
    path: '/purchase/orders',
    titleKey: 'nav.purchaseOrders',
    icon: 'ScrollText',
    displayOrder: 5,
    keywords: ['purchase orders', 'po', 'buying'],
    defaultPermissionCode: 'purchase.po_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-receipts',
    name: 'Goods Receipts',
    path: '/purchase/receipts',
    titleKey: 'nav.purchaseReceipts',
    icon: 'PackageCheck',
    displayOrder: 6,
    keywords: ['goods receipt', 'grn', 'receiving', 'inspection'],
    defaultPermissionCode: 'purchase.po_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-invoices',
    name: 'Supplier Invoices',
    path: '/purchase/invoices',
    titleKey: 'nav.purchaseInvoices',
    icon: 'ReceiptText',
    displayOrder: 7,
    keywords: ['supplier invoices', 'bills', 'payables', 'three-way match'],
    defaultPermissionCode: 'purchase.invoice_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-payments',
    name: 'Payments',
    path: '/purchase/payments',
    titleKey: 'nav.purchasePayments',
    icon: 'Banknote',
    displayOrder: 8,
    keywords: ['supplier payments', 'ap', 'settlements', 'allocations'],
    defaultPermissionCode: 'purchase.payment_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-returns',
    name: 'Returns & Debit Notes',
    path: '/purchase/returns',
    titleKey: 'nav.purchaseReturns',
    icon: 'Undo2',
    displayOrder: 9,
    keywords: ['purchase returns', 'debit notes', 'rtv'],
    defaultPermissionCode: 'purchase.po_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-approvals',
    name: 'Approvals',
    path: '/purchase/approvals',
    titleKey: 'nav.purchaseApprovals',
    icon: 'ShieldCheck',
    displayOrder: 10,
    keywords: ['approvals', 'workflow', 'inbox', 'escalation', 'delegate'],
    defaultPermissionCode: 'purchase.approval_action',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-dashboard',
    name: 'Restaurant Dashboard',
    path: '/restaurant/dashboard',
    titleKey: 'nav.restaurantDashboard',
    icon: 'LayoutDashboard',
    displayOrder: 0,
    keywords: ['dashboard', 'kpi', 'sales', 'overview', 'live'],
    defaultPermissionCode: 'res.dashboard.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-kitchen',
    name: 'Kitchen Board',
    path: '/restaurant/kitchen',
    titleKey: 'nav.restaurantKitchen',
    icon: 'ChefHat',
    displayOrder: 1,
    keywords: ['kitchen', 'board', 'prep', 'queue'],
    defaultPermissionCode: 'res.kitchen.access',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-menu',
    name: 'Menu Engineering',
    path: '/restaurant/menu',
    titleKey: 'nav.restaurantMenu',
    icon: 'ShoppingBasket',
    displayOrder: 2,
    keywords: ['menu', 'items', 'pricing', 'engineering'],
    defaultPermissionCode: 'res.menu.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-tables',
    name: 'Table Service',
    path: '/restaurant/tables',
    titleKey: 'nav.restaurantTables',
    icon: 'ReceiptText',
    displayOrder: 3,
    keywords: ['tables', 'service', 'covers', 'floor'],
    defaultPermissionCode: 'res.floor.manage',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-reports',
    name: 'Restaurant Reports',
    path: '/restaurant/reports',
    titleKey: 'nav.restaurantReports',
    icon: 'FileBarChart',
    displayOrder: 4,
    keywords: ['reports', 'sales', 'items', 'daily', 'export'],
    defaultPermissionCode: 'res.reports.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-analytics',
    name: 'Restaurant Analytics',
    path: '/restaurant/analytics',
    titleKey: 'nav.restaurantAnalytics',
    icon: 'TrendingUp',
    displayOrder: 5,
    keywords: ['analytics', 'trends', 'heat map', 'performance'],
    defaultPermissionCode: 'res.analytics.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-reservations',
    name: 'Reservations',
    path: '/restaurant/reservations',
    titleKey: 'nav.restaurantReservations',
    icon: 'CalendarClock',
    displayOrder: 6,
    keywords: ['reservations', 'bookings', 'calendar', 'guests'],
    defaultPermissionCode: 'res.reservations.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-waitlist',
    name: 'Waitlist',
    path: '/restaurant/waitlist',
    titleKey: 'nav.restaurantWaitlist',
    icon: 'ListOrdered',
    displayOrder: 7,
    keywords: ['waitlist', 'queue', 'walk-in', 'host'],
    defaultPermissionCode: 'res.reservations.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-takeaway',
    name: 'Takeaway',
    path: '/restaurant/takeaway',
    titleKey: 'nav.restaurantTakeaway',
    icon: 'ShoppingBag',
    displayOrder: 8,
    keywords: ['takeaway', 'pickup', 'counter', 'to-go'],
    defaultPermissionCode: 'res.takeaway.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-delivery',
    name: 'Delivery',
    path: '/restaurant/delivery',
    titleKey: 'nav.restaurantDelivery',
    icon: 'Bike',
    displayOrder: 9,
    keywords: ['delivery', 'dispatch', 'drivers', 'zones'],
    defaultPermissionCode: 'res.delivery.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-qr',
    name: 'QR Ordering',
    path: '/restaurant/qr',
    titleKey: 'nav.restaurantQr',
    icon: 'QrCode',
    displayOrder: 10,
    keywords: ['qr', 'codes', 'campaigns', 'ordering'],
    defaultPermissionCode: 'res.qr.manage',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-promotions',
    name: 'Promotions',
    path: '/restaurant/promotions',
    titleKey: 'nav.restaurantPromotions',
    icon: 'BadgePercent',
    displayOrder: 11,
    keywords: ['promotions', 'discounts', 'coupons', 'offers', 'happy hour'],
    defaultPermissionCode: 'res.promotions.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-giftcards',
    name: 'Gift Cards',
    path: '/restaurant/gift-cards',
    titleKey: 'nav.restaurantGiftCards',
    icon: 'Gift',
    displayOrder: 12,
    keywords: ['gift cards', 'stored value', 'reload', 'redeem'],
    defaultPermissionCode: 'res.giftcards.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-events',
    name: 'Events & Parties',
    path: '/restaurant/events',
    titleKey: 'nav.restaurantEvents',
    icon: 'PartyPopper',
    displayOrder: 13,
    keywords: ['events', 'parties', 'weddings', 'banquet', 'halls', 'booking'],
    defaultPermissionCode: 'res.events.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-catering',
    name: 'Catering',
    path: '/restaurant/catering',
    titleKey: 'nav.restaurantCatering',
    icon: 'UtensilsCrossed',
    displayOrder: 14,
    keywords: ['catering', 'corporate', 'outside events', 'jobs'],
    defaultPermissionCode: 'res.catering.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-settings',
    name: 'Restaurant Setup',
    path: '/restaurant/settings',
    titleKey: 'nav.restaurantSettings',
    icon: 'Settings',
    displayOrder: 15,
    keywords: [
      'restaurant',
      'branches',
      'tables',
      'service types',
      'stations',
      'tax',
      'setup',
    ],
    defaultPermissionCode: 'res.settings.manage',
  },
  {
    moduleCode: 'pos',
    code: 'pos-checkout',
    name: 'Checkout',
    path: '/pos',
    titleKey: 'nav.posCheckout',
    icon: 'ShoppingBasket',
    displayOrder: 0,
    keywords: ['checkout', 'basket', 'draft', 'scan'],
    defaultPermissionCode: 'dashboard.view',
  },
  {
    moduleCode: 'pos',
    code: 'pos-orders',
    name: 'Orders',
    path: '/pos/orders',
    titleKey: 'nav.posOrders',
    icon: 'ClipboardList',
    displayOrder: 1,
    keywords: ['orders', 'queue', 'tickets', 'history'],
    defaultPermissionCode: 'res.orders.view',
  },
  {
    moduleCode: 'pos',
    code: 'pos-returns',
    name: 'Returns',
    path: '/pos/returns',
    titleKey: 'nav.posReturns',
    icon: 'RotateCcw',
    displayOrder: 2,
    keywords: ['returns', 'refunds', 'voids', 'exceptions'],
    defaultPermissionCode: 'res.orders.cancel',
  },
  {
    moduleCode: 'crm',
    code: 'crm-dashboard',
    name: 'CRM Dashboard',
    path: '/crm/dashboard',
    titleKey: 'nav.crmDashboard',
    icon: 'LayoutDashboard',
    displayOrder: 0,
    keywords: ['crm', 'dashboard', 'overview', 'kpis', 'churn', 'revenue'],
    defaultPermissionCode: 'crm.analytics_view',
  },
  {
    moduleCode: 'crm',
    code: 'crm-customers',
    name: 'Customers 360',
    path: '/crm/customers',
    titleKey: 'nav.crmCustomers',
    icon: 'HeartHandshake',
    displayOrder: 1,
    keywords: ['crm', 'customers', '360', 'profiles', 'timeline', 'consent'],
    defaultPermissionCode: 'crm.view',
  },
  {
    moduleCode: 'crm',
    code: 'crm-loyalty',
    name: 'Loyalty',
    path: '/crm/loyalty',
    titleKey: 'nav.crmLoyalty',
    icon: 'Award',
    displayOrder: 2,
    keywords: ['loyalty', 'points', 'tiers', 'rewards', 'wallet'],
    defaultPermissionCode: 'crm.loyalty_view',
  },
  {
    moduleCode: 'crm',
    code: 'crm-segments',
    name: 'Segments',
    path: '/crm/segments',
    titleKey: 'nav.crmSegments',
    icon: 'UsersRound',
    displayOrder: 3,
    keywords: ['segments', 'audiences', 'targeting', 'rules'],
    defaultPermissionCode: 'crm.segment_view',
  },
  {
    moduleCode: 'crm',
    code: 'crm-analytics',
    name: 'Customer Analytics',
    path: '/crm/analytics',
    titleKey: 'nav.crmAnalytics',
    icon: 'ChartSpline',
    displayOrder: 4,
    keywords: ['analytics', 'clv', 'rfm', 'churn', 'retention', 'kpis'],
    defaultPermissionCode: 'crm.analytics_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-dashboard',
    name: 'Finance Dashboard',
    path: '/finance/dashboard',
    titleKey: 'nav.financeDashboard',
    icon: 'LayoutDashboard',
    displayOrder: 0,
    keywords: ['cfo', 'dashboard', 'kpis', 'profit', 'cash', 'overview'],
    defaultPermissionCode: 'finance.journal_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-accounts',
    name: 'Chart of Accounts',
    path: '/finance/accounts',
    titleKey: 'nav.financeAccounts',
    icon: 'Landmark',
    displayOrder: 1,
    keywords: ['chart of accounts', 'gl', 'accounts', 'ledger', 'coa'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-journal-types',
    name: 'Journal Types',
    path: '/finance/journal-types',
    titleKey: 'nav.financeJournalTypes',
    icon: 'ListOrdered',
    displayOrder: 2,
    keywords: ['journal types', 'daybooks', 'numbering', 'series'],
    defaultPermissionCode: 'finance.journal_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-journals',
    name: 'Journal Entries',
    path: '/finance/journals',
    titleKey: 'nav.financeJournals',
    icon: 'BookOpenCheck',
    displayOrder: 3,
    keywords: [
      'journal',
      'entries',
      'double entry',
      'trial balance',
      'posting',
    ],
    defaultPermissionCode: 'finance.journal_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-posting-queue',
    name: 'Posting Queue',
    path: '/finance/posting-queue',
    titleKey: 'nav.financePostingQueue',
    icon: 'Inbox',
    displayOrder: 4,
    keywords: ['posting queue', 'events', 'automation', 'exceptions'],
    defaultPermissionCode: 'finance.posting_manage',
  },
  {
    moduleCode: 'finance',
    code: 'finance-recurring',
    name: 'Recurring Journals',
    path: '/finance/recurring-journals',
    titleKey: 'nav.financeRecurring',
    icon: 'Repeat',
    displayOrder: 5,
    keywords: ['recurring', 'templates', 'accruals', 'schedule'],
    defaultPermissionCode: 'finance.journal_create',
  },
  {
    moduleCode: 'finance',
    code: 'finance-ar-customers',
    name: 'AR Customers',
    path: '/finance/receivables/customers',
    titleKey: 'nav.financeArCustomers',
    icon: 'UsersRound',
    displayOrder: 6,
    keywords: ['receivable', 'customers', 'aging', 'credit'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-customer-ledger',
    name: 'Customer Ledger',
    path: '/finance/receivables/ledger',
    titleKey: 'nav.financeCustomerLedger',
    icon: 'BookUser',
    displayOrder: 7,
    keywords: ['customer ledger', 'receivable', 'open items'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-customer-payments',
    name: 'Customer Payments',
    path: '/finance/receivables/payments',
    titleKey: 'nav.financeCustomerPayments',
    icon: 'HandCoins',
    displayOrder: 8,
    keywords: ['receipts', 'customer payments', 'allocation'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-credit-notes',
    name: 'Credit Notes',
    path: '/finance/receivables/credit-notes',
    titleKey: 'nav.financeCreditNotes',
    icon: 'ReceiptText',
    displayOrder: 9,
    keywords: ['credit notes', 'refund', 'receivable'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-customer-statements',
    name: 'Customer Statements',
    path: '/finance/receivables/statements',
    titleKey: 'nav.financeCustomerStatements',
    icon: 'FileText',
    displayOrder: 10,
    keywords: ['statements', 'receivable', 'dunning'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-vendors',
    name: 'Vendors',
    path: '/finance/payables/vendors',
    titleKey: 'nav.financeVendors',
    icon: 'Truck',
    displayOrder: 11,
    keywords: ['payable', 'vendors', 'suppliers', 'aging'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-vendor-ledger',
    name: 'Vendor Ledger',
    path: '/finance/payables/ledger',
    titleKey: 'nav.financeVendorLedger',
    icon: 'BookUser',
    displayOrder: 12,
    keywords: ['vendor ledger', 'payable', 'open items'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-vendor-payments',
    name: 'Vendor Payments',
    path: '/finance/payables/payments',
    titleKey: 'nav.financeVendorPayments',
    icon: 'HandCoins',
    displayOrder: 13,
    keywords: ['vendor payments', 'payment run', 'remittance'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-debit-notes',
    name: 'Debit Notes',
    path: '/finance/payables/debit-notes',
    titleKey: 'nav.financeDebitNotes',
    icon: 'ReceiptText',
    displayOrder: 14,
    keywords: ['debit notes', 'payable', 'vendor return'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-cash-accounts',
    name: 'Cash Accounts',
    path: '/finance/cash/accounts',
    titleKey: 'nav.financeCashAccounts',
    icon: 'Wallet',
    displayOrder: 15,
    keywords: ['cash', 'cashbox', 'till', 'float'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-cash-transactions',
    name: 'Cash Transactions',
    path: '/finance/cash/transactions',
    titleKey: 'nav.financeCashTransactions',
    icon: 'ArrowLeftRight',
    displayOrder: 16,
    keywords: ['cash transactions', 'receipts', 'disbursements'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-cash-sessions',
    name: 'Cash Sessions',
    path: '/finance/cash/sessions',
    titleKey: 'nav.financeCashSessions',
    icon: 'ClipboardCheck',
    displayOrder: 17,
    keywords: ['cash sessions', 'count', 'variance', 'closing'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-petty-cash',
    name: 'Petty Cash',
    path: '/finance/cash/petty-cash',
    titleKey: 'nav.financePettyCash',
    icon: 'Coins',
    displayOrder: 18,
    keywords: ['petty cash', 'imprest', 'replenish'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-bank-accounts',
    name: 'Bank Accounts',
    path: '/finance/banking/accounts',
    titleKey: 'nav.financeBankAccounts',
    icon: 'Landmark',
    displayOrder: 19,
    keywords: ['bank', 'accounts', 'iban', 'balance'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-bank-transactions',
    name: 'Bank Transactions',
    path: '/finance/banking/transactions',
    titleKey: 'nav.financeBankTransactions',
    icon: 'ArrowLeftRight',
    displayOrder: 20,
    keywords: ['bank transactions', 'deposits', 'withdrawals'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-bank-reconciliation',
    name: 'Bank Reconciliation',
    path: '/finance/banking/reconciliation',
    titleKey: 'nav.financeBankReconciliation',
    icon: 'GitCompareArrows',
    displayOrder: 21,
    keywords: ['reconciliation', 'matching', 'statement'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-cheques',
    name: 'Cheques',
    path: '/finance/banking/cheques',
    titleKey: 'nav.financeCheques',
    icon: 'ScrollText',
    displayOrder: 22,
    keywords: ['cheques', 'pdc', 'post dated', 'clearing'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-cost-centers',
    name: 'Cost Centers',
    path: '/finance/cost/cost-centers',
    titleKey: 'nav.financeCostCenters',
    icon: 'Network',
    displayOrder: 23,
    keywords: ['cost centers', 'dimensions', 'allocation'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-departments',
    name: 'Departments',
    path: '/finance/cost/departments',
    titleKey: 'nav.financeDepartments',
    icon: 'FolderTree',
    displayOrder: 24,
    keywords: ['departments', 'dimensions', 'analysis'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-projects',
    name: 'Projects',
    path: '/finance/cost/projects',
    titleKey: 'nav.financeProjects',
    icon: 'FolderKanban',
    displayOrder: 25,
    keywords: ['projects', 'profitability', 'budget'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-budget-plans',
    name: 'Budget Plans',
    path: '/finance/budgets/plans',
    titleKey: 'nav.financeBudgetPlans',
    icon: 'PiggyBank',
    displayOrder: 26,
    keywords: ['budget', 'plans', 'forecast', 'monthly'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-budget-monitoring',
    name: 'Budget Monitoring',
    path: '/finance/budgets/monitoring',
    titleKey: 'nav.financeBudgetMonitoring',
    icon: 'TrendingUp',
    displayOrder: 27,
    keywords: ['budget', 'variance', 'monitoring', 'actual'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-asset-categories',
    name: 'Asset Categories',
    path: '/finance/assets/categories',
    titleKey: 'nav.financeAssetCategories',
    icon: 'Layers',
    displayOrder: 28,
    keywords: ['assets', 'categories', 'depreciation method'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-assets',
    name: 'Assets',
    path: '/finance/assets/register',
    titleKey: 'nav.financeAssets',
    icon: 'Building2',
    displayOrder: 29,
    keywords: ['fixed assets', 'register', 'disposal'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-depreciation',
    name: 'Depreciation',
    path: '/finance/assets/depreciation',
    titleKey: 'nav.financeDepreciation',
    icon: 'TrendingDown',
    displayOrder: 30,
    keywords: ['depreciation', 'schedule', 'run'],
    defaultPermissionCode: 'finance.account_view',
  },
  {
    moduleCode: 'finance',
    code: 'finance-fiscal',
    name: 'Fiscal Calendar',
    path: '/finance/fiscal',
    titleKey: 'nav.financeFiscal',
    icon: 'CalendarRange',
    displayOrder: 31,
    keywords: ['fiscal year', 'periods', 'closing', 'locks'],
    defaultPermissionCode: 'finance.fiscal_manage',
  },
  {
    moduleCode: 'finance',
    code: 'finance-closing',
    name: 'Closing Wizard',
    path: '/finance/closing',
    titleKey: 'nav.financeClosing',
    icon: 'ClipboardCheck',
    displayOrder: 32,
    keywords: ['closing', 'year end', 'period close', 'checklist'],
    defaultPermissionCode: 'finance.fiscal_manage',
  },
  {
    moduleCode: 'finance',
    code: 'finance-settings',
    name: 'Financial Settings',
    path: '/finance/settings',
    titleKey: 'nav.financeSettings',
    icon: 'Settings2',
    displayOrder: 33,
    keywords: [
      'financial settings',
      'default accounts',
      'currencies',
      'exchange rates',
      'posting rules',
      'account mapping',
    ],
    defaultPermissionCode: 'finance.settings_manage',
  },
  {
    moduleCode: 'finance',
    code: 'finance-tax-settings',
    name: 'Tax Settings',
    path: '/finance/settings/tax',
    titleKey: 'nav.financeTaxSettings',
    icon: 'Percent',
    displayOrder: 34,
    keywords: ['tax', 'vat', 'withholding', 'returns'],
    defaultPermissionCode: 'finance.settings_manage',
  },
  {
    moduleCode: 'finance',
    code: 'finance-reports',
    name: 'Financial Reports',
    path: '/finance/reports',
    titleKey: 'nav.financeReports',
    icon: 'ChartSpline',
    displayOrder: 35,
    keywords: [
      'reports',
      'trial balance',
      'balance sheet',
      'income statement',
      'p&l',
    ],
    defaultPermissionCode: 'finance.journal_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-overview',
    name: 'HR Overview',
    path: '/hr',
    titleKey: 'nav.hr',
    icon: 'UsersRound',
    displayOrder: 0,
    keywords: ['hr', 'human resources', 'hcm', 'people', 'workforce'],
    defaultPermissionCode: 'hr.analytics_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-organization',
    name: 'Organization',
    path: '/hr/organization',
    titleKey: 'nav.hrOrganization',
    icon: 'Network',
    displayOrder: 1,
    keywords: [
      'organization',
      'org chart',
      'hierarchy',
      'companies',
      'branches',
    ],
    defaultPermissionCode: 'hr.org_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-departments',
    name: 'Departments',
    path: '/hr/departments',
    titleKey: 'nav.hrDepartments',
    icon: 'FolderTree',
    displayOrder: 2,
    keywords: ['departments', 'sections', 'divisions', 'units'],
    defaultPermissionCode: 'hr.org_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-positions',
    name: 'Positions',
    path: '/hr/positions',
    titleKey: 'nav.hrPositions',
    icon: 'BadgeCheck',
    displayOrder: 3,
    keywords: ['positions', 'jobs', 'roles', 'titles'],
    defaultPermissionCode: 'hr.org_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-job-grades',
    name: 'Job Grades',
    path: '/hr/job-grades',
    titleKey: 'nav.hrJobGrades',
    icon: 'Layers',
    displayOrder: 4,
    keywords: ['job grades', 'salary bands', 'levels', 'pay scale'],
    defaultPermissionCode: 'hr.org_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-cost-centers',
    name: 'Cost Centers',
    path: '/hr/cost-centers',
    titleKey: 'nav.hrCostCenters',
    icon: 'Landmark',
    displayOrder: 5,
    keywords: ['cost centers', 'budget', 'allocation'],
    defaultPermissionCode: 'hr.org_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-employees',
    name: 'Employees',
    path: '/hr/employees',
    titleKey: 'nav.hrEmployees',
    icon: 'UsersRound',
    displayOrder: 6,
    keywords: ['employees', 'staff', 'people', 'profiles', 'headcount'],
    defaultPermissionCode: 'hr.employee_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-recruitment',
    name: 'Recruitment',
    path: '/hr/recruitment',
    titleKey: 'nav.hrRecruitment',
    icon: 'ClipboardList',
    displayOrder: 7,
    keywords: [
      'recruitment',
      'ats',
      'vacancies',
      'candidates',
      'interviews',
      'offers',
    ],
    defaultPermissionCode: 'hr.recruitment_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-onboarding',
    name: 'Onboarding',
    path: '/hr/onboarding',
    titleKey: 'nav.hrOnboarding',
    icon: 'ClipboardCheck',
    displayOrder: 8,
    keywords: ['onboarding', 'tasks', 'new hire', 'checklist'],
    defaultPermissionCode: 'hr.recruitment_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-attendance',
    name: 'Time & Attendance',
    path: '/hr/attendance',
    titleKey: 'nav.hrAttendance',
    icon: 'CalendarClock',
    displayOrder: 9,
    keywords: ['attendance', 'time', 'shifts', 'punches', 'overtime'],
    defaultPermissionCode: 'hr.attendance_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-leave',
    name: 'Leave',
    path: '/hr/leave',
    titleKey: 'nav.hrLeave',
    icon: 'PackageCheck',
    displayOrder: 10,
    keywords: ['leave', 'time off', 'vacation', 'balances', 'requests'],
    defaultPermissionCode: 'hr.leave_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-payroll',
    name: 'Payroll',
    path: '/hr/payroll',
    titleKey: 'nav.hrPayroll',
    icon: 'Banknote',
    displayOrder: 11,
    keywords: ['payroll', 'salary', 'payslip', 'runs', 'components'],
    defaultPermissionCode: 'hr.payroll_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-performance',
    name: 'Performance',
    path: '/hr/performance',
    titleKey: 'nav.hrPerformance',
    icon: 'TrendingUp',
    displayOrder: 12,
    keywords: ['performance', 'goals', 'kpis', 'reviews', 'appraisal'],
    defaultPermissionCode: 'hr.performance_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-training',
    name: 'Learning',
    path: '/hr/training',
    titleKey: 'nav.hrTraining',
    icon: 'Award',
    displayOrder: 13,
    keywords: ['training', 'learning', 'courses', 'certificates'],
    defaultPermissionCode: 'hr.training_manage',
  },
  {
    moduleCode: 'hr',
    code: 'hr-career',
    name: 'Career',
    path: '/hr/career',
    titleKey: 'nav.hrCareer',
    icon: 'BadgeCheck',
    displayOrder: 14,
    keywords: ['career', 'succession', 'promotions', 'talent'],
    defaultPermissionCode: 'hr.employee_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-workforce',
    name: 'Workforce Planning',
    path: '/hr/workforce',
    titleKey: 'nav.hrWorkforce',
    icon: 'Network',
    displayOrder: 15,
    keywords: ['workforce', 'planning', 'skills', 'headcount', 'gap'],
    defaultPermissionCode: 'hr.employee_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-budgeting',
    name: 'HR Budgeting',
    path: '/hr/budgeting',
    titleKey: 'nav.hrBudgeting',
    icon: 'Landmark',
    displayOrder: 16,
    keywords: ['budget', 'salary budget', 'variance', 'actual'],
    defaultPermissionCode: 'hr.analytics_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-self-service',
    name: 'Self Service',
    path: '/hr/self-service',
    titleKey: 'nav.hrSelfService',
    icon: 'BellRing',
    displayOrder: 17,
    keywords: ['self service', 'ess', 'requests', 'announcements'],
    defaultPermissionCode: 'hr.employee_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-assets',
    name: 'Assets',
    path: '/hr/assets',
    titleKey: 'nav.hrAssets',
    icon: 'PackageSearch',
    displayOrder: 18,
    keywords: ['assets', 'laptop', 'vehicle', 'accountability'],
    defaultPermissionCode: 'hr.employee_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-expenses',
    name: 'Travel & Expense',
    path: '/hr/expenses',
    titleKey: 'nav.hrExpenses',
    icon: 'ReceiptText',
    displayOrder: 19,
    keywords: ['expense', 'travel', 'claims', 'reimbursement'],
    defaultPermissionCode: 'hr.expense_view',
  },
  {
    moduleCode: 'hr',
    code: 'hr-analytics',
    name: 'HR Analytics',
    path: '/hr/analytics',
    titleKey: 'nav.hrAnalytics',
    icon: 'ChartSpline',
    displayOrder: 20,
    keywords: ['analytics', 'headcount', 'turnover', 'dashboard'],
    defaultPermissionCode: 'hr.analytics_view',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-security',
    name: 'Security Center',
    path: '/settings/security',
    titleKey: 'nav.systemSecurity',
    icon: 'ShieldCheck',
    displayOrder: 0,
    keywords: ['security', 'rbac', 'modules', 'screens', 'registry', 'audit'],
    defaultPermissionCode: 'user.view',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-roles',
    name: 'Roles',
    path: '/settings/roles',
    titleKey: 'nav.systemRoles',
    icon: 'UsersRound',
    displayOrder: 1,
    keywords: ['roles', 'rbac', 'permissions', 'grants', 'custom roles'],
    defaultPermissionCode: 'role.view',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-modules',
    name: 'Modules',
    path: '/settings/modules',
    titleKey: 'nav.systemModules',
    icon: 'Boxes',
    displayOrder: 2,
    keywords: ['modules', 'menus', 'navigation', 'enable', 'disable'],
    defaultPermissionCode: 'module.manage',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-profile',
    name: 'My Profile',
    path: '/profile',
    titleKey: 'nav.profile',
    icon: 'UsersRound',
    displayOrder: 3,
    keywords: ['profile', 'account', 'self service', 'identity'],
    defaultPermissionCode: 'profile.view_self',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-access',
    name: 'Access Control',
    path: '/settings/access',
    titleKey: 'nav.systemAccess',
    icon: 'ShieldCheck',
    displayOrder: 4,
    keywords: ['access', 'permissions', 'overrides', 'rbac'],
    defaultPermissionCode: 'user.view',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-users',
    name: 'Users & Roles',
    path: '/settings/users',
    titleKey: 'nav.systemUsers',
    icon: 'UsersRound',
    displayOrder: 5,
    keywords: ['users', 'roles', 'permissions', 'access'],
    defaultPermissionCode: 'user.view',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-notifications',
    name: 'Notifications',
    path: '/settings/notifications',
    titleKey: 'nav.systemNotifications',
    icon: 'BellRing',
    displayOrder: 6,
    keywords: ['notifications', 'alerts', 'delivery', 'signals'],
    defaultPermissionCode: 'tenant.manage_settings',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-integrations',
    name: 'Integrations',
    path: '/settings/integrations',
    titleKey: 'nav.systemIntegrations',
    icon: 'PlugZap',
    displayOrder: 7,
    keywords: ['integrations', 'apis', 'connections', 'webhooks'],
    defaultPermissionCode: 'tenant.manage_settings',
  },
] as const

export const SCREEN_ACTION_DEFINITIONS: ReadonlyArray<ScreenActionDefinition> =
  [
    {
      screenCode: 'settings-users',
      code: 'user-invite',
      name: 'Invite User',
      actionKey: 'invite',
      description: 'Invite, resend, and revoke tenant invitations.',
      displayOrder: 0,
    },
    {
      screenCode: 'settings-users',
      code: 'user-update',
      name: 'Update User',
      actionKey: 'update',
      description: 'Update tenant user state and editable account fields.',
      displayOrder: 1,
    },
    {
      screenCode: 'settings-users',
      code: 'user-change-role',
      name: 'Change Role',
      actionKey: 'change_role',
      description: 'Assign or change a tenant user primary role.',
      displayOrder: 2,
    },
    {
      screenCode: 'settings-users',
      code: 'user-deactivate',
      name: 'Deactivate User',
      actionKey: 'deactivate',
      description: 'Suspend or disable tenant user access.',
      displayOrder: 3,
    },
    {
      screenCode: 'settings-access',
      code: 'permission-assign',
      name: 'Assign Permission',
      actionKey: 'assign_permission',
      description: 'Assign direct per-user permission overrides.',
      displayOrder: 0,
    },
  ] as const

// Every catalog permission maps to a module (and optionally a screen/action) plus a
// kind. Typed as a total Record so a missing/renamed permission code fails to
// compile — keeping this in lockstep with `PERMISSION_DEFINITIONS`.
export const PERMISSION_LINKS: Record<PermissionCode, PermissionLink> = {
  'tenant.view': {
    moduleCode: 'system_admin',
    screenCode: null,
    actionCode: null,
    kind: 'data',
  },
  'tenant.update': {
    moduleCode: 'system_admin',
    screenCode: null,
    actionCode: null,
    kind: 'admin',
  },
  'tenant.manage_settings': {
    moduleCode: 'system_admin',
    screenCode: 'settings-integrations',
    actionCode: null,
    kind: 'admin',
  },
  'user.view': {
    moduleCode: 'system_admin',
    screenCode: 'settings-users',
    actionCode: null,
    kind: 'screen',
  },
  'user.invite': {
    moduleCode: 'system_admin',
    screenCode: 'settings-users',
    actionCode: 'user-invite',
    kind: 'action',
  },
  'user.update': {
    moduleCode: 'system_admin',
    screenCode: 'settings-users',
    actionCode: 'user-update',
    kind: 'action',
  },
  'user.deactivate': {
    moduleCode: 'system_admin',
    screenCode: 'settings-users',
    actionCode: 'user-deactivate',
    kind: 'action',
  },
  'user.change_role': {
    moduleCode: 'system_admin',
    screenCode: 'settings-users',
    actionCode: 'user-change-role',
    kind: 'action',
  },
  'user.assign_permission': {
    moduleCode: 'system_admin',
    screenCode: 'settings-access',
    actionCode: 'permission-assign',
    kind: 'action',
  },
  'profile.view_self': {
    moduleCode: 'system_admin',
    screenCode: 'settings-profile',
    actionCode: null,
    kind: 'screen',
  },
  'profile.update_self': {
    moduleCode: 'system_admin',
    screenCode: 'settings-profile',
    actionCode: null,
    kind: 'action',
  },
  'dashboard.view': {
    moduleCode: 'overview',
    screenCode: 'dashboard',
    actionCode: null,
    kind: 'screen',
  },
  'role.view': {
    moduleCode: 'system_admin',
    screenCode: 'settings-roles',
    actionCode: null,
    kind: 'screen',
  },
  'role.manage': {
    moduleCode: 'system_admin',
    screenCode: 'settings-roles',
    actionCode: null,
    kind: 'admin',
  },
  'module.manage': {
    moduleCode: 'system_admin',
    screenCode: 'settings-modules',
    actionCode: null,
    kind: 'admin',
  },
  'res.dashboard.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-dashboard',
    actionCode: null,
    kind: 'screen',
  },
  'res.reports.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-reports',
    actionCode: null,
    kind: 'screen',
  },
  'res.analytics.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-analytics',
    actionCode: null,
    kind: 'screen',
  },
  'res.reservations.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-reservations',
    actionCode: null,
    kind: 'screen',
  },
  'res.reservations.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-reservations',
    actionCode: null,
    kind: 'action',
  },
  'res.takeaway.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-takeaway',
    actionCode: null,
    kind: 'screen',
  },
  'res.takeaway.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-takeaway',
    actionCode: null,
    kind: 'action',
  },
  'res.delivery.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-delivery',
    actionCode: null,
    kind: 'screen',
  },
  'res.delivery.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-delivery',
    actionCode: null,
    kind: 'action',
  },
  'res.qr.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-qr',
    actionCode: null,
    kind: 'screen',
  },
  'res.promotions.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-promotions',
    actionCode: null,
    kind: 'screen',
  },
  'res.promotions.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-promotions',
    actionCode: null,
    kind: 'action',
  },
  'res.giftcards.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-giftcards',
    actionCode: null,
    kind: 'screen',
  },
  'res.giftcards.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-giftcards',
    actionCode: null,
    kind: 'action',
  },
  'res.events.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-events',
    actionCode: null,
    kind: 'screen',
  },
  'res.events.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-events',
    actionCode: null,
    kind: 'action',
  },
  'res.catering.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-catering',
    actionCode: null,
    kind: 'screen',
  },
  'res.catering.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-catering',
    actionCode: null,
    kind: 'action',
  },
  'res.orders.view': {
    moduleCode: 'restaurant',
    screenCode: null,
    actionCode: null,
    kind: 'screen',
  },
  'res.orders.create': {
    moduleCode: 'restaurant',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'res.orders.update': {
    moduleCode: 'restaurant',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'res.orders.cancel': {
    moduleCode: 'restaurant',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'res.cashier.access': {
    moduleCode: 'restaurant',
    screenCode: null,
    actionCode: null,
    kind: 'screen',
  },
  'res.kitchen.access': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-kitchen',
    actionCode: null,
    kind: 'screen',
  },
  'res.kitchen.update_order_status': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-kitchen',
    actionCode: null,
    kind: 'action',
  },
  'res.floor.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-tables',
    actionCode: null,
    kind: 'action',
  },
  'res.users.view': {
    moduleCode: 'system_admin',
    screenCode: null,
    actionCode: null,
    kind: 'screen',
  },
  'res.users.manage': {
    moduleCode: 'system_admin',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'res.settings.manage': {
    moduleCode: 'system_admin',
    screenCode: null,
    actionCode: null,
    kind: 'admin',
  },
  'res.menu.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-menu',
    actionCode: null,
    kind: 'screen',
  },
  'res.menu.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-menu',
    actionCode: null,
    kind: 'action',
  },
  'res.recipe.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-menu',
    actionCode: null,
    kind: 'data',
  },
  'res.recipe.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-menu',
    actionCode: null,
    kind: 'action',
  },
  'product.view': {
    moduleCode: 'inventory',
    screenCode: 'inventory-catalog',
    actionCode: null,
    kind: 'screen',
  },
  'product.create': {
    moduleCode: 'inventory',
    screenCode: 'inventory-catalog',
    actionCode: null,
    kind: 'action',
  },
  'product.update': {
    moduleCode: 'inventory',
    screenCode: 'inventory-catalog',
    actionCode: null,
    kind: 'action',
  },
  'product.delete': {
    moduleCode: 'inventory',
    screenCode: 'inventory-catalog',
    actionCode: null,
    kind: 'action',
  },
  'product.manage_pricing': {
    moduleCode: 'inventory',
    screenCode: 'inventory-pricing',
    actionCode: null,
    kind: 'action',
  },
  'product.manage_categories': {
    moduleCode: 'inventory',
    screenCode: 'inventory-categories',
    actionCode: null,
    kind: 'action',
  },
  'supplier.view': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'data',
  },
  'supplier.manage': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'customer.view': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'data',
  },
  'customer.manage': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'tax.manage': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'admin',
  },
  'warehouse.view': {
    moduleCode: 'inventory',
    screenCode: 'inventory-outlets',
    actionCode: null,
    kind: 'screen',
  },
  'warehouse.create': {
    moduleCode: 'inventory',
    screenCode: 'inventory-outlets',
    actionCode: null,
    kind: 'action',
  },
  'warehouse.update': {
    moduleCode: 'inventory',
    screenCode: 'inventory-outlets',
    actionCode: null,
    kind: 'action',
  },
  'warehouse.manage_locations': {
    moduleCode: 'inventory',
    screenCode: 'inventory-locations',
    actionCode: null,
    kind: 'action',
  },
  'inventory.view_stock': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'screen',
  },
  'inventory.view_movements': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'data',
  },
  'inventory.reserve': {
    moduleCode: 'inventory',
    screenCode: 'inventory-reservations',
    actionCode: null,
    kind: 'action',
  },
  'inventory.manage_lots': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'action',
  },
  'inventory.manage_serials': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'action',
  },
  'inventory.manage_reorder': {
    moduleCode: 'inventory',
    screenCode: 'inventory-settings',
    actionCode: null,
    kind: 'action',
  },
  'inventory.view_valuation': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'data',
  },
  'inventory.count_view': {
    moduleCode: 'inventory',
    screenCode: 'inventory-counts',
    actionCode: null,
    kind: 'screen',
  },
  'inventory.count_manage': {
    moduleCode: 'inventory',
    screenCode: 'inventory-counts',
    actionCode: null,
    kind: 'action',
  },
  'inventory.count_approve': {
    moduleCode: 'inventory',
    screenCode: 'inventory-counts',
    actionCode: null,
    kind: 'action',
  },
  'adjustment.view': {
    moduleCode: 'inventory',
    screenCode: 'inventory-adjustments',
    actionCode: null,
    kind: 'screen',
  },
  'adjustment.create': {
    moduleCode: 'inventory',
    screenCode: 'inventory-adjustments',
    actionCode: null,
    kind: 'action',
  },
  'adjustment.post': {
    moduleCode: 'inventory',
    screenCode: 'inventory-adjustments',
    actionCode: null,
    kind: 'action',
  },
  'transfer.view': {
    moduleCode: 'inventory',
    screenCode: 'inventory-transfers',
    actionCode: null,
    kind: 'screen',
  },
  'transfer.create': {
    moduleCode: 'inventory',
    screenCode: 'inventory-transfers',
    actionCode: null,
    kind: 'action',
  },
  'transfer.ship': {
    moduleCode: 'inventory',
    screenCode: 'inventory-transfers',
    actionCode: null,
    kind: 'action',
  },
  'transfer.receive': {
    moduleCode: 'inventory',
    screenCode: 'inventory-transfers',
    actionCode: null,
    kind: 'action',
  },
  'purchase.requisition_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-requisitions',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.requisition_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-requisitions',
    actionCode: null,
    kind: 'action',
  },
  'purchase.po_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-orders',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.po_create': {
    moduleCode: 'purchase',
    screenCode: 'purchase-orders',
    actionCode: null,
    kind: 'action',
  },
  'purchase.po_approve': {
    moduleCode: 'purchase',
    screenCode: 'purchase-orders',
    actionCode: null,
    kind: 'action',
  },
  'purchase.po_receive': {
    moduleCode: 'purchase',
    screenCode: 'purchase-receipts',
    actionCode: null,
    kind: 'action',
  },
  'purchase.return_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-returns',
    actionCode: null,
    kind: 'action',
  },
  'purchase.rfq_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-rfqs',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.rfq_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-rfqs',
    actionCode: null,
    kind: 'action',
  },
  'purchase.quotation_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-quotations',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.quotation_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-quotations',
    actionCode: null,
    kind: 'action',
  },
  'purchase.quotation_award': {
    moduleCode: 'purchase',
    screenCode: 'purchase-quotations',
    actionCode: null,
    kind: 'action',
  },
  'purchase.invoice_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-invoices',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.invoice_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-invoices',
    actionCode: null,
    kind: 'action',
  },
  'purchase.invoice_match': {
    moduleCode: 'purchase',
    screenCode: 'purchase-invoices',
    actionCode: null,
    kind: 'action',
  },
  'purchase.payment_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-payments',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.payment_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-payments',
    actionCode: null,
    kind: 'action',
  },
  'purchase.landed_cost_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-receipts',
    actionCode: null,
    kind: 'action',
  },
  'purchase.debit_note_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-returns',
    actionCode: null,
    kind: 'action',
  },
  'purchase.approval_action': {
    moduleCode: 'purchase',
    screenCode: 'purchase-orders',
    actionCode: null,
    kind: 'action',
  },
  'purchase.config_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-overview',
    actionCode: null,
    kind: 'action',
  },
  'sales.order_view': {
    moduleCode: 'pos',
    screenCode: 'pos-orders',
    actionCode: null,
    kind: 'screen',
  },
  'sales.order_create': {
    moduleCode: 'pos',
    screenCode: 'pos-orders',
    actionCode: null,
    kind: 'action',
  },
  'sales.order_confirm': {
    moduleCode: 'pos',
    screenCode: 'pos-orders',
    actionCode: null,
    kind: 'action',
  },
  'sales.order_fulfill': {
    moduleCode: 'pos',
    screenCode: 'pos-orders',
    actionCode: null,
    kind: 'action',
  },
  'sales.invoice_manage': {
    moduleCode: 'pos',
    screenCode: 'pos-orders',
    actionCode: null,
    kind: 'action',
  },
  'pos.access': {
    moduleCode: 'pos',
    screenCode: 'pos-checkout',
    actionCode: null,
    kind: 'screen',
  },
  'pos.sell': {
    moduleCode: 'pos',
    screenCode: 'pos-checkout',
    actionCode: null,
    kind: 'action',
  },
  'pos.void': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'pos.session_manage': {
    moduleCode: 'pos',
    screenCode: 'pos-checkout',
    actionCode: null,
    kind: 'action',
  },
  'returns.view': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'screen',
  },
  'returns.create': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'returns.approve': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'returns.receive': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'returns.refund': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'note.manage': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'production.view': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'screen',
  },
  'production.manage_bom': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'production.create': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'production.release': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'production.consume': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'production.complete': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'crm.view': {
    moduleCode: 'crm',
    screenCode: 'crm-customers',
    actionCode: null,
    kind: 'screen',
  },
  'crm.profile_manage': {
    moduleCode: 'crm',
    screenCode: 'crm-customers',
    actionCode: null,
    kind: 'action',
  },
  'crm.timeline_view': {
    moduleCode: 'crm',
    screenCode: 'crm-customers',
    actionCode: null,
    kind: 'data',
  },
  'crm.timeline_note': {
    moduleCode: 'crm',
    screenCode: 'crm-customers',
    actionCode: null,
    kind: 'action',
  },
  'crm.loyalty_view': {
    moduleCode: 'crm',
    screenCode: 'crm-loyalty',
    actionCode: null,
    kind: 'screen',
  },
  'crm.loyalty_manage': {
    moduleCode: 'crm',
    screenCode: 'crm-loyalty',
    actionCode: null,
    kind: 'admin',
  },
  'crm.loyalty_redeem': {
    moduleCode: 'crm',
    screenCode: 'crm-loyalty',
    actionCode: null,
    kind: 'action',
  },
  'crm.loyalty_adjust': {
    moduleCode: 'crm',
    screenCode: 'crm-loyalty',
    actionCode: null,
    kind: 'action',
  },
  'crm.segment_view': {
    moduleCode: 'crm',
    screenCode: 'crm-segments',
    actionCode: null,
    kind: 'screen',
  },
  'crm.segment_manage': {
    moduleCode: 'crm',
    screenCode: 'crm-segments',
    actionCode: null,
    kind: 'action',
  },
  'crm.analytics_view': {
    moduleCode: 'crm',
    screenCode: 'crm-analytics',
    actionCode: null,
    kind: 'screen',
  },
  'crm.settings_manage': {
    moduleCode: 'crm',
    screenCode: null,
    actionCode: null,
    kind: 'admin',
  },
  'finance.account_view': {
    moduleCode: 'finance',
    screenCode: 'finance-accounts',
    actionCode: null,
    kind: 'screen',
  },
  'finance.account_manage': {
    moduleCode: 'finance',
    screenCode: 'finance-accounts',
    actionCode: null,
    kind: 'action',
  },
  'finance.fiscal_manage': {
    moduleCode: 'finance',
    screenCode: 'finance-fiscal',
    actionCode: null,
    kind: 'screen',
  },
  'finance.journal_view': {
    moduleCode: 'finance',
    screenCode: 'finance-journals',
    actionCode: null,
    kind: 'screen',
  },
  'finance.journal_create': {
    moduleCode: 'finance',
    screenCode: 'finance-journals',
    actionCode: null,
    kind: 'action',
  },
  'finance.journal_post': {
    moduleCode: 'finance',
    screenCode: 'finance-journals',
    actionCode: null,
    kind: 'action',
  },
  'finance.journal_reverse': {
    moduleCode: 'finance',
    screenCode: 'finance-journals',
    actionCode: null,
    kind: 'action',
  },
  'finance.settings_manage': {
    moduleCode: 'finance',
    screenCode: 'finance-settings',
    actionCode: null,
    kind: 'screen',
  },
  'finance.posting_manage': {
    moduleCode: 'finance',
    screenCode: 'finance-settings',
    actionCode: null,
    kind: 'action',
  },
  'hr.analytics_view': {
    moduleCode: 'hr',
    screenCode: 'hr-overview',
    actionCode: null,
    kind: 'screen',
  },
  'hr.org_view': {
    moduleCode: 'hr',
    screenCode: 'hr-organization',
    actionCode: null,
    kind: 'screen',
  },
  'hr.org_manage': {
    moduleCode: 'hr',
    screenCode: 'hr-organization',
    actionCode: null,
    kind: 'action',
  },
  'hr.employee_view': {
    moduleCode: 'hr',
    screenCode: 'hr-employees',
    actionCode: null,
    kind: 'screen',
  },
  'hr.employee_manage': {
    moduleCode: 'hr',
    screenCode: 'hr-employees',
    actionCode: null,
    kind: 'action',
  },
  'hr.recruitment_view': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'menu',
  },
  'hr.recruitment_manage': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'hr.attendance_view': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'menu',
  },
  'hr.attendance_manage': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'hr.leave_view': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'menu',
  },
  'hr.leave_request': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'hr.leave_approve': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'hr.payroll_view': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'menu',
  },
  'hr.payroll_run': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'hr.payroll_post': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'hr.loan_manage': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'hr.performance_view': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'menu',
  },
  'hr.performance_manage': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'hr.training_manage': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'hr.expense_view': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'menu',
  },
  'hr.expense_manage': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'hr.expense_approve': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'hr.settings_manage': {
    moduleCode: 'hr',
    screenCode: null,
    actionCode: null,
    kind: 'admin',
  },
}
