import type { PermissionCode } from '#/features/auth/rbac-catalog'

// Plain-data bootstrap catalog for the dynamic RBAC registry (modules / screens /
// actions / permission links). Intentionally free of React or Lucide imports so it
// is safe to import from the `tsx prisma/seed.ts` runner. `icon` values are Lucide
// icon *names* (strings), decoupled from the component references used in
// `src/lib/navigation/app-nav.ts`. In the DB-authoritative model this is bootstrap
// input for the seed, not the runtime source of truth.

export type PermissionKindCode =
  | 'screen'
  | 'menu'
  | 'action'
  | 'api'
  | 'data'
  | 'admin'

export type ModuleDefinition = {
  code: string
  name: string
  description: string
  icon: string
  displayOrder: number
  titleKey: string
  rootPath: string
}

export type ScreenDefinition = {
  moduleCode: string
  code: string
  name: string
  path: string
  titleKey: string
  icon: string
  displayOrder: number
  keywords: Array<string>
  defaultPermissionCode: PermissionCode | null
}

export type ScreenActionDefinition = {
  screenCode: string
  code: string
  name: string
  actionKey: string
  description: string
  displayOrder: number
}

export type PermissionLink = {
  moduleCode: string
  screenCode: string | null
  actionCode: string | null
  kind: PermissionKindCode
}

export const MODULE_DEFINITIONS: ReadonlyArray<ModuleDefinition> = [
  {
    code: 'overview',
    name: 'Overview',
    description: 'Cross-tenant control room and dashboards.',
    icon: 'LayoutDashboard',
    displayOrder: 0,
    titleKey: 'nav.dashboard',
    rootPath: '/dashboard',
  },
  {
    code: 'inventory',
    name: 'Inventory',
    description: 'Stock, catalog, outlets, and supply coverage.',
    icon: 'Boxes',
    displayOrder: 1,
    titleKey: 'nav.inventory',
    rootPath: '/inventory',
  },
  {
    code: 'purchase',
    name: 'Purchasing',
    description:
      'Procurement: suppliers, RFQs, orders, receipts, invoices, and payments.',
    icon: 'ShoppingCart',
    displayOrder: 2,
    titleKey: 'nav.purchase',
    rootPath: '/purchase',
  },
  {
    code: 'restaurant',
    name: 'Restaurant',
    description: 'Kitchen, menu engineering, and floor service.',
    icon: 'ChefHat',
    displayOrder: 3,
    titleKey: 'nav.restaurant',
    rootPath: '/restaurant/kitchen',
  },
  {
    code: 'pos',
    name: 'POS',
    description: 'Checkout, orders, and returns.',
    icon: 'ShoppingBasket',
    displayOrder: 4,
    titleKey: 'nav.pos',
    rootPath: '/pos',
  },
  {
    code: 'crm',
    name: 'CRM',
    description:
      'Customer intelligence: profiles, loyalty, segments, and analytics.',
    icon: 'HeartHandshake',
    displayOrder: 5,
    titleKey: 'nav.crm',
    rootPath: '/crm/customers',
  },
  {
    code: 'system_admin',
    name: 'System Admin',
    description: 'Users, roles, access control, and configuration.',
    icon: 'ShieldCheck',
    displayOrder: 6,
    titleKey: 'nav.systemAdmin',
    rootPath: '/settings/security',
  },
] as const

export const SCREEN_DEFINITIONS: ReadonlyArray<ScreenDefinition> = [
  {
    moduleCode: 'overview',
    code: 'dashboard',
    name: 'Dashboard',
    path: '/dashboard',
    titleKey: 'nav.dashboard',
    icon: 'LayoutDashboard',
    displayOrder: 0,
    keywords: ['dashboard', 'overview', 'control room', 'briefing'],
    defaultPermissionCode: 'dashboard.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-overview',
    name: 'Overview',
    path: '/inventory',
    titleKey: 'nav.inventoryOverview',
    icon: 'PackageSearch',
    displayOrder: 0,
    keywords: ['inventory overview', 'coverage', 'reorder', 'stock'],
    defaultPermissionCode: 'inventory.view_stock',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-catalog',
    name: 'Catalog',
    path: '/inventory/catalog',
    titleKey: 'nav.inventoryCatalog',
    icon: 'ClipboardList',
    displayOrder: 1,
    keywords: ['catalog', 'products', 'assortment', 'sku'],
    defaultPermissionCode: 'product.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-outlets',
    name: 'Outlets',
    path: '/outlets',
    titleKey: 'nav.inventoryOutlets',
    icon: 'MapPinned',
    displayOrder: 2,
    keywords: ['outlets', 'stores', 'locations', 'coverage'],
    defaultPermissionCode: 'warehouse.view',
  },
  {
    moduleCode: 'inventory',
    code: 'inventory-stock',
    name: 'Stock Ledger',
    path: '/inventory/stock',
    titleKey: 'nav.inventoryStock',
    icon: 'ReceiptText',
    displayOrder: 3,
    keywords: ['stock ledger', 'movements', 'thresholds', 'balance'],
    defaultPermissionCode: 'inventory.view_stock',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-overview',
    name: 'Overview',
    path: '/purchase',
    titleKey: 'nav.purchaseOverview',
    icon: 'ShoppingCart',
    displayOrder: 0,
    keywords: ['purchasing', 'procurement', 'overview', 'buyer'],
    defaultPermissionCode: 'purchase.po_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-suppliers',
    name: 'Suppliers',
    path: '/purchase/suppliers',
    titleKey: 'nav.purchaseSuppliers',
    icon: 'Truck',
    displayOrder: 1,
    keywords: ['suppliers', 'vendors', 'contacts', 'bank accounts'],
    defaultPermissionCode: 'supplier.view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-requisitions',
    name: 'Requisitions',
    path: '/purchase/requisitions',
    titleKey: 'nav.purchaseRequisitions',
    icon: 'ClipboardList',
    displayOrder: 2,
    keywords: ['requisitions', 'purchase requests', 'pr'],
    defaultPermissionCode: 'purchase.requisition_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-rfqs',
    name: 'RFQs',
    path: '/purchase/rfqs',
    titleKey: 'nav.purchaseRfqs',
    icon: 'FileQuestion',
    displayOrder: 3,
    keywords: ['rfq', 'request for quotation', 'tender'],
    defaultPermissionCode: 'purchase.rfq_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-quotations',
    name: 'Quotations',
    path: '/purchase/quotations',
    titleKey: 'nav.purchaseQuotations',
    icon: 'FileText',
    displayOrder: 4,
    keywords: ['quotations', 'supplier quotes', 'comparison'],
    defaultPermissionCode: 'purchase.quotation_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-orders',
    name: 'Purchase Orders',
    path: '/purchase/orders',
    titleKey: 'nav.purchaseOrders',
    icon: 'ScrollText',
    displayOrder: 5,
    keywords: ['purchase orders', 'po', 'buying'],
    defaultPermissionCode: 'purchase.po_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-receipts',
    name: 'Goods Receipts',
    path: '/purchase/receipts',
    titleKey: 'nav.purchaseReceipts',
    icon: 'PackageCheck',
    displayOrder: 6,
    keywords: ['goods receipt', 'grn', 'receiving', 'inspection'],
    defaultPermissionCode: 'purchase.po_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-invoices',
    name: 'Supplier Invoices',
    path: '/purchase/invoices',
    titleKey: 'nav.purchaseInvoices',
    icon: 'ReceiptText',
    displayOrder: 7,
    keywords: ['supplier invoices', 'bills', 'payables', 'three-way match'],
    defaultPermissionCode: 'purchase.invoice_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-payments',
    name: 'Payments',
    path: '/purchase/payments',
    titleKey: 'nav.purchasePayments',
    icon: 'Banknote',
    displayOrder: 8,
    keywords: ['supplier payments', 'ap', 'settlements', 'allocations'],
    defaultPermissionCode: 'purchase.payment_view',
  },
  {
    moduleCode: 'purchase',
    code: 'purchase-returns',
    name: 'Returns & Debit Notes',
    path: '/purchase/returns',
    titleKey: 'nav.purchaseReturns',
    icon: 'Undo2',
    displayOrder: 9,
    keywords: ['purchase returns', 'debit notes', 'rtv'],
    defaultPermissionCode: 'purchase.po_view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-kitchen',
    name: 'Kitchen Board',
    path: '/restaurant/kitchen',
    titleKey: 'nav.restaurantKitchen',
    icon: 'ChefHat',
    displayOrder: 0,
    keywords: ['kitchen', 'board', 'prep', 'queue'],
    defaultPermissionCode: 'res.kitchen.access',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-menu',
    name: 'Menu Engineering',
    path: '/restaurant/menu',
    titleKey: 'nav.restaurantMenu',
    icon: 'ShoppingBasket',
    displayOrder: 1,
    keywords: ['menu', 'items', 'pricing', 'engineering'],
    defaultPermissionCode: 'res.menu.view',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-tables',
    name: 'Table Service',
    path: '/restaurant/tables',
    titleKey: 'nav.restaurantTables',
    icon: 'ReceiptText',
    displayOrder: 2,
    keywords: ['tables', 'service', 'covers', 'floor'],
    defaultPermissionCode: 'res.floor.manage',
  },
  {
    moduleCode: 'restaurant',
    code: 'restaurant-settings',
    name: 'Restaurant Setup',
    path: '/restaurant/settings',
    titleKey: 'nav.restaurantSettings',
    icon: 'Settings',
    displayOrder: 3,
    keywords: [
      'restaurant',
      'branches',
      'tables',
      'service types',
      'stations',
      'tax',
      'setup',
    ],
    defaultPermissionCode: 'res.settings.manage',
  },
  {
    moduleCode: 'pos',
    code: 'pos-checkout',
    name: 'Checkout',
    path: '/pos',
    titleKey: 'nav.posCheckout',
    icon: 'ShoppingBasket',
    displayOrder: 0,
    keywords: ['checkout', 'basket', 'draft', 'scan'],
    defaultPermissionCode: 'dashboard.view',
  },
  {
    moduleCode: 'pos',
    code: 'pos-orders',
    name: 'Orders',
    path: '/pos/orders',
    titleKey: 'nav.posOrders',
    icon: 'ClipboardList',
    displayOrder: 1,
    keywords: ['orders', 'queue', 'tickets', 'history'],
    defaultPermissionCode: 'res.orders.view',
  },
  {
    moduleCode: 'pos',
    code: 'pos-returns',
    name: 'Returns',
    path: '/pos/returns',
    titleKey: 'nav.posReturns',
    icon: 'RotateCcw',
    displayOrder: 2,
    keywords: ['returns', 'refunds', 'voids', 'exceptions'],
    defaultPermissionCode: 'res.orders.cancel',
  },
  {
    moduleCode: 'crm',
    code: 'crm-customers',
    name: 'Customers 360',
    path: '/crm/customers',
    titleKey: 'nav.crmCustomers',
    icon: 'HeartHandshake',
    displayOrder: 0,
    keywords: ['crm', 'customers', '360', 'profiles', 'timeline', 'consent'],
    defaultPermissionCode: 'crm.view',
  },
  {
    moduleCode: 'crm',
    code: 'crm-loyalty',
    name: 'Loyalty',
    path: '/crm/loyalty',
    titleKey: 'nav.crmLoyalty',
    icon: 'Award',
    displayOrder: 1,
    keywords: ['loyalty', 'points', 'tiers', 'rewards', 'wallet'],
    defaultPermissionCode: 'crm.loyalty_view',
  },
  {
    moduleCode: 'crm',
    code: 'crm-segments',
    name: 'Segments',
    path: '/crm/segments',
    titleKey: 'nav.crmSegments',
    icon: 'UsersRound',
    displayOrder: 2,
    keywords: ['segments', 'audiences', 'targeting', 'rules'],
    defaultPermissionCode: 'crm.segment_view',
  },
  {
    moduleCode: 'crm',
    code: 'crm-analytics',
    name: 'Customer Analytics',
    path: '/crm/analytics',
    titleKey: 'nav.crmAnalytics',
    icon: 'ChartSpline',
    displayOrder: 3,
    keywords: ['analytics', 'clv', 'rfm', 'churn', 'retention', 'kpis'],
    defaultPermissionCode: 'crm.analytics_view',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-security',
    name: 'Security Center',
    path: '/settings/security',
    titleKey: 'nav.systemSecurity',
    icon: 'ShieldCheck',
    displayOrder: 0,
    keywords: ['security', 'rbac', 'modules', 'screens', 'registry', 'audit'],
    defaultPermissionCode: 'user.view',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-roles',
    name: 'Roles',
    path: '/settings/roles',
    titleKey: 'nav.systemRoles',
    icon: 'UsersRound',
    displayOrder: 1,
    keywords: ['roles', 'rbac', 'permissions', 'grants', 'custom roles'],
    defaultPermissionCode: 'role.view',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-modules',
    name: 'Modules',
    path: '/settings/modules',
    titleKey: 'nav.systemModules',
    icon: 'Boxes',
    displayOrder: 2,
    keywords: ['modules', 'menus', 'navigation', 'enable', 'disable'],
    defaultPermissionCode: 'module.manage',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-profile',
    name: 'My Profile',
    path: '/profile',
    titleKey: 'nav.profile',
    icon: 'UsersRound',
    displayOrder: 3,
    keywords: ['profile', 'account', 'self service', 'identity'],
    defaultPermissionCode: 'profile.view_self',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-access',
    name: 'Access Control',
    path: '/settings/access',
    titleKey: 'nav.systemAccess',
    icon: 'ShieldCheck',
    displayOrder: 4,
    keywords: ['access', 'permissions', 'overrides', 'rbac'],
    defaultPermissionCode: 'user.view',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-users',
    name: 'Users & Roles',
    path: '/settings/users',
    titleKey: 'nav.systemUsers',
    icon: 'UsersRound',
    displayOrder: 5,
    keywords: ['users', 'roles', 'permissions', 'access'],
    defaultPermissionCode: 'user.view',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-notifications',
    name: 'Notifications',
    path: '/settings/notifications',
    titleKey: 'nav.systemNotifications',
    icon: 'BellRing',
    displayOrder: 6,
    keywords: ['notifications', 'alerts', 'delivery', 'signals'],
    defaultPermissionCode: 'tenant.manage_settings',
  },
  {
    moduleCode: 'system_admin',
    code: 'settings-integrations',
    name: 'Integrations',
    path: '/settings/integrations',
    titleKey: 'nav.systemIntegrations',
    icon: 'PlugZap',
    displayOrder: 7,
    keywords: ['integrations', 'apis', 'connections', 'webhooks'],
    defaultPermissionCode: 'tenant.manage_settings',
  },
] as const

export const SCREEN_ACTION_DEFINITIONS: ReadonlyArray<ScreenActionDefinition> =
  [
    {
      screenCode: 'settings-users',
      code: 'user-invite',
      name: 'Invite User',
      actionKey: 'invite',
      description: 'Invite, resend, and revoke tenant invitations.',
      displayOrder: 0,
    },
    {
      screenCode: 'settings-users',
      code: 'user-update',
      name: 'Update User',
      actionKey: 'update',
      description: 'Update tenant user state and editable account fields.',
      displayOrder: 1,
    },
    {
      screenCode: 'settings-users',
      code: 'user-change-role',
      name: 'Change Role',
      actionKey: 'change_role',
      description: 'Assign or change a tenant user primary role.',
      displayOrder: 2,
    },
    {
      screenCode: 'settings-users',
      code: 'user-deactivate',
      name: 'Deactivate User',
      actionKey: 'deactivate',
      description: 'Suspend or disable tenant user access.',
      displayOrder: 3,
    },
    {
      screenCode: 'settings-access',
      code: 'permission-assign',
      name: 'Assign Permission',
      actionKey: 'assign_permission',
      description: 'Assign direct per-user permission overrides.',
      displayOrder: 0,
    },
  ] as const

// Every catalog permission maps to a module (and optionally a screen/action) plus a
// kind. Typed as a total Record so a missing/renamed permission code fails to
// compile — keeping this in lockstep with `PERMISSION_DEFINITIONS`.
export const PERMISSION_LINKS: Record<PermissionCode, PermissionLink> = {
  'tenant.view': {
    moduleCode: 'system_admin',
    screenCode: null,
    actionCode: null,
    kind: 'data',
  },
  'tenant.update': {
    moduleCode: 'system_admin',
    screenCode: null,
    actionCode: null,
    kind: 'admin',
  },
  'tenant.manage_settings': {
    moduleCode: 'system_admin',
    screenCode: 'settings-integrations',
    actionCode: null,
    kind: 'admin',
  },
  'user.view': {
    moduleCode: 'system_admin',
    screenCode: 'settings-users',
    actionCode: null,
    kind: 'screen',
  },
  'user.invite': {
    moduleCode: 'system_admin',
    screenCode: 'settings-users',
    actionCode: 'user-invite',
    kind: 'action',
  },
  'user.update': {
    moduleCode: 'system_admin',
    screenCode: 'settings-users',
    actionCode: 'user-update',
    kind: 'action',
  },
  'user.deactivate': {
    moduleCode: 'system_admin',
    screenCode: 'settings-users',
    actionCode: 'user-deactivate',
    kind: 'action',
  },
  'user.change_role': {
    moduleCode: 'system_admin',
    screenCode: 'settings-users',
    actionCode: 'user-change-role',
    kind: 'action',
  },
  'user.assign_permission': {
    moduleCode: 'system_admin',
    screenCode: 'settings-access',
    actionCode: 'permission-assign',
    kind: 'action',
  },
  'profile.view_self': {
    moduleCode: 'system_admin',
    screenCode: 'settings-profile',
    actionCode: null,
    kind: 'screen',
  },
  'profile.update_self': {
    moduleCode: 'system_admin',
    screenCode: 'settings-profile',
    actionCode: null,
    kind: 'action',
  },
  'dashboard.view': {
    moduleCode: 'overview',
    screenCode: 'dashboard',
    actionCode: null,
    kind: 'screen',
  },
  'role.view': {
    moduleCode: 'system_admin',
    screenCode: 'settings-roles',
    actionCode: null,
    kind: 'screen',
  },
  'role.manage': {
    moduleCode: 'system_admin',
    screenCode: 'settings-roles',
    actionCode: null,
    kind: 'admin',
  },
  'module.manage': {
    moduleCode: 'system_admin',
    screenCode: 'settings-modules',
    actionCode: null,
    kind: 'admin',
  },
  'res.dashboard.view': {
    moduleCode: 'restaurant',
    screenCode: null,
    actionCode: null,
    kind: 'screen',
  },
  'res.orders.view': {
    moduleCode: 'restaurant',
    screenCode: null,
    actionCode: null,
    kind: 'screen',
  },
  'res.orders.create': {
    moduleCode: 'restaurant',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'res.orders.update': {
    moduleCode: 'restaurant',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'res.orders.cancel': {
    moduleCode: 'restaurant',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'res.cashier.access': {
    moduleCode: 'restaurant',
    screenCode: null,
    actionCode: null,
    kind: 'screen',
  },
  'res.kitchen.access': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-kitchen',
    actionCode: null,
    kind: 'screen',
  },
  'res.kitchen.update_order_status': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-kitchen',
    actionCode: null,
    kind: 'action',
  },
  'res.floor.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-tables',
    actionCode: null,
    kind: 'action',
  },
  'res.users.view': {
    moduleCode: 'system_admin',
    screenCode: null,
    actionCode: null,
    kind: 'screen',
  },
  'res.users.manage': {
    moduleCode: 'system_admin',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'res.settings.manage': {
    moduleCode: 'system_admin',
    screenCode: null,
    actionCode: null,
    kind: 'admin',
  },
  'res.menu.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-menu',
    actionCode: null,
    kind: 'screen',
  },
  'res.menu.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-menu',
    actionCode: null,
    kind: 'action',
  },
  'res.recipe.view': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-menu',
    actionCode: null,
    kind: 'data',
  },
  'res.recipe.manage': {
    moduleCode: 'restaurant',
    screenCode: 'restaurant-menu',
    actionCode: null,
    kind: 'action',
  },
  'product.view': {
    moduleCode: 'inventory',
    screenCode: 'inventory-catalog',
    actionCode: null,
    kind: 'screen',
  },
  'product.create': {
    moduleCode: 'inventory',
    screenCode: 'inventory-catalog',
    actionCode: null,
    kind: 'action',
  },
  'product.update': {
    moduleCode: 'inventory',
    screenCode: 'inventory-catalog',
    actionCode: null,
    kind: 'action',
  },
  'product.delete': {
    moduleCode: 'inventory',
    screenCode: 'inventory-catalog',
    actionCode: null,
    kind: 'action',
  },
  'product.manage_pricing': {
    moduleCode: 'inventory',
    screenCode: 'inventory-catalog',
    actionCode: null,
    kind: 'action',
  },
  'product.manage_categories': {
    moduleCode: 'inventory',
    screenCode: 'inventory-catalog',
    actionCode: null,
    kind: 'action',
  },
  'supplier.view': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'data',
  },
  'supplier.manage': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'customer.view': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'data',
  },
  'customer.manage': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'tax.manage': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'admin',
  },
  'warehouse.view': {
    moduleCode: 'inventory',
    screenCode: 'inventory-outlets',
    actionCode: null,
    kind: 'screen',
  },
  'warehouse.create': {
    moduleCode: 'inventory',
    screenCode: 'inventory-outlets',
    actionCode: null,
    kind: 'action',
  },
  'warehouse.update': {
    moduleCode: 'inventory',
    screenCode: 'inventory-outlets',
    actionCode: null,
    kind: 'action',
  },
  'warehouse.manage_locations': {
    moduleCode: 'inventory',
    screenCode: 'inventory-outlets',
    actionCode: null,
    kind: 'action',
  },
  'inventory.view_stock': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'screen',
  },
  'inventory.view_movements': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'data',
  },
  'inventory.reserve': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'action',
  },
  'inventory.manage_lots': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'action',
  },
  'inventory.manage_serials': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'action',
  },
  'inventory.manage_reorder': {
    moduleCode: 'inventory',
    screenCode: 'inventory-overview',
    actionCode: null,
    kind: 'action',
  },
  'inventory.view_valuation': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'data',
  },
  'adjustment.view': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'screen',
  },
  'adjustment.create': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'action',
  },
  'adjustment.post': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'action',
  },
  'transfer.view': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'screen',
  },
  'transfer.create': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'action',
  },
  'transfer.ship': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'action',
  },
  'transfer.receive': {
    moduleCode: 'inventory',
    screenCode: 'inventory-stock',
    actionCode: null,
    kind: 'action',
  },
  'purchase.requisition_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-requisitions',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.requisition_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-requisitions',
    actionCode: null,
    kind: 'action',
  },
  'purchase.po_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-orders',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.po_create': {
    moduleCode: 'purchase',
    screenCode: 'purchase-orders',
    actionCode: null,
    kind: 'action',
  },
  'purchase.po_approve': {
    moduleCode: 'purchase',
    screenCode: 'purchase-orders',
    actionCode: null,
    kind: 'action',
  },
  'purchase.po_receive': {
    moduleCode: 'purchase',
    screenCode: 'purchase-receipts',
    actionCode: null,
    kind: 'action',
  },
  'purchase.return_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-returns',
    actionCode: null,
    kind: 'action',
  },
  'purchase.rfq_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-rfqs',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.rfq_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-rfqs',
    actionCode: null,
    kind: 'action',
  },
  'purchase.quotation_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-quotations',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.quotation_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-quotations',
    actionCode: null,
    kind: 'action',
  },
  'purchase.quotation_award': {
    moduleCode: 'purchase',
    screenCode: 'purchase-quotations',
    actionCode: null,
    kind: 'action',
  },
  'purchase.invoice_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-invoices',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.invoice_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-invoices',
    actionCode: null,
    kind: 'action',
  },
  'purchase.invoice_match': {
    moduleCode: 'purchase',
    screenCode: 'purchase-invoices',
    actionCode: null,
    kind: 'action',
  },
  'purchase.payment_view': {
    moduleCode: 'purchase',
    screenCode: 'purchase-payments',
    actionCode: null,
    kind: 'screen',
  },
  'purchase.payment_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-payments',
    actionCode: null,
    kind: 'action',
  },
  'purchase.landed_cost_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-receipts',
    actionCode: null,
    kind: 'action',
  },
  'purchase.debit_note_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-returns',
    actionCode: null,
    kind: 'action',
  },
  'purchase.approval_action': {
    moduleCode: 'purchase',
    screenCode: 'purchase-orders',
    actionCode: null,
    kind: 'action',
  },
  'purchase.config_manage': {
    moduleCode: 'purchase',
    screenCode: 'purchase-overview',
    actionCode: null,
    kind: 'action',
  },
  'sales.order_view': {
    moduleCode: 'pos',
    screenCode: 'pos-orders',
    actionCode: null,
    kind: 'screen',
  },
  'sales.order_create': {
    moduleCode: 'pos',
    screenCode: 'pos-orders',
    actionCode: null,
    kind: 'action',
  },
  'sales.order_confirm': {
    moduleCode: 'pos',
    screenCode: 'pos-orders',
    actionCode: null,
    kind: 'action',
  },
  'sales.order_fulfill': {
    moduleCode: 'pos',
    screenCode: 'pos-orders',
    actionCode: null,
    kind: 'action',
  },
  'sales.invoice_manage': {
    moduleCode: 'pos',
    screenCode: 'pos-orders',
    actionCode: null,
    kind: 'action',
  },
  'pos.access': {
    moduleCode: 'pos',
    screenCode: 'pos-checkout',
    actionCode: null,
    kind: 'screen',
  },
  'pos.sell': {
    moduleCode: 'pos',
    screenCode: 'pos-checkout',
    actionCode: null,
    kind: 'action',
  },
  'pos.void': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'pos.session_manage': {
    moduleCode: 'pos',
    screenCode: 'pos-checkout',
    actionCode: null,
    kind: 'action',
  },
  'returns.view': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'screen',
  },
  'returns.create': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'returns.approve': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'returns.receive': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'returns.refund': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'note.manage': {
    moduleCode: 'pos',
    screenCode: 'pos-returns',
    actionCode: null,
    kind: 'action',
  },
  'production.view': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'screen',
  },
  'production.manage_bom': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'production.create': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'production.release': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'production.consume': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'production.complete': {
    moduleCode: 'inventory',
    screenCode: null,
    actionCode: null,
    kind: 'action',
  },
  'crm.view': {
    moduleCode: 'crm',
    screenCode: 'crm-customers',
    actionCode: null,
    kind: 'screen',
  },
  'crm.profile_manage': {
    moduleCode: 'crm',
    screenCode: 'crm-customers',
    actionCode: null,
    kind: 'action',
  },
  'crm.timeline_view': {
    moduleCode: 'crm',
    screenCode: 'crm-customers',
    actionCode: null,
    kind: 'data',
  },
  'crm.timeline_note': {
    moduleCode: 'crm',
    screenCode: 'crm-customers',
    actionCode: null,
    kind: 'action',
  },
  'crm.loyalty_view': {
    moduleCode: 'crm',
    screenCode: 'crm-loyalty',
    actionCode: null,
    kind: 'screen',
  },
  'crm.loyalty_manage': {
    moduleCode: 'crm',
    screenCode: 'crm-loyalty',
    actionCode: null,
    kind: 'admin',
  },
  'crm.loyalty_redeem': {
    moduleCode: 'crm',
    screenCode: 'crm-loyalty',
    actionCode: null,
    kind: 'action',
  },
  'crm.loyalty_adjust': {
    moduleCode: 'crm',
    screenCode: 'crm-loyalty',
    actionCode: null,
    kind: 'action',
  },
  'crm.segment_view': {
    moduleCode: 'crm',
    screenCode: 'crm-segments',
    actionCode: null,
    kind: 'screen',
  },
  'crm.segment_manage': {
    moduleCode: 'crm',
    screenCode: 'crm-segments',
    actionCode: null,
    kind: 'action',
  },
  'crm.analytics_view': {
    moduleCode: 'crm',
    screenCode: 'crm-analytics',
    actionCode: null,
    kind: 'screen',
  },
  'crm.settings_manage': {
    moduleCode: 'crm',
    screenCode: null,
    actionCode: null,
    kind: 'admin',
  },
}
