export const ROLE_CODE_ALIASES: Readonly<Partial<Record<string, string>>> = {
  'res:cachier': 'res:cashier',
} as const

export function normalizeRoleCode(roleCode: string) {
  const normalizedRoleCode = roleCode.trim().toLowerCase()

  return ROLE_CODE_ALIASES[normalizedRoleCode] ?? normalizedRoleCode
}

export const ROLE_DEFINITIONS = [
  {
    code: 'super_admin',
    name: 'Super Admin',
    description:
      'Tenant owner-grade access across all tenant and restaurant controls.',
    isSystem: true,
    rank: 100,
  },
  {
    code: 'res:super_admin',
    name: 'Restaurant Super Admin',
    description:
      'Restaurant operational super admin with staff and settings control.',
    isSystem: true,
    rank: 90,
  },
  {
    code: 'admin',
    name: 'Admin',
    description: 'Tenant administrator with user and dashboard access.',
    isSystem: true,
    rank: 80,
  },
  {
    code: 'res:admin',
    name: 'Restaurant Admin',
    description:
      'Restaurant administrator with order oversight and limited staff visibility.',
    isSystem: true,
    rank: 70,
  },
  {
    code: 'res:floor_manager',
    name: 'Floor Manager',
    description: 'Front-of-house manager focused on live order coordination.',
    isSystem: true,
    rank: 60,
  },
  {
    code: 'cashier',
    name: 'Cashier',
    description:
      'Generic cashier access for dashboard and self-service profile actions.',
    isSystem: true,
    rank: 50,
  },
  {
    code: 'res:cashier',
    name: 'Restaurant Cashier',
    description:
      'Restaurant cashier with order entry and cashier interface access.',
    isSystem: true,
    rank: 45,
  },
  {
    code: 'res:kitchen',
    name: 'Kitchen',
    description: 'Kitchen role for fulfillment and order status progression.',
    isSystem: true,
    rank: 40,
  },
  {
    code: 'res:user',
    name: 'Restaurant User',
    description: 'Basic restaurant access with self-profile permissions.',
    isSystem: true,
    rank: 30,
  },
  {
    code: 'inventory_manager',
    name: 'Inventory Manager',
    description:
      'Manages the product catalog, master data, and inventory operations.',
    isSystem: true,
    rank: 65,
  },
  {
    code: 'warehouse_manager',
    name: 'Warehouse Manager',
    description: 'Manages warehouses, locations, stock, and adjustments.',
    isSystem: true,
    rank: 62,
  },
  {
    code: 'purchasing_officer',
    name: 'Purchasing Officer',
    description:
      'Manages requisitions, purchase orders, goods receipts, and returns.',
    isSystem: true,
    rank: 58,
  },
  {
    code: 'sales_manager',
    name: 'Sales Manager',
    description: 'Manages sales orders, invoices, and customers.',
    isSystem: true,
    rank: 56,
  },
  {
    code: 'pos_cashier',
    name: 'POS Cashier',
    description:
      'Operates the point of sale — sells, takes payment, manages the drawer.',
    isSystem: true,
    rank: 48,
  },
  {
    code: 'production_manager',
    name: 'Production Manager',
    description:
      'Manages bills of materials and production orders through to finished goods.',
    isSystem: true,
    rank: 60,
  },
  {
    code: 'crm_manager',
    name: 'CRM Manager',
    description:
      'Manages customer intelligence: profiles, loyalty, segments, and CRM analytics.',
    isSystem: true,
    rank: 57,
  },
  {
    code: 'finance_manager',
    name: 'Finance Manager',
    description:
      'Manages the accounting engine: chart of accounts, fiscal calendar, journals, and financial settings.',
    isSystem: true,
    rank: 63,
  },
] as const

export const PERMISSION_DEFINITIONS = [
  {
    code: 'tenant.view',
    name: 'View Tenant',
    moduleKey: 'tenant',
    actionKey: 'view',
    description: 'View tenant data and scoped settings.',
  },
  {
    code: 'tenant.update',
    name: 'Update Tenant',
    moduleKey: 'tenant',
    actionKey: 'update',
    description: 'Update tenant details and configuration.',
  },
  {
    code: 'tenant.manage_settings',
    name: 'Manage Tenant Settings',
    moduleKey: 'tenant',
    actionKey: 'manage_settings',
    description: 'Manage tenant settings and integrations.',
  },
  {
    code: 'user.view',
    name: 'View Users',
    moduleKey: 'user',
    actionKey: 'view',
    description: 'View tenant users and invitations.',
  },
  {
    code: 'user.invite',
    name: 'Invite Users',
    moduleKey: 'user',
    actionKey: 'invite',
    description: 'Invite, resend, revoke, and manage invitation flow.',
  },
  {
    code: 'user.update',
    name: 'Update Users',
    moduleKey: 'user',
    actionKey: 'update',
    description: 'Update tenant user state and editable account fields.',
  },
  {
    code: 'user.deactivate',
    name: 'Deactivate Users',
    moduleKey: 'user',
    actionKey: 'deactivate',
    description: 'Suspend or disable tenant user access.',
  },
  {
    code: 'user.change_role',
    name: 'Change User Role',
    moduleKey: 'user',
    actionKey: 'change_role',
    description: 'Assign or change tenant user primary roles.',
  },
  {
    code: 'user.assign_permission',
    name: 'Assign User Permission',
    moduleKey: 'user',
    actionKey: 'assign_permission',
    description: 'Assign direct user permission overrides.',
  },
  {
    code: 'profile.view_self',
    name: 'View Own Profile',
    moduleKey: 'profile',
    actionKey: 'view_self',
    description: 'View the authenticated user profile.',
  },
  {
    code: 'profile.update_self',
    name: 'Update Own Profile',
    moduleKey: 'profile',
    actionKey: 'update_self',
    description: 'Update the authenticated user profile.',
  },
  {
    code: 'dashboard.view',
    name: 'View Dashboard',
    moduleKey: 'dashboard',
    actionKey: 'view',
    description: 'Access the tenant dashboard.',
  },
  {
    code: 'role.view',
    name: 'View Roles',
    moduleKey: 'role',
    actionKey: 'view',
    description: 'View tenant roles and their permission mappings.',
  },
  {
    code: 'role.manage',
    name: 'Manage Roles',
    moduleKey: 'role',
    actionKey: 'manage',
    description: 'Create, edit, and delete tenant roles and their permissions.',
  },
  {
    code: 'module.manage',
    name: 'Manage Modules',
    moduleKey: 'module',
    actionKey: 'manage',
    description: 'Enable, disable, and reorder tenant modules and menus.',
  },
  {
    code: 'res.dashboard.view',
    name: 'View Restaurant Dashboard',
    moduleKey: 'restaurant_dashboard',
    actionKey: 'view',
    description: 'Access restaurant operational dashboards.',
  },
  {
    code: 'res.orders.view',
    name: 'View Restaurant Orders',
    moduleKey: 'restaurant_orders',
    actionKey: 'view',
    description: 'View restaurant orders and queue state.',
  },
  {
    code: 'res.orders.create',
    name: 'Create Restaurant Orders',
    moduleKey: 'restaurant_orders',
    actionKey: 'create',
    description: 'Create restaurant orders and cashier drafts.',
  },
  {
    code: 'res.orders.update',
    name: 'Update Restaurant Orders',
    moduleKey: 'restaurant_orders',
    actionKey: 'update',
    description: 'Update restaurant orders and service state.',
  },
  {
    code: 'res.orders.cancel',
    name: 'Cancel Restaurant Orders',
    moduleKey: 'restaurant_orders',
    actionKey: 'cancel',
    description: 'Cancel or reverse restaurant orders.',
  },
  {
    code: 'res.cashier.access',
    name: 'Access Restaurant Cashier',
    moduleKey: 'restaurant_cashier',
    actionKey: 'access',
    description: 'Access cashier controls for restaurant operations.',
  },
  {
    code: 'res.kitchen.access',
    name: 'Access Kitchen Board',
    moduleKey: 'restaurant_kitchen',
    actionKey: 'access',
    description: 'Access kitchen preparation and queue views.',
  },
  {
    code: 'res.kitchen.update_order_status',
    name: 'Update Kitchen Order Status',
    moduleKey: 'restaurant_kitchen',
    actionKey: 'update_order_status',
    description: 'Advance kitchen-facing order statuses.',
  },
  {
    code: 'res.floor.manage',
    name: 'Manage Floor',
    moduleKey: 'restaurant_floor',
    actionKey: 'manage',
    description: 'Manage floor operations, seating, and service state.',
  },
  {
    code: 'res.users.view',
    name: 'View Restaurant Users',
    moduleKey: 'restaurant_users',
    actionKey: 'view',
    description: 'View restaurant user access surfaces.',
  },
  {
    code: 'res.users.manage',
    name: 'Manage Restaurant Users',
    moduleKey: 'restaurant_users',
    actionKey: 'manage',
    description: 'Manage restaurant user access within the tenant scope.',
  },
  {
    code: 'res.settings.manage',
    name: 'Manage Restaurant Settings',
    moduleKey: 'restaurant_settings',
    actionKey: 'manage',
    description: 'Manage restaurant-specific settings and configuration.',
  },
  {
    code: 'res.menu.view',
    name: 'View Restaurant Menu',
    moduleKey: 'restaurant_menu',
    actionKey: 'view',
    description:
      'View menus, categories, items, modifiers, combos, and pricing.',
  },
  {
    code: 'res.menu.manage',
    name: 'Manage Restaurant Menu',
    moduleKey: 'restaurant_menu',
    actionKey: 'manage',
    description:
      'Create and edit menus, items, price rules, modifiers, and combos.',
  },
  {
    code: 'res.recipe.view',
    name: 'View Recipes',
    moduleKey: 'restaurant_recipe',
    actionKey: 'view',
    description:
      'View recipes, versions, ingredient lines, and computed costs.',
  },
  {
    code: 'res.recipe.manage',
    name: 'Manage Recipes',
    moduleKey: 'restaurant_recipe',
    actionKey: 'manage',
    description:
      'Create recipes, edit versions and lines, compute cost, and approve.',
  },
  {
    code: 'res.reports.view',
    name: 'View Restaurant Reports',
    moduleKey: 'restaurant_reports',
    actionKey: 'view',
    description: 'View restaurant sales, item, and operational reports.',
  },
  {
    code: 'res.reservations.view',
    name: 'View Reservations',
    moduleKey: 'restaurant_reservations',
    actionKey: 'view',
    description: 'View reservations and the walk-in waitlist.',
  },
  {
    code: 'res.reservations.manage',
    name: 'Manage Reservations',
    moduleKey: 'restaurant_reservations',
    actionKey: 'manage',
    description: 'Book, confirm, seat, and cancel reservations and waitlist entries.',
  },
  {
    code: 'res.takeaway.view',
    name: 'View Takeaway',
    moduleKey: 'restaurant_takeaway',
    actionKey: 'view',
    description: 'View the takeaway pickup queue.',
  },
  {
    code: 'res.takeaway.manage',
    name: 'Manage Takeaway',
    moduleKey: 'restaurant_takeaway',
    actionKey: 'manage',
    description: 'Create pickup tickets, notify guests, and verify hand-overs.',
  },
  {
    code: 'res.delivery.view',
    name: 'View Delivery',
    moduleKey: 'restaurant_delivery',
    actionKey: 'view',
    description: 'View the delivery dispatch board, drivers, and zones.',
  },
  {
    code: 'res.delivery.manage',
    name: 'Manage Delivery',
    moduleKey: 'restaurant_delivery',
    actionKey: 'manage',
    description: 'Assign drivers, advance deliveries, and manage zones and the roster.',
  },
  {
    code: 'res.qr.manage',
    name: 'Manage QR Codes',
    moduleKey: 'restaurant_qr',
    actionKey: 'manage',
    description: 'Create and manage QR ordering codes and campaigns.',
  },
  {
    code: 'res.events.view',
    name: 'View Events',
    moduleKey: 'restaurant_events',
    actionKey: 'view',
    description: 'View event and party bookings.',
  },
  {
    code: 'res.events.manage',
    name: 'Manage Events',
    moduleKey: 'restaurant_events',
    actionKey: 'manage',
    description: 'Book events, manage tasks, payments, and party layouts.',
  },
  {
    code: 'res.catering.view',
    name: 'View Catering',
    moduleKey: 'restaurant_catering',
    actionKey: 'view',
    description: 'View catering jobs and their pipeline.',
  },
  {
    code: 'res.catering.manage',
    name: 'Manage Catering',
    moduleKey: 'restaurant_catering',
    actionKey: 'manage',
    description: 'Create catering jobs and advance their lifecycle.',
  },
  {
    code: 'res.promotions.view',
    name: 'View Promotions',
    moduleKey: 'restaurant_promotions',
    actionKey: 'view',
    description: 'View promotions and apply them to orders at the register.',
  },
  {
    code: 'res.promotions.manage',
    name: 'Manage Promotions',
    moduleKey: 'restaurant_promotions',
    actionKey: 'manage',
    description: 'Create, activate, pause, and analyze promotions and coupons.',
  },
  {
    code: 'res.giftcards.view',
    name: 'View Gift Cards',
    moduleKey: 'restaurant_giftcards',
    actionKey: 'view',
    description: 'View gift cards, balances, and transaction ledgers.',
  },
  {
    code: 'res.giftcards.manage',
    name: 'Manage Gift Cards',
    moduleKey: 'restaurant_giftcards',
    actionKey: 'manage',
    description: 'Issue, reload, freeze, and redeem gift cards.',
  },
  {
    code: 'res.analytics.view',
    name: 'View Restaurant Analytics',
    moduleKey: 'restaurant_analytics',
    actionKey: 'view',
    description: 'View restaurant trends, heat maps, and performance analytics.',
  },
  {
    code: 'product.view',
    name: 'View Products',
    moduleKey: 'product',
    actionKey: 'view',
    description: 'View the product catalog, variants, and pricing.',
  },
  {
    code: 'product.create',
    name: 'Create Products',
    moduleKey: 'product',
    actionKey: 'create',
    description: 'Create catalog products and variants.',
  },
  {
    code: 'product.update',
    name: 'Update Products',
    moduleKey: 'product',
    actionKey: 'update',
    description: 'Update catalog products, variants, and attributes.',
  },
  {
    code: 'product.delete',
    name: 'Delete Products',
    moduleKey: 'product',
    actionKey: 'delete',
    description: 'Archive or delete catalog products.',
  },
  {
    code: 'product.manage_pricing',
    name: 'Manage Product Pricing',
    moduleKey: 'product',
    actionKey: 'manage_pricing',
    description: 'Manage price lists and product prices.',
  },
  {
    code: 'product.manage_categories',
    name: 'Manage Product Categories',
    moduleKey: 'product',
    actionKey: 'manage_categories',
    description: 'Manage categories, brands, units, and attributes.',
  },
  {
    code: 'supplier.view',
    name: 'View Suppliers',
    moduleKey: 'supplier',
    actionKey: 'view',
    description: 'View supplier master data.',
  },
  {
    code: 'supplier.manage',
    name: 'Manage Suppliers',
    moduleKey: 'supplier',
    actionKey: 'manage',
    description: 'Create and update supplier master data.',
  },
  {
    code: 'customer.view',
    name: 'View Customers',
    moduleKey: 'customer',
    actionKey: 'view',
    description: 'View customer master data.',
  },
  {
    code: 'customer.manage',
    name: 'Manage Customers',
    moduleKey: 'customer',
    actionKey: 'manage',
    description: 'Create and update customer master data.',
  },
  {
    code: 'tax.manage',
    name: 'Manage Tax Rates',
    moduleKey: 'tax',
    actionKey: 'manage',
    description: 'Create and update tax rates.',
  },
  {
    code: 'warehouse.view',
    name: 'View Warehouses',
    moduleKey: 'warehouse',
    actionKey: 'view',
    description: 'View warehouses and storage locations.',
  },
  {
    code: 'warehouse.create',
    name: 'Create Warehouses',
    moduleKey: 'warehouse',
    actionKey: 'create',
    description: 'Create warehouses.',
  },
  {
    code: 'warehouse.update',
    name: 'Update Warehouses',
    moduleKey: 'warehouse',
    actionKey: 'update',
    description: 'Update warehouse details.',
  },
  {
    code: 'warehouse.manage_locations',
    name: 'Manage Warehouse Locations',
    moduleKey: 'warehouse',
    actionKey: 'manage_locations',
    description: 'Create and manage warehouse location hierarchy.',
  },
  {
    code: 'inventory.view_stock',
    name: 'View Stock',
    moduleKey: 'inventory',
    actionKey: 'view_stock',
    description: 'View current stock balances.',
  },
  {
    code: 'inventory.view_movements',
    name: 'View Movements',
    moduleKey: 'inventory',
    actionKey: 'view_movements',
    description: 'View the inventory movement ledger.',
  },
  {
    code: 'inventory.reserve',
    name: 'Reserve Stock',
    moduleKey: 'inventory',
    actionKey: 'reserve',
    description: 'Place, release, and expire soft stock reservations.',
  },
  {
    code: 'inventory.manage_lots',
    name: 'Manage Lots',
    moduleKey: 'inventory',
    actionKey: 'manage_lots',
    description: 'Quarantine, recall, and expire batch lots.',
  },
  {
    code: 'inventory.manage_serials',
    name: 'Manage Serials',
    moduleKey: 'inventory',
    actionKey: 'manage_serials',
    description: 'Manage serial-number lifecycle (repair, scrap, quarantine).',
  },
  {
    code: 'inventory.manage_reorder',
    name: 'Manage Reorder Rules',
    moduleKey: 'inventory',
    actionKey: 'manage_reorder',
    description: 'Maintain reorder rules and take valuation snapshots.',
  },
  {
    code: 'inventory.view_valuation',
    name: 'View Valuation',
    moduleKey: 'inventory',
    actionKey: 'view_valuation',
    description: 'View stock valuation summaries and period snapshots.',
  },
  {
    code: 'adjustment.view',
    name: 'View Adjustments',
    moduleKey: 'adjustment',
    actionKey: 'view',
    description: 'View stock adjustments.',
  },
  {
    code: 'adjustment.create',
    name: 'Create Adjustments',
    moduleKey: 'adjustment',
    actionKey: 'create',
    description: 'Create stock adjustment documents.',
  },
  {
    code: 'adjustment.post',
    name: 'Post Adjustments',
    moduleKey: 'adjustment',
    actionKey: 'post',
    description: 'Post stock adjustments to the inventory ledger.',
  },
  {
    code: 'transfer.view',
    name: 'View Transfers',
    moduleKey: 'transfer',
    actionKey: 'view',
    description: 'View stock transfers.',
  },
  {
    code: 'transfer.create',
    name: 'Create Transfers',
    moduleKey: 'transfer',
    actionKey: 'create',
    description: 'Create stock transfer documents.',
  },
  {
    code: 'transfer.ship',
    name: 'Ship Transfers',
    moduleKey: 'transfer',
    actionKey: 'ship',
    description: 'Ship transfers (post TRANSFER_OUT).',
  },
  {
    code: 'transfer.receive',
    name: 'Receive Transfers',
    moduleKey: 'transfer',
    actionKey: 'receive',
    description: 'Receive transfers (post TRANSFER_IN).',
  },
  {
    code: 'purchase.requisition_view',
    name: 'View Requisitions',
    moduleKey: 'purchase',
    actionKey: 'requisition_view',
    description: 'View purchase requisitions.',
  },
  {
    code: 'purchase.requisition_manage',
    name: 'Manage Requisitions',
    moduleKey: 'purchase',
    actionKey: 'requisition_manage',
    description: 'Create, submit, approve, and convert requisitions.',
  },
  {
    code: 'purchase.po_view',
    name: 'View Purchase Orders',
    moduleKey: 'purchase',
    actionKey: 'po_view',
    description: 'View purchase orders, receipts, and returns.',
  },
  {
    code: 'purchase.po_create',
    name: 'Create Purchase Orders',
    moduleKey: 'purchase',
    actionKey: 'po_create',
    description: 'Create purchase orders.',
  },
  {
    code: 'purchase.po_approve',
    name: 'Approve Purchase Orders',
    moduleKey: 'purchase',
    actionKey: 'po_approve',
    description: 'Approve, confirm, and cancel purchase orders.',
  },
  {
    code: 'purchase.po_receive',
    name: 'Receive Goods',
    moduleKey: 'purchase',
    actionKey: 'po_receive',
    description: 'Create and post goods receipts.',
  },
  {
    code: 'purchase.return_manage',
    name: 'Manage Purchase Returns',
    moduleKey: 'purchase',
    actionKey: 'return_manage',
    description: 'Create and post purchase returns.',
  },
  {
    code: 'purchase.rfq_view',
    name: 'View RFQs',
    moduleKey: 'purchase',
    actionKey: 'rfq_view',
    description: 'View requests for quotation and supplier responses.',
  },
  {
    code: 'purchase.rfq_manage',
    name: 'Manage RFQs',
    moduleKey: 'purchase',
    actionKey: 'rfq_manage',
    description: 'Create, revise, issue, and cancel requests for quotation.',
  },
  {
    code: 'purchase.quotation_view',
    name: 'View Quotations',
    moduleKey: 'purchase',
    actionKey: 'quotation_view',
    description: 'View supplier quotations and the comparison matrix.',
  },
  {
    code: 'purchase.quotation_manage',
    name: 'Manage Quotations',
    moduleKey: 'purchase',
    actionKey: 'quotation_manage',
    description: 'Record, revise, and approve supplier quotations.',
  },
  {
    code: 'purchase.quotation_award',
    name: 'Award Quotations',
    moduleKey: 'purchase',
    actionKey: 'quotation_award',
    description: 'Award a quotation and convert it to a purchase order.',
  },
  {
    code: 'purchase.invoice_view',
    name: 'View Supplier Invoices',
    moduleKey: 'purchase',
    actionKey: 'invoice_view',
    description: 'View supplier invoices and payables.',
  },
  {
    code: 'purchase.invoice_manage',
    name: 'Manage Supplier Invoices',
    moduleKey: 'purchase',
    actionKey: 'invoice_manage',
    description: 'Create, approve, and post supplier invoices.',
  },
  {
    code: 'purchase.invoice_match',
    name: 'Match Supplier Invoices',
    moduleKey: 'purchase',
    actionKey: 'invoice_match',
    description: 'Perform PO/GRN/invoice three-way matching.',
  },
  {
    code: 'purchase.payment_view',
    name: 'View Supplier Payments',
    moduleKey: 'purchase',
    actionKey: 'payment_view',
    description: 'View supplier payments and allocations.',
  },
  {
    code: 'purchase.payment_manage',
    name: 'Manage Supplier Payments',
    moduleKey: 'purchase',
    actionKey: 'payment_manage',
    description: 'Record, allocate, and post supplier payments.',
  },
  {
    code: 'purchase.landed_cost_manage',
    name: 'Manage Landed Cost',
    moduleKey: 'purchase',
    actionKey: 'landed_cost_manage',
    description: 'Create landed-cost vouchers and allocate to inventory.',
  },
  {
    code: 'purchase.debit_note_manage',
    name: 'Manage Debit Notes',
    moduleKey: 'purchase',
    actionKey: 'debit_note_manage',
    description: 'Create and issue supplier debit notes.',
  },
  {
    code: 'purchase.approval_action',
    name: 'Act on Purchase Approvals',
    moduleKey: 'purchase',
    actionKey: 'approval_action',
    description: 'Approve, reject, delegate, or escalate purchase approvals.',
  },
  {
    code: 'purchase.config_manage',
    name: 'Manage Purchase Settings',
    moduleKey: 'purchase',
    actionKey: 'config_manage',
    description:
      'Manage supplier categories, approval workflows, and purchase lookups.',
  },
  {
    code: 'sales.order_view',
    name: 'View Sales Orders',
    moduleKey: 'sales',
    actionKey: 'order_view',
    description: 'View sales orders and invoices.',
  },
  {
    code: 'sales.order_create',
    name: 'Create Sales Orders',
    moduleKey: 'sales',
    actionKey: 'order_create',
    description: 'Create sales orders.',
  },
  {
    code: 'sales.order_confirm',
    name: 'Confirm Sales Orders',
    moduleKey: 'sales',
    actionKey: 'order_confirm',
    description: 'Confirm and cancel sales orders.',
  },
  {
    code: 'sales.order_fulfill',
    name: 'Fulfil Sales Orders',
    moduleKey: 'sales',
    actionKey: 'order_fulfill',
    description: 'Fulfil sales orders (post SALE movements).',
  },
  {
    code: 'sales.invoice_manage',
    name: 'Manage Sales Invoices',
    moduleKey: 'sales',
    actionKey: 'invoice_manage',
    description: 'Create, issue, and record payments on sales invoices.',
  },
  {
    code: 'pos.access',
    name: 'Access POS',
    moduleKey: 'pos',
    actionKey: 'access',
    description: 'Access the point-of-sale surface and its sales/sessions.',
  },
  {
    code: 'pos.sell',
    name: 'Sell at POS',
    moduleKey: 'pos',
    actionKey: 'sell',
    description: 'Create and complete POS sales (post SALE movements).',
  },
  {
    code: 'pos.void',
    name: 'Void POS Sales',
    moduleKey: 'pos',
    actionKey: 'void',
    description: 'Void POS sales.',
  },
  {
    code: 'pos.session_manage',
    name: 'Manage POS Sessions',
    moduleKey: 'pos',
    actionKey: 'session_manage',
    description: 'Open and close cash-drawer sessions.',
  },
  {
    code: 'returns.view',
    name: 'View Returns',
    moduleKey: 'returns',
    actionKey: 'view',
    description: 'View sales returns and credit/debit notes.',
  },
  {
    code: 'returns.create',
    name: 'Create Returns',
    moduleKey: 'returns',
    actionKey: 'create',
    description: 'Create, submit, and cancel sales returns.',
  },
  {
    code: 'returns.approve',
    name: 'Approve Returns',
    moduleKey: 'returns',
    actionKey: 'approve',
    description: 'Approve or reject requested sales returns.',
  },
  {
    code: 'returns.receive',
    name: 'Receive Returns',
    moduleKey: 'returns',
    actionKey: 'receive',
    description: 'Receive sales returns (post SALES_RETURN movements).',
  },
  {
    code: 'returns.refund',
    name: 'Refund POS Sales',
    moduleKey: 'returns',
    actionKey: 'refund',
    description: 'Refund completed POS sales and re-enter stock.',
  },
  {
    code: 'note.manage',
    name: 'Manage Credit/Debit Notes',
    moduleKey: 'returns',
    actionKey: 'note_manage',
    description: 'Create, issue, apply, and cancel credit and debit notes.',
  },
  {
    code: 'production.view',
    name: 'View Production',
    moduleKey: 'production',
    actionKey: 'view',
    description: 'View bills of materials and production orders.',
  },
  {
    code: 'production.manage_bom',
    name: 'Manage BOMs',
    moduleKey: 'production',
    actionKey: 'manage_bom',
    description: 'Create and maintain bills of materials.',
  },
  {
    code: 'production.create',
    name: 'Create Production Orders',
    moduleKey: 'production',
    actionKey: 'create',
    description: 'Create and cancel production orders.',
  },
  {
    code: 'production.release',
    name: 'Release Production Orders',
    moduleKey: 'production',
    actionKey: 'release',
    description: 'Plan and release production orders for execution.',
  },
  {
    code: 'production.consume',
    name: 'Consume Materials',
    moduleKey: 'production',
    actionKey: 'consume',
    description: 'Issue materials to production (post PRODUCTION_CONSUMPTION).',
  },
  {
    code: 'production.complete',
    name: 'Complete Production',
    moduleKey: 'production',
    actionKey: 'complete',
    description:
      'Receive finished goods from production (post PRODUCTION_OUTPUT).',
  },
  {
    code: 'crm.view',
    name: 'View CRM',
    moduleKey: 'crm',
    actionKey: 'view',
    description:
      'Access CRM customer intelligence surfaces and the customer 360 view.',
  },
  {
    code: 'crm.profile_manage',
    name: 'Manage Customer Profiles',
    moduleKey: 'crm',
    actionKey: 'profile_manage',
    description:
      'Maintain customer profiles, contacts, addresses, preferences, tags, and consent.',
  },
  {
    code: 'crm.timeline_view',
    name: 'View Customer Timeline',
    moduleKey: 'crm',
    actionKey: 'timeline_view',
    description: 'View the chronological customer activity timeline.',
  },
  {
    code: 'crm.timeline_note',
    name: 'Add Timeline Notes',
    moduleKey: 'crm',
    actionKey: 'timeline_note',
    description: 'Add manual notes to a customer timeline.',
  },
  {
    code: 'crm.loyalty_view',
    name: 'View Loyalty',
    moduleKey: 'crm',
    actionKey: 'loyalty_view',
    description: 'View loyalty accounts, balances, and the points ledger.',
  },
  {
    code: 'crm.loyalty_manage',
    name: 'Manage Loyalty Program',
    moduleKey: 'crm',
    actionKey: 'loyalty_manage',
    description: 'Configure loyalty settings, tiers, and earning rules.',
  },
  {
    code: 'crm.loyalty_redeem',
    name: 'Redeem Loyalty Points',
    moduleKey: 'crm',
    actionKey: 'loyalty_redeem',
    description: 'Redeem customer loyalty points against a sale.',
  },
  {
    code: 'crm.loyalty_adjust',
    name: 'Adjust Loyalty Points',
    moduleKey: 'crm',
    actionKey: 'loyalty_adjust',
    description: 'Apply manual loyalty point adjustments and expirations.',
  },
  {
    code: 'crm.segment_view',
    name: 'View Segments',
    moduleKey: 'crm',
    actionKey: 'segment_view',
    description: 'View customer segments and their membership.',
  },
  {
    code: 'crm.segment_manage',
    name: 'Manage Segments',
    moduleKey: 'crm',
    actionKey: 'segment_manage',
    description: 'Create, edit, rebuild, and delete customer segments.',
  },
  {
    code: 'crm.analytics_view',
    name: 'View CRM Analytics',
    moduleKey: 'crm',
    actionKey: 'analytics_view',
    description: 'View customer analytics dashboards and metrics.',
  },
  {
    code: 'crm.settings_manage',
    name: 'Manage CRM Settings',
    moduleKey: 'crm',
    actionKey: 'settings_manage',
    description:
      'Manage CRM configuration: custom fields, groups, and projector operations.',
  },
  {
    code: 'finance.account_view',
    name: 'View Chart of Accounts',
    moduleKey: 'finance',
    actionKey: 'account_view',
    description: 'View the chart of accounts, account types, and mappings.',
  },
  {
    code: 'finance.account_manage',
    name: 'Manage Chart of Accounts',
    moduleKey: 'finance',
    actionKey: 'account_manage',
    description: 'Create, update, and deactivate GL accounts.',
  },
  {
    code: 'finance.fiscal_manage',
    name: 'Manage Fiscal Calendar',
    moduleKey: 'finance',
    actionKey: 'fiscal_manage',
    description: 'Create fiscal years and open, close, or lock periods.',
  },
  {
    code: 'finance.journal_view',
    name: 'View Journals',
    moduleKey: 'finance',
    actionKey: 'journal_view',
    description: 'View journal entries, journal types, and the trial balance.',
  },
  {
    code: 'finance.journal_create',
    name: 'Create Journal Entries',
    moduleKey: 'finance',
    actionKey: 'journal_create',
    description: 'Create and edit draft manual journal entries.',
  },
  {
    code: 'finance.journal_post',
    name: 'Post Journal Entries',
    moduleKey: 'finance',
    actionKey: 'journal_post',
    description: 'Post draft journal entries to the general ledger.',
  },
  {
    code: 'finance.journal_reverse',
    name: 'Reverse Journal Entries',
    moduleKey: 'finance',
    actionKey: 'journal_reverse',
    description: 'Reverse posted journal entries (reversal-only corrections).',
  },
  {
    code: 'finance.settings_manage',
    name: 'Manage Financial Settings',
    moduleKey: 'finance',
    actionKey: 'settings_manage',
    description:
      'Bootstrap tenant finance and manage default accounts, currencies, and exchange rates.',
  },
  {
    code: 'finance.posting_manage',
    name: 'Manage Posting Rules',
    moduleKey: 'finance',
    actionKey: 'posting_manage',
    description:
      'Configure posting rules and operational-entity account mappings.',
  },
] as const

export type RoleCode = (typeof ROLE_DEFINITIONS)[number]['code']
export type PermissionCode = (typeof PERMISSION_DEFINITIONS)[number]['code']
export const PERMISSION_CODES = PERMISSION_DEFINITIONS.map(
  (definition) => definition.code,
) as [PermissionCode, ...PermissionCode[]]

const ROLE_DEFINITION_BY_CODE: Record<
  string,
  (typeof ROLE_DEFINITIONS)[number]
> = Object.fromEntries(
  ROLE_DEFINITIONS.map((definition) => [definition.code, definition]),
) as Record<string, (typeof ROLE_DEFINITIONS)[number]>

export const ROLE_RANKS: Record<string, number> = Object.fromEntries(
  ROLE_DEFINITIONS.map((definition) => [definition.code, definition.rank]),
) as Record<string, number>

export const TENANT_ASSIGNABLE_ROLE_CODES: Array<RoleCode> =
  ROLE_DEFINITIONS.map((definition) => definition.code)

export const ROLE_PERMISSION_MAP: Record<RoleCode, Array<PermissionCode>> = {
  super_admin: PERMISSION_DEFINITIONS.map((permission) => permission.code),
  admin: [
    'tenant.view',
    'tenant.update',
    'user.view',
    'user.invite',
    'user.update',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'role.view',
    'role.manage',
    'module.manage',
    'product.view',
    'product.create',
    'product.update',
    'product.delete',
    'product.manage_pricing',
    'product.manage_categories',
    'supplier.view',
    'supplier.manage',
    'customer.view',
    'customer.manage',
    'tax.manage',
    'warehouse.view',
    'warehouse.create',
    'warehouse.update',
    'warehouse.manage_locations',
    'inventory.view_stock',
    'inventory.view_movements',
    'inventory.reserve',
    'inventory.manage_lots',
    'inventory.manage_serials',
    'inventory.manage_reorder',
    'inventory.view_valuation',
    'adjustment.view',
    'adjustment.create',
    'adjustment.post',
    'transfer.view',
    'transfer.create',
    'transfer.ship',
    'transfer.receive',
    'purchase.requisition_view',
    'purchase.requisition_manage',
    'purchase.po_view',
    'purchase.po_create',
    'purchase.po_approve',
    'purchase.po_receive',
    'purchase.return_manage',
    'purchase.rfq_view',
    'purchase.rfq_manage',
    'purchase.quotation_view',
    'purchase.quotation_manage',
    'purchase.quotation_award',
    'purchase.invoice_view',
    'purchase.invoice_manage',
    'purchase.invoice_match',
    'purchase.payment_view',
    'purchase.payment_manage',
    'purchase.landed_cost_manage',
    'purchase.debit_note_manage',
    'purchase.approval_action',
    'purchase.config_manage',
    'sales.order_view',
    'sales.order_create',
    'sales.order_confirm',
    'sales.order_fulfill',
    'sales.invoice_manage',
    'pos.access',
    'pos.sell',
    'pos.void',
    'pos.session_manage',
    'returns.view',
    'returns.create',
    'returns.approve',
    'returns.receive',
    'returns.refund',
    'note.manage',
    'production.view',
    'production.manage_bom',
    'production.create',
    'production.release',
    'production.consume',
    'production.complete',
    'crm.view',
    'crm.profile_manage',
    'crm.timeline_view',
    'crm.timeline_note',
    'crm.loyalty_view',
    'crm.loyalty_manage',
    'crm.loyalty_redeem',
    'crm.loyalty_adjust',
    'crm.segment_view',
    'crm.segment_manage',
    'crm.analytics_view',
    'crm.settings_manage',
    'finance.account_view',
    'finance.account_manage',
    'finance.fiscal_manage',
    'finance.journal_view',
    'finance.journal_create',
    'finance.journal_post',
    'finance.journal_reverse',
    'finance.settings_manage',
    'finance.posting_manage',
  ],
  finance_manager: [
    'tenant.view',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'supplier.view',
    'customer.view',
    'purchase.invoice_view',
    'purchase.payment_view',
    'inventory.view_valuation',
    'finance.account_view',
    'finance.account_manage',
    'finance.fiscal_manage',
    'finance.journal_view',
    'finance.journal_create',
    'finance.journal_post',
    'finance.journal_reverse',
    'finance.settings_manage',
    'finance.posting_manage',
  ],
  'res:super_admin': [
    'tenant.view',
    'tenant.manage_settings',
    'user.view',
    'user.invite',
    'user.update',
    'user.deactivate',
    'user.change_role',
    'user.assign_permission',
    'profile.view_self',
    'profile.update_self',
    'res.dashboard.view',
    'res.orders.view',
    'res.orders.create',
    'res.orders.update',
    'res.orders.cancel',
    'res.cashier.access',
    'res.kitchen.access',
    'res.kitchen.update_order_status',
    'res.floor.manage',
    'res.users.view',
    'res.users.manage',
    'res.settings.manage',
    'res.menu.view',
    'res.menu.manage',
    'res.recipe.view',
    'res.recipe.manage',
    'res.reports.view',
    'res.analytics.view',
    'res.reservations.view',
    'res.reservations.manage',
    'res.takeaway.view',
    'res.takeaway.manage',
    'res.delivery.view',
    'res.delivery.manage',
    'res.qr.manage',
    'res.promotions.view',
    'res.promotions.manage',
    'res.giftcards.view',
    'res.giftcards.manage',
    'res.events.view',
    'res.events.manage',
    'res.catering.view',
    'res.catering.manage',
    'role.view',
    'role.manage',
    'module.manage',
  ],
  'res:admin': [
    'user.view',
    'profile.view_self',
    'profile.update_self',
    'res.dashboard.view',
    'res.orders.view',
    'res.orders.create',
    'res.orders.update',
    'res.users.view',
    'res.menu.view',
    'res.menu.manage',
    'res.recipe.view',
    'res.recipe.manage',
    'res.reports.view',
    'res.analytics.view',
    'res.reservations.view',
    'res.reservations.manage',
    'res.takeaway.view',
    'res.takeaway.manage',
    'res.delivery.view',
    'res.delivery.manage',
    'res.qr.manage',
    'res.promotions.view',
    'res.promotions.manage',
    'res.giftcards.view',
    'res.giftcards.manage',
    'res.events.view',
    'res.events.manage',
    'res.catering.view',
    'res.catering.manage',
  ],
  'res:floor_manager': [
    'profile.view_self',
    'profile.update_self',
    'res.dashboard.view',
    'res.orders.view',
    'res.orders.update',
    'res.floor.manage',
    'res.menu.view',
    'res.reports.view',
    'res.analytics.view',
    'res.reservations.view',
    'res.reservations.manage',
    'res.takeaway.view',
    'res.takeaway.manage',
    'res.delivery.view',
    'res.delivery.manage',
    'res.qr.manage',
    'res.events.view',
    'res.events.manage',
    'res.catering.view',
    'res.catering.manage',
  ],
  cashier: ['dashboard.view', 'profile.view_self', 'profile.update_self'],
  'res:cashier': [
    'profile.view_self',
    'profile.update_self',
    'res.dashboard.view',
    'res.cashier.access',
    'res.orders.view',
    'res.orders.create',
    'res.menu.view',
    'res.reservations.view',
    'res.takeaway.view',
    'res.takeaway.manage',
    'res.delivery.view',
    'res.promotions.view',
    'res.giftcards.view',
    'res.giftcards.manage',
  ],
  'res:kitchen': [
    'profile.view_self',
    'profile.update_self',
    'res.dashboard.view',
    'res.kitchen.access',
    'res.kitchen.update_order_status',
    'res.orders.view',
    'res.menu.view',
  ],
  'res:user': [
    'profile.view_self',
    'profile.update_self',
    'res.dashboard.view',
  ],
  inventory_manager: [
    'tenant.view',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'product.view',
    'product.create',
    'product.update',
    'product.delete',
    'product.manage_pricing',
    'product.manage_categories',
    'supplier.view',
    'supplier.manage',
    'customer.view',
    'customer.manage',
    'tax.manage',
    'warehouse.view',
    'warehouse.create',
    'warehouse.update',
    'warehouse.manage_locations',
    'inventory.view_stock',
    'inventory.view_movements',
    'inventory.reserve',
    'inventory.manage_lots',
    'inventory.manage_serials',
    'inventory.manage_reorder',
    'inventory.view_valuation',
    'adjustment.view',
    'adjustment.create',
    'adjustment.post',
    'transfer.view',
    'transfer.create',
    'transfer.ship',
    'transfer.receive',
    'purchase.requisition_view',
    'purchase.po_view',
  ],
  warehouse_manager: [
    'tenant.view',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'product.view',
    'warehouse.view',
    'warehouse.create',
    'warehouse.update',
    'warehouse.manage_locations',
    'inventory.view_stock',
    'inventory.view_movements',
    'inventory.reserve',
    'inventory.manage_lots',
    'inventory.manage_serials',
    'inventory.manage_reorder',
    'inventory.view_valuation',
    'adjustment.view',
    'adjustment.create',
    'adjustment.post',
    'transfer.view',
    'transfer.create',
    'transfer.ship',
    'transfer.receive',
    'purchase.po_view',
    'purchase.po_receive',
  ],
  purchasing_officer: [
    'tenant.view',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'product.view',
    'supplier.view',
    'supplier.manage',
    'warehouse.view',
    'inventory.view_stock',
    'transfer.view',
    'purchase.requisition_view',
    'purchase.requisition_manage',
    'purchase.po_view',
    'purchase.po_create',
    'purchase.po_approve',
    'purchase.po_receive',
    'purchase.return_manage',
    'purchase.rfq_view',
    'purchase.rfq_manage',
    'purchase.quotation_view',
    'purchase.quotation_manage',
    'purchase.quotation_award',
    'purchase.invoice_view',
    'purchase.invoice_manage',
    'purchase.invoice_match',
    'purchase.payment_view',
    'purchase.payment_manage',
    'purchase.landed_cost_manage',
    'purchase.debit_note_manage',
    'purchase.approval_action',
    'purchase.config_manage',
    'note.manage',
  ],
  sales_manager: [
    'tenant.view',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'product.view',
    'customer.view',
    'customer.manage',
    'inventory.view_stock',
    'inventory.reserve',
    'sales.order_view',
    'sales.order_create',
    'sales.order_confirm',
    'sales.order_fulfill',
    'sales.invoice_manage',
    'pos.access',
    'returns.view',
    'returns.create',
    'returns.approve',
    'returns.receive',
    'returns.refund',
    'note.manage',
    'crm.view',
    'crm.timeline_view',
    'crm.timeline_note',
    'crm.loyalty_view',
    'crm.loyalty_adjust',
    'crm.segment_view',
    'crm.analytics_view',
  ],
  pos_cashier: [
    'profile.view_self',
    'profile.update_self',
    'product.view',
    'customer.view',
    'inventory.view_stock',
    'pos.access',
    'pos.sell',
    'pos.session_manage',
    'returns.view',
    'returns.refund',
    'crm.loyalty_view',
    'crm.loyalty_redeem',
  ],
  production_manager: [
    'tenant.view',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'product.view',
    'warehouse.view',
    'inventory.view_stock',
    'inventory.view_movements',
    'inventory.manage_lots',
    'inventory.manage_serials',
    'production.view',
    'production.manage_bom',
    'production.create',
    'production.release',
    'production.consume',
    'production.complete',
  ],
  crm_manager: [
    'tenant.view',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'customer.view',
    'customer.manage',
    'crm.view',
    'crm.profile_manage',
    'crm.timeline_view',
    'crm.timeline_note',
    'crm.loyalty_view',
    'crm.loyalty_manage',
    'crm.loyalty_redeem',
    'crm.loyalty_adjust',
    'crm.segment_view',
    'crm.segment_manage',
    'crm.analytics_view',
    'crm.settings_manage',
  ],
}

export function getRoleDefinition(roleCode: string) {
  const normalizedRoleCode = normalizeRoleCode(roleCode)

  return ROLE_DEFINITION_BY_CODE[normalizedRoleCode] ?? null
}

export function isTenantAssignableRole(roleCode: string): roleCode is RoleCode {
  return TENANT_ASSIGNABLE_ROLE_CODES.includes(
    normalizeRoleCode(roleCode) as RoleCode,
  )
}

export function isPermissionCode(
  permissionCode: string,
): permissionCode is PermissionCode {
  return PERMISSION_CODES.includes(permissionCode as PermissionCode)
}

export function getRoleRank(roleCode: string) {
  const normalizedRoleCode = normalizeRoleCode(roleCode)

  return ROLE_RANKS[normalizedRoleCode] ?? 0
}
