export const ROLE_CODE_ALIASES: Readonly<Partial<Record<string, string>>> = {
  'res:cachier': 'res:cashier',
} as const

export function normalizeRoleCode(roleCode: string) {
  const normalizedRoleCode = roleCode.trim().toLowerCase()

  return ROLE_CODE_ALIASES[normalizedRoleCode] ?? normalizedRoleCode
}

export const ROLE_DEFINITIONS = [
  {
    code: 'super_admin',
    name: 'Super Admin',
    description: 'Tenant owner-grade access across all tenant and restaurant controls.',
    isSystem: true,
    rank: 100,
  },
  {
    code: 'res:super_admin',
    name: 'Restaurant Super Admin',
    description: 'Restaurant operational super admin with staff and settings control.',
    isSystem: true,
    rank: 90,
  },
  {
    code: 'admin',
    name: 'Admin',
    description: 'Tenant administrator with user and dashboard access.',
    isSystem: true,
    rank: 80,
  },
  {
    code: 'res:admin',
    name: 'Restaurant Admin',
    description: 'Restaurant administrator with order oversight and limited staff visibility.',
    isSystem: true,
    rank: 70,
  },
  {
    code: 'res:floor_manager',
    name: 'Floor Manager',
    description: 'Front-of-house manager focused on live order coordination.',
    isSystem: true,
    rank: 60,
  },
  {
    code: 'cashier',
    name: 'Cashier',
    description: 'Generic cashier access for dashboard and self-service profile actions.',
    isSystem: true,
    rank: 50,
  },
  {
    code: 'res:cashier',
    name: 'Restaurant Cashier',
    description: 'Restaurant cashier with order entry and cashier interface access.',
    isSystem: true,
    rank: 45,
  },
  {
    code: 'res:kitchen',
    name: 'Kitchen',
    description: 'Kitchen role for fulfillment and order status progression.',
    isSystem: true,
    rank: 40,
  },
  {
    code: 'res:user',
    name: 'Restaurant User',
    description: 'Basic restaurant access with self-profile permissions.',
    isSystem: true,
    rank: 30,
  },
  {
    code: 'inventory_manager',
    name: 'Inventory Manager',
    description: 'Manages the product catalog, master data, and inventory operations.',
    isSystem: true,
    rank: 65,
  },
  {
    code: 'warehouse_manager',
    name: 'Warehouse Manager',
    description: 'Manages warehouses, locations, stock, and adjustments.',
    isSystem: true,
    rank: 62,
  },
  {
    code: 'purchasing_officer',
    name: 'Purchasing Officer',
    description: 'Manages requisitions, purchase orders, goods receipts, and returns.',
    isSystem: true,
    rank: 58,
  },
  {
    code: 'sales_manager',
    name: 'Sales Manager',
    description: 'Manages sales orders, invoices, and customers.',
    isSystem: true,
    rank: 56,
  },
  {
    code: 'pos_cashier',
    name: 'POS Cashier',
    description: 'Operates the point of sale — sells, takes payment, manages the drawer.',
    isSystem: true,
    rank: 48,
  },
] as const

export const PERMISSION_DEFINITIONS = [
  {
    code: 'tenant.view',
    name: 'View Tenant',
    moduleKey: 'tenant',
    actionKey: 'view',
    description: 'View tenant data and scoped settings.',
  },
  {
    code: 'tenant.update',
    name: 'Update Tenant',
    moduleKey: 'tenant',
    actionKey: 'update',
    description: 'Update tenant details and configuration.',
  },
  {
    code: 'tenant.manage_settings',
    name: 'Manage Tenant Settings',
    moduleKey: 'tenant',
    actionKey: 'manage_settings',
    description: 'Manage tenant settings and integrations.',
  },
  {
    code: 'user.view',
    name: 'View Users',
    moduleKey: 'user',
    actionKey: 'view',
    description: 'View tenant users and invitations.',
  },
  {
    code: 'user.invite',
    name: 'Invite Users',
    moduleKey: 'user',
    actionKey: 'invite',
    description: 'Invite, resend, revoke, and manage invitation flow.',
  },
  {
    code: 'user.update',
    name: 'Update Users',
    moduleKey: 'user',
    actionKey: 'update',
    description: 'Update tenant user state and editable account fields.',
  },
  {
    code: 'user.deactivate',
    name: 'Deactivate Users',
    moduleKey: 'user',
    actionKey: 'deactivate',
    description: 'Suspend or disable tenant user access.',
  },
  {
    code: 'user.change_role',
    name: 'Change User Role',
    moduleKey: 'user',
    actionKey: 'change_role',
    description: 'Assign or change tenant user primary roles.',
  },
  {
    code: 'user.assign_permission',
    name: 'Assign User Permission',
    moduleKey: 'user',
    actionKey: 'assign_permission',
    description: 'Assign direct user permission overrides.',
  },
  {
    code: 'profile.view_self',
    name: 'View Own Profile',
    moduleKey: 'profile',
    actionKey: 'view_self',
    description: 'View the authenticated user profile.',
  },
  {
    code: 'profile.update_self',
    name: 'Update Own Profile',
    moduleKey: 'profile',
    actionKey: 'update_self',
    description: 'Update the authenticated user profile.',
  },
  {
    code: 'dashboard.view',
    name: 'View Dashboard',
    moduleKey: 'dashboard',
    actionKey: 'view',
    description: 'Access the tenant dashboard.',
  },
  {
    code: 'role.view',
    name: 'View Roles',
    moduleKey: 'role',
    actionKey: 'view',
    description: 'View tenant roles and their permission mappings.',
  },
  {
    code: 'role.manage',
    name: 'Manage Roles',
    moduleKey: 'role',
    actionKey: 'manage',
    description: 'Create, edit, and delete tenant roles and their permissions.',
  },
  {
    code: 'module.manage',
    name: 'Manage Modules',
    moduleKey: 'module',
    actionKey: 'manage',
    description: 'Enable, disable, and reorder tenant modules and menus.',
  },
  {
    code: 'res.dashboard.view',
    name: 'View Restaurant Dashboard',
    moduleKey: 'restaurant_dashboard',
    actionKey: 'view',
    description: 'Access restaurant operational dashboards.',
  },
  {
    code: 'res.orders.view',
    name: 'View Restaurant Orders',
    moduleKey: 'restaurant_orders',
    actionKey: 'view',
    description: 'View restaurant orders and queue state.',
  },
  {
    code: 'res.orders.create',
    name: 'Create Restaurant Orders',
    moduleKey: 'restaurant_orders',
    actionKey: 'create',
    description: 'Create restaurant orders and cashier drafts.',
  },
  {
    code: 'res.orders.update',
    name: 'Update Restaurant Orders',
    moduleKey: 'restaurant_orders',
    actionKey: 'update',
    description: 'Update restaurant orders and service state.',
  },
  {
    code: 'res.orders.cancel',
    name: 'Cancel Restaurant Orders',
    moduleKey: 'restaurant_orders',
    actionKey: 'cancel',
    description: 'Cancel or reverse restaurant orders.',
  },
  {
    code: 'res.cashier.access',
    name: 'Access Restaurant Cashier',
    moduleKey: 'restaurant_cashier',
    actionKey: 'access',
    description: 'Access cashier controls for restaurant operations.',
  },
  {
    code: 'res.kitchen.access',
    name: 'Access Kitchen Board',
    moduleKey: 'restaurant_kitchen',
    actionKey: 'access',
    description: 'Access kitchen preparation and queue views.',
  },
  {
    code: 'res.kitchen.update_order_status',
    name: 'Update Kitchen Order Status',
    moduleKey: 'restaurant_kitchen',
    actionKey: 'update_order_status',
    description: 'Advance kitchen-facing order statuses.',
  },
  {
    code: 'res.floor.manage',
    name: 'Manage Floor',
    moduleKey: 'restaurant_floor',
    actionKey: 'manage',
    description: 'Manage floor operations, seating, and service state.',
  },
  {
    code: 'res.users.view',
    name: 'View Restaurant Users',
    moduleKey: 'restaurant_users',
    actionKey: 'view',
    description: 'View restaurant user access surfaces.',
  },
  {
    code: 'res.users.manage',
    name: 'Manage Restaurant Users',
    moduleKey: 'restaurant_users',
    actionKey: 'manage',
    description: 'Manage restaurant user access within the tenant scope.',
  },
  {
    code: 'res.settings.manage',
    name: 'Manage Restaurant Settings',
    moduleKey: 'restaurant_settings',
    actionKey: 'manage',
    description: 'Manage restaurant-specific settings and configuration.',
  },
  {
    code: 'product.view',
    name: 'View Products',
    moduleKey: 'product',
    actionKey: 'view',
    description: 'View the product catalog, variants, and pricing.',
  },
  {
    code: 'product.create',
    name: 'Create Products',
    moduleKey: 'product',
    actionKey: 'create',
    description: 'Create catalog products and variants.',
  },
  {
    code: 'product.update',
    name: 'Update Products',
    moduleKey: 'product',
    actionKey: 'update',
    description: 'Update catalog products, variants, and attributes.',
  },
  {
    code: 'product.delete',
    name: 'Delete Products',
    moduleKey: 'product',
    actionKey: 'delete',
    description: 'Archive or delete catalog products.',
  },
  {
    code: 'product.manage_pricing',
    name: 'Manage Product Pricing',
    moduleKey: 'product',
    actionKey: 'manage_pricing',
    description: 'Manage price lists and product prices.',
  },
  {
    code: 'product.manage_categories',
    name: 'Manage Product Categories',
    moduleKey: 'product',
    actionKey: 'manage_categories',
    description: 'Manage categories, brands, units, and attributes.',
  },
  {
    code: 'supplier.view',
    name: 'View Suppliers',
    moduleKey: 'supplier',
    actionKey: 'view',
    description: 'View supplier master data.',
  },
  {
    code: 'supplier.manage',
    name: 'Manage Suppliers',
    moduleKey: 'supplier',
    actionKey: 'manage',
    description: 'Create and update supplier master data.',
  },
  {
    code: 'customer.view',
    name: 'View Customers',
    moduleKey: 'customer',
    actionKey: 'view',
    description: 'View customer master data.',
  },
  {
    code: 'customer.manage',
    name: 'Manage Customers',
    moduleKey: 'customer',
    actionKey: 'manage',
    description: 'Create and update customer master data.',
  },
  {
    code: 'tax.manage',
    name: 'Manage Tax Rates',
    moduleKey: 'tax',
    actionKey: 'manage',
    description: 'Create and update tax rates.',
  },
  {
    code: 'warehouse.view',
    name: 'View Warehouses',
    moduleKey: 'warehouse',
    actionKey: 'view',
    description: 'View warehouses and storage locations.',
  },
  {
    code: 'warehouse.create',
    name: 'Create Warehouses',
    moduleKey: 'warehouse',
    actionKey: 'create',
    description: 'Create warehouses.',
  },
  {
    code: 'warehouse.update',
    name: 'Update Warehouses',
    moduleKey: 'warehouse',
    actionKey: 'update',
    description: 'Update warehouse details.',
  },
  {
    code: 'warehouse.manage_locations',
    name: 'Manage Warehouse Locations',
    moduleKey: 'warehouse',
    actionKey: 'manage_locations',
    description: 'Create and manage warehouse location hierarchy.',
  },
  {
    code: 'inventory.view_stock',
    name: 'View Stock',
    moduleKey: 'inventory',
    actionKey: 'view_stock',
    description: 'View current stock balances.',
  },
  {
    code: 'inventory.view_movements',
    name: 'View Movements',
    moduleKey: 'inventory',
    actionKey: 'view_movements',
    description: 'View the inventory movement ledger.',
  },
  {
    code: 'adjustment.view',
    name: 'View Adjustments',
    moduleKey: 'adjustment',
    actionKey: 'view',
    description: 'View stock adjustments.',
  },
  {
    code: 'adjustment.create',
    name: 'Create Adjustments',
    moduleKey: 'adjustment',
    actionKey: 'create',
    description: 'Create stock adjustment documents.',
  },
  {
    code: 'adjustment.post',
    name: 'Post Adjustments',
    moduleKey: 'adjustment',
    actionKey: 'post',
    description: 'Post stock adjustments to the inventory ledger.',
  },
  {
    code: 'transfer.view',
    name: 'View Transfers',
    moduleKey: 'transfer',
    actionKey: 'view',
    description: 'View stock transfers.',
  },
  {
    code: 'transfer.create',
    name: 'Create Transfers',
    moduleKey: 'transfer',
    actionKey: 'create',
    description: 'Create stock transfer documents.',
  },
  {
    code: 'transfer.ship',
    name: 'Ship Transfers',
    moduleKey: 'transfer',
    actionKey: 'ship',
    description: 'Ship transfers (post TRANSFER_OUT).',
  },
  {
    code: 'transfer.receive',
    name: 'Receive Transfers',
    moduleKey: 'transfer',
    actionKey: 'receive',
    description: 'Receive transfers (post TRANSFER_IN).',
  },
  {
    code: 'purchase.requisition_view',
    name: 'View Requisitions',
    moduleKey: 'purchase',
    actionKey: 'requisition_view',
    description: 'View purchase requisitions.',
  },
  {
    code: 'purchase.requisition_manage',
    name: 'Manage Requisitions',
    moduleKey: 'purchase',
    actionKey: 'requisition_manage',
    description: 'Create, submit, approve, and convert requisitions.',
  },
  {
    code: 'purchase.po_view',
    name: 'View Purchase Orders',
    moduleKey: 'purchase',
    actionKey: 'po_view',
    description: 'View purchase orders, receipts, and returns.',
  },
  {
    code: 'purchase.po_create',
    name: 'Create Purchase Orders',
    moduleKey: 'purchase',
    actionKey: 'po_create',
    description: 'Create purchase orders.',
  },
  {
    code: 'purchase.po_approve',
    name: 'Approve Purchase Orders',
    moduleKey: 'purchase',
    actionKey: 'po_approve',
    description: 'Approve, confirm, and cancel purchase orders.',
  },
  {
    code: 'purchase.po_receive',
    name: 'Receive Goods',
    moduleKey: 'purchase',
    actionKey: 'po_receive',
    description: 'Create and post goods receipts.',
  },
  {
    code: 'purchase.return_manage',
    name: 'Manage Purchase Returns',
    moduleKey: 'purchase',
    actionKey: 'return_manage',
    description: 'Create and post purchase returns.',
  },
  {
    code: 'sales.order_view',
    name: 'View Sales Orders',
    moduleKey: 'sales',
    actionKey: 'order_view',
    description: 'View sales orders and invoices.',
  },
  {
    code: 'sales.order_create',
    name: 'Create Sales Orders',
    moduleKey: 'sales',
    actionKey: 'order_create',
    description: 'Create sales orders.',
  },
  {
    code: 'sales.order_confirm',
    name: 'Confirm Sales Orders',
    moduleKey: 'sales',
    actionKey: 'order_confirm',
    description: 'Confirm and cancel sales orders.',
  },
  {
    code: 'sales.order_fulfill',
    name: 'Fulfil Sales Orders',
    moduleKey: 'sales',
    actionKey: 'order_fulfill',
    description: 'Fulfil sales orders (post SALE movements).',
  },
  {
    code: 'sales.invoice_manage',
    name: 'Manage Sales Invoices',
    moduleKey: 'sales',
    actionKey: 'invoice_manage',
    description: 'Create, issue, and record payments on sales invoices.',
  },
  {
    code: 'pos.access',
    name: 'Access POS',
    moduleKey: 'pos',
    actionKey: 'access',
    description: 'Access the point-of-sale surface and its sales/sessions.',
  },
  {
    code: 'pos.sell',
    name: 'Sell at POS',
    moduleKey: 'pos',
    actionKey: 'sell',
    description: 'Create and complete POS sales (post SALE movements).',
  },
  {
    code: 'pos.void',
    name: 'Void POS Sales',
    moduleKey: 'pos',
    actionKey: 'void',
    description: 'Void POS sales.',
  },
  {
    code: 'pos.session_manage',
    name: 'Manage POS Sessions',
    moduleKey: 'pos',
    actionKey: 'session_manage',
    description: 'Open and close cash-drawer sessions.',
  },
  {
    code: 'returns.view',
    name: 'View Returns',
    moduleKey: 'returns',
    actionKey: 'view',
    description: 'View sales returns and credit/debit notes.',
  },
  {
    code: 'returns.create',
    name: 'Create Returns',
    moduleKey: 'returns',
    actionKey: 'create',
    description: 'Create, submit, and cancel sales returns.',
  },
  {
    code: 'returns.approve',
    name: 'Approve Returns',
    moduleKey: 'returns',
    actionKey: 'approve',
    description: 'Approve or reject requested sales returns.',
  },
  {
    code: 'returns.receive',
    name: 'Receive Returns',
    moduleKey: 'returns',
    actionKey: 'receive',
    description: 'Receive sales returns (post SALES_RETURN movements).',
  },
  {
    code: 'returns.refund',
    name: 'Refund POS Sales',
    moduleKey: 'returns',
    actionKey: 'refund',
    description: 'Refund completed POS sales and re-enter stock.',
  },
  {
    code: 'note.manage',
    name: 'Manage Credit/Debit Notes',
    moduleKey: 'returns',
    actionKey: 'note_manage',
    description: 'Create, issue, apply, and cancel credit and debit notes.',
  },
] as const

export type RoleCode = (typeof ROLE_DEFINITIONS)[number]['code']
export type PermissionCode = (typeof PERMISSION_DEFINITIONS)[number]['code']
export const PERMISSION_CODES = PERMISSION_DEFINITIONS.map(
  (definition) => definition.code
) as [PermissionCode, ...PermissionCode[]]

const ROLE_DEFINITION_BY_CODE: Record<string, (typeof ROLE_DEFINITIONS)[number]> =
  Object.fromEntries(
    ROLE_DEFINITIONS.map((definition) => [definition.code, definition])
  ) as Record<string, (typeof ROLE_DEFINITIONS)[number]>

export const ROLE_RANKS: Record<string, number> = Object.fromEntries(
  ROLE_DEFINITIONS.map((definition) => [definition.code, definition.rank])
) as Record<string, number>

export const TENANT_ASSIGNABLE_ROLE_CODES: Array<RoleCode> = ROLE_DEFINITIONS.map(
  (definition) => definition.code
)

export const ROLE_PERMISSION_MAP: Record<RoleCode, Array<PermissionCode>> = {
  super_admin: PERMISSION_DEFINITIONS.map((permission) => permission.code),
  admin: [
    'tenant.view',
    'tenant.update',
    'user.view',
    'user.invite',
    'user.update',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'role.view',
    'role.manage',
    'module.manage',
    'product.view',
    'product.create',
    'product.update',
    'product.delete',
    'product.manage_pricing',
    'product.manage_categories',
    'supplier.view',
    'supplier.manage',
    'customer.view',
    'customer.manage',
    'tax.manage',
    'warehouse.view',
    'warehouse.create',
    'warehouse.update',
    'warehouse.manage_locations',
    'inventory.view_stock',
    'inventory.view_movements',
    'adjustment.view',
    'adjustment.create',
    'adjustment.post',
    'transfer.view',
    'transfer.create',
    'transfer.ship',
    'transfer.receive',
    'purchase.requisition_view',
    'purchase.requisition_manage',
    'purchase.po_view',
    'purchase.po_create',
    'purchase.po_approve',
    'purchase.po_receive',
    'purchase.return_manage',
    'sales.order_view',
    'sales.order_create',
    'sales.order_confirm',
    'sales.order_fulfill',
    'sales.invoice_manage',
    'pos.access',
    'pos.sell',
    'pos.void',
    'pos.session_manage',
    'returns.view',
    'returns.create',
    'returns.approve',
    'returns.receive',
    'returns.refund',
    'note.manage',
  ],
  'res:super_admin': [
    'tenant.view',
    'tenant.manage_settings',
    'user.view',
    'user.invite',
    'user.update',
    'user.deactivate',
    'user.change_role',
    'user.assign_permission',
    'profile.view_self',
    'profile.update_self',
    'res.dashboard.view',
    'res.orders.view',
    'res.orders.create',
    'res.orders.update',
    'res.orders.cancel',
    'res.cashier.access',
    'res.kitchen.access',
    'res.kitchen.update_order_status',
    'res.floor.manage',
    'res.users.view',
    'res.users.manage',
    'res.settings.manage',
    'role.view',
    'role.manage',
    'module.manage',
  ],
  'res:admin': [
    'user.view',
    'profile.view_self',
    'profile.update_self',
    'res.dashboard.view',
    'res.orders.view',
    'res.orders.create',
    'res.orders.update',
    'res.users.view',
  ],
  'res:floor_manager': [
    'profile.view_self',
    'profile.update_self',
    'res.dashboard.view',
    'res.orders.view',
    'res.orders.update',
    'res.floor.manage',
  ],
  cashier: ['dashboard.view', 'profile.view_self', 'profile.update_self'],
  'res:cashier': [
    'profile.view_self',
    'profile.update_self',
    'res.dashboard.view',
    'res.cashier.access',
    'res.orders.view',
    'res.orders.create',
  ],
  'res:kitchen': [
    'profile.view_self',
    'profile.update_self',
    'res.dashboard.view',
    'res.kitchen.access',
    'res.kitchen.update_order_status',
    'res.orders.view',
  ],
  'res:user': ['profile.view_self', 'profile.update_self', 'res.dashboard.view'],
  inventory_manager: [
    'tenant.view',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'product.view',
    'product.create',
    'product.update',
    'product.delete',
    'product.manage_pricing',
    'product.manage_categories',
    'supplier.view',
    'supplier.manage',
    'customer.view',
    'customer.manage',
    'tax.manage',
    'warehouse.view',
    'warehouse.create',
    'warehouse.update',
    'warehouse.manage_locations',
    'inventory.view_stock',
    'inventory.view_movements',
    'adjustment.view',
    'adjustment.create',
    'adjustment.post',
    'transfer.view',
    'transfer.create',
    'transfer.ship',
    'transfer.receive',
    'purchase.requisition_view',
    'purchase.po_view',
  ],
  warehouse_manager: [
    'tenant.view',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'product.view',
    'warehouse.view',
    'warehouse.create',
    'warehouse.update',
    'warehouse.manage_locations',
    'inventory.view_stock',
    'inventory.view_movements',
    'adjustment.view',
    'adjustment.create',
    'adjustment.post',
    'transfer.view',
    'transfer.create',
    'transfer.ship',
    'transfer.receive',
    'purchase.po_view',
    'purchase.po_receive',
  ],
  purchasing_officer: [
    'tenant.view',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'product.view',
    'supplier.view',
    'supplier.manage',
    'warehouse.view',
    'inventory.view_stock',
    'transfer.view',
    'purchase.requisition_view',
    'purchase.requisition_manage',
    'purchase.po_view',
    'purchase.po_create',
    'purchase.po_approve',
    'purchase.po_receive',
    'purchase.return_manage',
    'note.manage',
  ],
  sales_manager: [
    'tenant.view',
    'dashboard.view',
    'profile.view_self',
    'profile.update_self',
    'product.view',
    'customer.view',
    'customer.manage',
    'inventory.view_stock',
    'sales.order_view',
    'sales.order_create',
    'sales.order_confirm',
    'sales.order_fulfill',
    'sales.invoice_manage',
    'pos.access',
    'returns.view',
    'returns.create',
    'returns.approve',
    'returns.receive',
    'returns.refund',
    'note.manage',
  ],
  pos_cashier: [
    'profile.view_self',
    'profile.update_self',
    'product.view',
    'customer.view',
    'inventory.view_stock',
    'pos.access',
    'pos.sell',
    'pos.session_manage',
    'returns.view',
    'returns.refund',
  ],
}

export function getRoleDefinition(roleCode: string) {
  const normalizedRoleCode = normalizeRoleCode(roleCode)

  return ROLE_DEFINITION_BY_CODE[normalizedRoleCode] ?? null
}

export function isTenantAssignableRole(roleCode: string): roleCode is RoleCode {
  return TENANT_ASSIGNABLE_ROLE_CODES.includes(
    normalizeRoleCode(roleCode) as RoleCode
  )
}

export function isPermissionCode(permissionCode: string): permissionCode is PermissionCode {
  return PERMISSION_CODES.includes(permissionCode as PermissionCode)
}

export function getRoleRank(roleCode: string) {
  const normalizedRoleCode = normalizeRoleCode(roleCode)

  return ROLE_RANKS[normalizedRoleCode] ?? 0
}
