/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSelectTenantRouteImport } from './routes/_auth/select-tenant'
import { Route as AuthCompleteProfileRouteImport } from './routes/_auth/complete-profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPosIndexRouteImport } from './routes/_app/pos/index'
import { Route as AppOutletsIndexRouteImport } from './routes/_app/outlets/index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app/settings/integrations'
import { Route as AppRestaurantTablesRouteImport } from './routes/_app/restaurant/tables'
import { Route as AppRestaurantMenuRouteImport } from './routes/_app/restaurant/menu'
import { Route as AppRestaurantKitchenRouteImport } from './routes/_app/restaurant/kitchen'
import { Route as AppPosReturnsRouteImport } from './routes/_app/pos/returns'
import { Route as AppPosOrdersRouteImport } from './routes/_app/pos/orders'
import { Route as AppInventoryStockRouteImport } from './routes/_app/inventory/stock'
import { Route as AppInventoryCatalogRouteImport } from './routes/_app/inventory/catalog'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSelectTenantRoute = AuthSelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPosIndexRoute = AppPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => AppRoute,
} as any)
const AppOutletsIndexRoute = AppOutletsIndexRouteImport.update({
  id: '/outlets/',
  path: '/outlets/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantTablesRoute = AppRestaurantTablesRouteImport.update({
  id: '/restaurant/tables',
  path: '/restaurant/tables',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantMenuRoute = AppRestaurantMenuRouteImport.update({
  id: '/restaurant/menu',
  path: '/restaurant/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantKitchenRoute = AppRestaurantKitchenRouteImport.update({
  id: '/restaurant/kitchen',
  path: '/restaurant/kitchen',
  getParentRoute: () => AppRoute,
} as any)
const AppPosReturnsRoute = AppPosReturnsRouteImport.update({
  id: '/pos/returns',
  path: '/pos/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppPosOrdersRoute = AppPosOrdersRouteImport.update({
  id: '/pos/orders',
  path: '/pos/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryStockRoute = AppInventoryStockRouteImport.update({
  id: '/inventory/stock',
  path: '/inventory/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryCatalogRoute = AppInventoryCatalogRouteImport.update({
  id: '/inventory/catalog',
  path: '/inventory/catalog',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AppDashboardRoute
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/select-tenant': typeof AuthSelectTenantRoute
  '/sign-in': typeof AuthSignInRoute
  '/inventory/catalog': typeof AppInventoryCatalogRoute
  '/inventory/stock': typeof AppInventoryStockRoute
  '/pos/orders': typeof AppPosOrdersRoute
  '/pos/returns': typeof AppPosReturnsRoute
  '/restaurant/kitchen': typeof AppRestaurantKitchenRoute
  '/restaurant/menu': typeof AppRestaurantMenuRoute
  '/restaurant/tables': typeof AppRestaurantTablesRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/outlets/': typeof AppOutletsIndexRoute
  '/pos/': typeof AppPosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AppDashboardRoute
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/select-tenant': typeof AuthSelectTenantRoute
  '/sign-in': typeof AuthSignInRoute
  '/inventory/catalog': typeof AppInventoryCatalogRoute
  '/inventory/stock': typeof AppInventoryStockRoute
  '/pos/orders': typeof AppPosOrdersRoute
  '/pos/returns': typeof AppPosReturnsRoute
  '/restaurant/kitchen': typeof AppRestaurantKitchenRoute
  '/restaurant/menu': typeof AppRestaurantMenuRoute
  '/restaurant/tables': typeof AppRestaurantTablesRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/outlets': typeof AppOutletsIndexRoute
  '/pos': typeof AppPosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/complete-profile': typeof AuthCompleteProfileRoute
  '/_auth/select-tenant': typeof AuthSelectTenantRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_app/inventory/catalog': typeof AppInventoryCatalogRoute
  '/_app/inventory/stock': typeof AppInventoryStockRoute
  '/_app/pos/orders': typeof AppPosOrdersRoute
  '/_app/pos/returns': typeof AppPosReturnsRoute
  '/_app/restaurant/kitchen': typeof AppRestaurantKitchenRoute
  '/_app/restaurant/menu': typeof AppRestaurantMenuRoute
  '/_app/restaurant/tables': typeof AppRestaurantTablesRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/outlets/': typeof AppOutletsIndexRoute
  '/_app/pos/': typeof AppPosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/complete-profile'
    | '/select-tenant'
    | '/sign-in'
    | '/inventory/catalog'
    | '/inventory/stock'
    | '/pos/orders'
    | '/pos/returns'
    | '/restaurant/kitchen'
    | '/restaurant/menu'
    | '/restaurant/tables'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/users'
    | '/inventory/'
    | '/outlets/'
    | '/pos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/complete-profile'
    | '/select-tenant'
    | '/sign-in'
    | '/inventory/catalog'
    | '/inventory/stock'
    | '/pos/orders'
    | '/pos/returns'
    | '/restaurant/kitchen'
    | '/restaurant/menu'
    | '/restaurant/tables'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/users'
    | '/inventory'
    | '/outlets'
    | '/pos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/about'
    | '/_app/dashboard'
    | '/_auth/complete-profile'
    | '/_auth/select-tenant'
    | '/_auth/sign-in'
    | '/_app/inventory/catalog'
    | '/_app/inventory/stock'
    | '/_app/pos/orders'
    | '/_app/pos/returns'
    | '/_app/restaurant/kitchen'
    | '/_app/restaurant/menu'
    | '/_app/restaurant/tables'
    | '/_app/settings/integrations'
    | '/_app/settings/notifications'
    | '/_app/settings/users'
    | '/_app/inventory/'
    | '/_app/outlets/'
    | '/_app/pos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/select-tenant': {
      id: '/_auth/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof AuthSelectTenantRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/complete-profile': {
      id: '/_auth/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos/': {
      id: '/_app/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof AppPosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outlets/': {
      id: '/_app/outlets/'
      path: '/outlets'
      fullPath: '/outlets/'
      preLoaderRoute: typeof AppOutletsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/tables': {
      id: '/_app/restaurant/tables'
      path: '/restaurant/tables'
      fullPath: '/restaurant/tables'
      preLoaderRoute: typeof AppRestaurantTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/menu': {
      id: '/_app/restaurant/menu'
      path: '/restaurant/menu'
      fullPath: '/restaurant/menu'
      preLoaderRoute: typeof AppRestaurantMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/kitchen': {
      id: '/_app/restaurant/kitchen'
      path: '/restaurant/kitchen'
      fullPath: '/restaurant/kitchen'
      preLoaderRoute: typeof AppRestaurantKitchenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos/returns': {
      id: '/_app/pos/returns'
      path: '/pos/returns'
      fullPath: '/pos/returns'
      preLoaderRoute: typeof AppPosReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos/orders': {
      id: '/_app/pos/orders'
      path: '/pos/orders'
      fullPath: '/pos/orders'
      preLoaderRoute: typeof AppPosOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/stock': {
      id: '/_app/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof AppInventoryStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/catalog': {
      id: '/_app/inventory/catalog'
      path: '/inventory/catalog'
      fullPath: '/inventory/catalog'
      preLoaderRoute: typeof AppInventoryCatalogRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryCatalogRoute: typeof AppInventoryCatalogRoute
  AppInventoryStockRoute: typeof AppInventoryStockRoute
  AppPosOrdersRoute: typeof AppPosOrdersRoute
  AppPosReturnsRoute: typeof AppPosReturnsRoute
  AppRestaurantKitchenRoute: typeof AppRestaurantKitchenRoute
  AppRestaurantMenuRoute: typeof AppRestaurantMenuRoute
  AppRestaurantTablesRoute: typeof AppRestaurantTablesRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppOutletsIndexRoute: typeof AppOutletsIndexRoute
  AppPosIndexRoute: typeof AppPosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryCatalogRoute: AppInventoryCatalogRoute,
  AppInventoryStockRoute: AppInventoryStockRoute,
  AppPosOrdersRoute: AppPosOrdersRoute,
  AppPosReturnsRoute: AppPosReturnsRoute,
  AppRestaurantKitchenRoute: AppRestaurantKitchenRoute,
  AppRestaurantMenuRoute: AppRestaurantMenuRoute,
  AppRestaurantTablesRoute: AppRestaurantTablesRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppOutletsIndexRoute: AppOutletsIndexRoute,
  AppPosIndexRoute: AppPosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthSelectTenantRoute: typeof AuthSelectTenantRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthSelectTenantRoute: AuthSelectTenantRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
