/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSelectTenantRouteImport } from './routes/_auth/select-tenant'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthCompleteProfileRouteImport } from './routes/_auth/complete-profile'
import { Route as AuthCompleteAccountRouteImport } from './routes/_auth/complete-account'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPurchaseIndexRouteImport } from './routes/_app/purchase/index'
import { Route as AppPosIndexRouteImport } from './routes/_app/pos/index'
import { Route as AppOutletsIndexRouteImport } from './routes/_app/outlets/index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppHrIndexRouteImport } from './routes/_app/hr/index'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app/settings/security'
import { Route as AppSettingsRolesRouteImport } from './routes/_app/settings/roles'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsModulesRouteImport } from './routes/_app/settings/modules'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app/settings/integrations'
import { Route as AppSettingsAccessRouteImport } from './routes/_app/settings/access'
import { Route as AppRestaurantWaitlistRouteImport } from './routes/_app/restaurant/waitlist'
import { Route as AppRestaurantTakeawayRouteImport } from './routes/_app/restaurant/takeaway'
import { Route as AppRestaurantTablesRouteImport } from './routes/_app/restaurant/tables'
import { Route as AppRestaurantSettingsRouteImport } from './routes/_app/restaurant/settings'
import { Route as AppRestaurantReservationsRouteImport } from './routes/_app/restaurant/reservations'
import { Route as AppRestaurantReportsRouteImport } from './routes/_app/restaurant/reports'
import { Route as AppRestaurantQrRouteImport } from './routes/_app/restaurant/qr'
import { Route as AppRestaurantPromotionsRouteImport } from './routes/_app/restaurant/promotions'
import { Route as AppRestaurantMenuRouteImport } from './routes/_app/restaurant/menu'
import { Route as AppRestaurantKitchenRouteImport } from './routes/_app/restaurant/kitchen'
import { Route as AppRestaurantGiftCardsRouteImport } from './routes/_app/restaurant/gift-cards'
import { Route as AppRestaurantFloorPlanRouteImport } from './routes/_app/restaurant/floor-plan'
import { Route as AppRestaurantEventsRouteImport } from './routes/_app/restaurant/events'
import { Route as AppRestaurantDeliveryRouteImport } from './routes/_app/restaurant/delivery'
import { Route as AppRestaurantDashboardRouteImport } from './routes/_app/restaurant/dashboard'
import { Route as AppRestaurantCateringRouteImport } from './routes/_app/restaurant/catering'
import { Route as AppRestaurantAnalyticsRouteImport } from './routes/_app/restaurant/analytics'
import { Route as AppPurchaseSuppliersRouteImport } from './routes/_app/purchase/suppliers'
import { Route as AppPurchaseRfqsRouteImport } from './routes/_app/purchase/rfqs'
import { Route as AppPurchaseReturnsRouteImport } from './routes/_app/purchase/returns'
import { Route as AppPurchaseRequisitionsRouteImport } from './routes/_app/purchase/requisitions'
import { Route as AppPurchaseReceiptsRouteImport } from './routes/_app/purchase/receipts'
import { Route as AppPurchaseQuotationsRouteImport } from './routes/_app/purchase/quotations'
import { Route as AppPurchasePaymentsRouteImport } from './routes/_app/purchase/payments'
import { Route as AppPurchaseOrdersRouteImport } from './routes/_app/purchase/orders'
import { Route as AppPurchaseInvoicesRouteImport } from './routes/_app/purchase/invoices'
import { Route as AppPurchaseApprovalsRouteImport } from './routes/_app/purchase/approvals'
import { Route as AppPosReturnsRouteImport } from './routes/_app/pos/returns'
import { Route as AppPosOrdersRouteImport } from './routes/_app/pos/orders'
import { Route as AppInventoryUnitsRouteImport } from './routes/_app/inventory/units'
import { Route as AppInventoryTransfersRouteImport } from './routes/_app/inventory/transfers'
import { Route as AppInventoryStockRouteImport } from './routes/_app/inventory/stock'
import { Route as AppInventorySettingsRouteImport } from './routes/_app/inventory/settings'
import { Route as AppInventoryReservationsRouteImport } from './routes/_app/inventory/reservations'
import { Route as AppInventoryReportsRouteImport } from './routes/_app/inventory/reports'
import { Route as AppInventoryPricingRouteImport } from './routes/_app/inventory/pricing'
import { Route as AppInventoryMovementsRouteImport } from './routes/_app/inventory/movements'
import { Route as AppInventoryLocationsRouteImport } from './routes/_app/inventory/locations'
import { Route as AppInventoryCountsRouteImport } from './routes/_app/inventory/counts'
import { Route as AppInventoryCategoriesRouteImport } from './routes/_app/inventory/categories'
import { Route as AppInventoryCatalogRouteImport } from './routes/_app/inventory/catalog'
import { Route as AppInventoryBrandsRouteImport } from './routes/_app/inventory/brands'
import { Route as AppInventoryAdjustmentsRouteImport } from './routes/_app/inventory/adjustments'
import { Route as AppHrWorkforceRouteImport } from './routes/_app/hr/workforce'
import { Route as AppHrTrainingRouteImport } from './routes/_app/hr/training'
import { Route as AppHrSelfServiceRouteImport } from './routes/_app/hr/self-service'
import { Route as AppHrRecruitmentRouteImport } from './routes/_app/hr/recruitment'
import { Route as AppHrPositionsRouteImport } from './routes/_app/hr/positions'
import { Route as AppHrPerformanceRouteImport } from './routes/_app/hr/performance'
import { Route as AppHrPayrollRouteImport } from './routes/_app/hr/payroll'
import { Route as AppHrOrganizationRouteImport } from './routes/_app/hr/organization'
import { Route as AppHrOnboardingRouteImport } from './routes/_app/hr/onboarding'
import { Route as AppHrLeaveRouteImport } from './routes/_app/hr/leave'
import { Route as AppHrJobGradesRouteImport } from './routes/_app/hr/job-grades'
import { Route as AppHrExpensesRouteImport } from './routes/_app/hr/expenses'
import { Route as AppHrEmployeesRouteImport } from './routes/_app/hr/employees'
import { Route as AppHrDepartmentsRouteImport } from './routes/_app/hr/departments'
import { Route as AppHrCostCentersRouteImport } from './routes/_app/hr/cost-centers'
import { Route as AppHrCareerRouteImport } from './routes/_app/hr/career'
import { Route as AppHrBudgetingRouteImport } from './routes/_app/hr/budgeting'
import { Route as AppHrAttendanceRouteImport } from './routes/_app/hr/attendance'
import { Route as AppHrAssetsRouteImport } from './routes/_app/hr/assets'
import { Route as AppHrAnalyticsRouteImport } from './routes/_app/hr/analytics'
import { Route as AppCrmSegmentsRouteImport } from './routes/_app/crm/segments'
import { Route as AppCrmLoyaltyRouteImport } from './routes/_app/crm/loyalty'
import { Route as AppCrmCustomersRouteImport } from './routes/_app/crm/customers'
import { Route as AppCrmAnalyticsRouteImport } from './routes/_app/crm/analytics'
import { Route as AppRestaurantOrdersIndexRouteImport } from './routes/_app/restaurant/orders/index'
import { Route as AppRestaurantOrdersOrderIdRouteImport } from './routes/_app/restaurant/orders/$orderId'
import { Route as AppInventoryCatalogProductIdRouteImport } from './routes/_app/inventory/catalog_.$productId'
import { Route as AppHrEmployeesEmployeeIdRouteImport } from './routes/_app/hr/employees_.$employeeId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSelectTenantRoute = AuthSelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompleteAccountRoute = AuthCompleteAccountRouteImport.update({
  id: '/complete-account',
  path: '/complete-account',
  getParentRoute: () => AuthRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseIndexRoute = AppPurchaseIndexRouteImport.update({
  id: '/purchase/',
  path: '/purchase/',
  getParentRoute: () => AppRoute,
} as any)
const AppPosIndexRoute = AppPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => AppRoute,
} as any)
const AppOutletsIndexRoute = AppOutletsIndexRouteImport.update({
  id: '/outlets/',
  path: '/outlets/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrIndexRoute = AppHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsModulesRoute = AppSettingsModulesRouteImport.update({
  id: '/settings/modules',
  path: '/settings/modules',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccessRoute = AppSettingsAccessRouteImport.update({
  id: '/settings/access',
  path: '/settings/access',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantWaitlistRoute = AppRestaurantWaitlistRouteImport.update({
  id: '/restaurant/waitlist',
  path: '/restaurant/waitlist',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantTakeawayRoute = AppRestaurantTakeawayRouteImport.update({
  id: '/restaurant/takeaway',
  path: '/restaurant/takeaway',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantTablesRoute = AppRestaurantTablesRouteImport.update({
  id: '/restaurant/tables',
  path: '/restaurant/tables',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantSettingsRoute = AppRestaurantSettingsRouteImport.update({
  id: '/restaurant/settings',
  path: '/restaurant/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantReservationsRoute =
  AppRestaurantReservationsRouteImport.update({
    id: '/restaurant/reservations',
    path: '/restaurant/reservations',
    getParentRoute: () => AppRoute,
  } as any)
const AppRestaurantReportsRoute = AppRestaurantReportsRouteImport.update({
  id: '/restaurant/reports',
  path: '/restaurant/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantQrRoute = AppRestaurantQrRouteImport.update({
  id: '/restaurant/qr',
  path: '/restaurant/qr',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantPromotionsRoute = AppRestaurantPromotionsRouteImport.update({
  id: '/restaurant/promotions',
  path: '/restaurant/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantMenuRoute = AppRestaurantMenuRouteImport.update({
  id: '/restaurant/menu',
  path: '/restaurant/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantKitchenRoute = AppRestaurantKitchenRouteImport.update({
  id: '/restaurant/kitchen',
  path: '/restaurant/kitchen',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantGiftCardsRoute = AppRestaurantGiftCardsRouteImport.update({
  id: '/restaurant/gift-cards',
  path: '/restaurant/gift-cards',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantFloorPlanRoute = AppRestaurantFloorPlanRouteImport.update({
  id: '/restaurant/floor-plan',
  path: '/restaurant/floor-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantEventsRoute = AppRestaurantEventsRouteImport.update({
  id: '/restaurant/events',
  path: '/restaurant/events',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantDeliveryRoute = AppRestaurantDeliveryRouteImport.update({
  id: '/restaurant/delivery',
  path: '/restaurant/delivery',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantDashboardRoute = AppRestaurantDashboardRouteImport.update({
  id: '/restaurant/dashboard',
  path: '/restaurant/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantCateringRoute = AppRestaurantCateringRouteImport.update({
  id: '/restaurant/catering',
  path: '/restaurant/catering',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantAnalyticsRoute = AppRestaurantAnalyticsRouteImport.update({
  id: '/restaurant/analytics',
  path: '/restaurant/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseSuppliersRoute = AppPurchaseSuppliersRouteImport.update({
  id: '/purchase/suppliers',
  path: '/purchase/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseRfqsRoute = AppPurchaseRfqsRouteImport.update({
  id: '/purchase/rfqs',
  path: '/purchase/rfqs',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseReturnsRoute = AppPurchaseReturnsRouteImport.update({
  id: '/purchase/returns',
  path: '/purchase/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseRequisitionsRoute = AppPurchaseRequisitionsRouteImport.update({
  id: '/purchase/requisitions',
  path: '/purchase/requisitions',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseReceiptsRoute = AppPurchaseReceiptsRouteImport.update({
  id: '/purchase/receipts',
  path: '/purchase/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseQuotationsRoute = AppPurchaseQuotationsRouteImport.update({
  id: '/purchase/quotations',
  path: '/purchase/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasePaymentsRoute = AppPurchasePaymentsRouteImport.update({
  id: '/purchase/payments',
  path: '/purchase/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase/orders',
  path: '/purchase/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseInvoicesRoute = AppPurchaseInvoicesRouteImport.update({
  id: '/purchase/invoices',
  path: '/purchase/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseApprovalsRoute = AppPurchaseApprovalsRouteImport.update({
  id: '/purchase/approvals',
  path: '/purchase/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppPosReturnsRoute = AppPosReturnsRouteImport.update({
  id: '/pos/returns',
  path: '/pos/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppPosOrdersRoute = AppPosOrdersRouteImport.update({
  id: '/pos/orders',
  path: '/pos/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryUnitsRoute = AppInventoryUnitsRouteImport.update({
  id: '/inventory/units',
  path: '/inventory/units',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryTransfersRoute = AppInventoryTransfersRouteImport.update({
  id: '/inventory/transfers',
  path: '/inventory/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryStockRoute = AppInventoryStockRouteImport.update({
  id: '/inventory/stock',
  path: '/inventory/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppInventorySettingsRoute = AppInventorySettingsRouteImport.update({
  id: '/inventory/settings',
  path: '/inventory/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryReservationsRoute =
  AppInventoryReservationsRouteImport.update({
    id: '/inventory/reservations',
    path: '/inventory/reservations',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryReportsRoute = AppInventoryReportsRouteImport.update({
  id: '/inventory/reports',
  path: '/inventory/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryPricingRoute = AppInventoryPricingRouteImport.update({
  id: '/inventory/pricing',
  path: '/inventory/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryMovementsRoute = AppInventoryMovementsRouteImport.update({
  id: '/inventory/movements',
  path: '/inventory/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryLocationsRoute = AppInventoryLocationsRouteImport.update({
  id: '/inventory/locations',
  path: '/inventory/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryCountsRoute = AppInventoryCountsRouteImport.update({
  id: '/inventory/counts',
  path: '/inventory/counts',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryCategoriesRoute = AppInventoryCategoriesRouteImport.update({
  id: '/inventory/categories',
  path: '/inventory/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryCatalogRoute = AppInventoryCatalogRouteImport.update({
  id: '/inventory/catalog',
  path: '/inventory/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryBrandsRoute = AppInventoryBrandsRouteImport.update({
  id: '/inventory/brands',
  path: '/inventory/brands',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryAdjustmentsRoute = AppInventoryAdjustmentsRouteImport.update({
  id: '/inventory/adjustments',
  path: '/inventory/adjustments',
  getParentRoute: () => AppRoute,
} as any)
const AppHrWorkforceRoute = AppHrWorkforceRouteImport.update({
  id: '/hr/workforce',
  path: '/hr/workforce',
  getParentRoute: () => AppRoute,
} as any)
const AppHrTrainingRoute = AppHrTrainingRouteImport.update({
  id: '/hr/training',
  path: '/hr/training',
  getParentRoute: () => AppRoute,
} as any)
const AppHrSelfServiceRoute = AppHrSelfServiceRouteImport.update({
  id: '/hr/self-service',
  path: '/hr/self-service',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRecruitmentRoute = AppHrRecruitmentRouteImport.update({
  id: '/hr/recruitment',
  path: '/hr/recruitment',
  getParentRoute: () => AppRoute,
} as any)
const AppHrPositionsRoute = AppHrPositionsRouteImport.update({
  id: '/hr/positions',
  path: '/hr/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppHrPerformanceRoute = AppHrPerformanceRouteImport.update({
  id: '/hr/performance',
  path: '/hr/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppHrPayrollRoute = AppHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppHrOrganizationRoute = AppHrOrganizationRouteImport.update({
  id: '/hr/organization',
  path: '/hr/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppHrOnboardingRoute = AppHrOnboardingRouteImport.update({
  id: '/hr/onboarding',
  path: '/hr/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppHrLeaveRoute = AppHrLeaveRouteImport.update({
  id: '/hr/leave',
  path: '/hr/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppHrJobGradesRoute = AppHrJobGradesRouteImport.update({
  id: '/hr/job-grades',
  path: '/hr/job-grades',
  getParentRoute: () => AppRoute,
} as any)
const AppHrExpensesRoute = AppHrExpensesRouteImport.update({
  id: '/hr/expenses',
  path: '/hr/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppHrEmployeesRoute = AppHrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppHrDepartmentsRoute = AppHrDepartmentsRouteImport.update({
  id: '/hr/departments',
  path: '/hr/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppHrCostCentersRoute = AppHrCostCentersRouteImport.update({
  id: '/hr/cost-centers',
  path: '/hr/cost-centers',
  getParentRoute: () => AppRoute,
} as any)
const AppHrCareerRoute = AppHrCareerRouteImport.update({
  id: '/hr/career',
  path: '/hr/career',
  getParentRoute: () => AppRoute,
} as any)
const AppHrBudgetingRoute = AppHrBudgetingRouteImport.update({
  id: '/hr/budgeting',
  path: '/hr/budgeting',
  getParentRoute: () => AppRoute,
} as any)
const AppHrAttendanceRoute = AppHrAttendanceRouteImport.update({
  id: '/hr/attendance',
  path: '/hr/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppHrAssetsRoute = AppHrAssetsRouteImport.update({
  id: '/hr/assets',
  path: '/hr/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppHrAnalyticsRoute = AppHrAnalyticsRouteImport.update({
  id: '/hr/analytics',
  path: '/hr/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmSegmentsRoute = AppCrmSegmentsRouteImport.update({
  id: '/crm/segments',
  path: '/crm/segments',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmLoyaltyRoute = AppCrmLoyaltyRouteImport.update({
  id: '/crm/loyalty',
  path: '/crm/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCustomersRoute = AppCrmCustomersRouteImport.update({
  id: '/crm/customers',
  path: '/crm/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmAnalyticsRoute = AppCrmAnalyticsRouteImport.update({
  id: '/crm/analytics',
  path: '/crm/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantOrdersIndexRoute =
  AppRestaurantOrdersIndexRouteImport.update({
    id: '/restaurant/orders/',
    path: '/restaurant/orders/',
    getParentRoute: () => AppRoute,
  } as any)
const AppRestaurantOrdersOrderIdRoute =
  AppRestaurantOrdersOrderIdRouteImport.update({
    id: '/restaurant/orders/$orderId',
    path: '/restaurant/orders/$orderId',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryCatalogProductIdRoute =
  AppInventoryCatalogProductIdRouteImport.update({
    id: '/inventory/catalog_/$productId',
    path: '/inventory/catalog/$productId',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrEmployeesEmployeeIdRoute =
  AppHrEmployeesEmployeeIdRouteImport.update({
    id: '/hr/employees_/$employeeId',
    path: '/hr/employees/$employeeId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/complete-account': typeof AuthCompleteAccountRoute
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/select-tenant': typeof AuthSelectTenantRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/crm/analytics': typeof AppCrmAnalyticsRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/loyalty': typeof AppCrmLoyaltyRoute
  '/crm/segments': typeof AppCrmSegmentsRoute
  '/hr/analytics': typeof AppHrAnalyticsRoute
  '/hr/assets': typeof AppHrAssetsRoute
  '/hr/attendance': typeof AppHrAttendanceRoute
  '/hr/budgeting': typeof AppHrBudgetingRoute
  '/hr/career': typeof AppHrCareerRoute
  '/hr/cost-centers': typeof AppHrCostCentersRoute
  '/hr/departments': typeof AppHrDepartmentsRoute
  '/hr/employees': typeof AppHrEmployeesRoute
  '/hr/expenses': typeof AppHrExpensesRoute
  '/hr/job-grades': typeof AppHrJobGradesRoute
  '/hr/leave': typeof AppHrLeaveRoute
  '/hr/onboarding': typeof AppHrOnboardingRoute
  '/hr/organization': typeof AppHrOrganizationRoute
  '/hr/payroll': typeof AppHrPayrollRoute
  '/hr/performance': typeof AppHrPerformanceRoute
  '/hr/positions': typeof AppHrPositionsRoute
  '/hr/recruitment': typeof AppHrRecruitmentRoute
  '/hr/self-service': typeof AppHrSelfServiceRoute
  '/hr/training': typeof AppHrTrainingRoute
  '/hr/workforce': typeof AppHrWorkforceRoute
  '/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/inventory/brands': typeof AppInventoryBrandsRoute
  '/inventory/catalog': typeof AppInventoryCatalogRoute
  '/inventory/categories': typeof AppInventoryCategoriesRoute
  '/inventory/counts': typeof AppInventoryCountsRoute
  '/inventory/locations': typeof AppInventoryLocationsRoute
  '/inventory/movements': typeof AppInventoryMovementsRoute
  '/inventory/pricing': typeof AppInventoryPricingRoute
  '/inventory/reports': typeof AppInventoryReportsRoute
  '/inventory/reservations': typeof AppInventoryReservationsRoute
  '/inventory/settings': typeof AppInventorySettingsRoute
  '/inventory/stock': typeof AppInventoryStockRoute
  '/inventory/transfers': typeof AppInventoryTransfersRoute
  '/inventory/units': typeof AppInventoryUnitsRoute
  '/pos/orders': typeof AppPosOrdersRoute
  '/pos/returns': typeof AppPosReturnsRoute
  '/purchase/approvals': typeof AppPurchaseApprovalsRoute
  '/purchase/invoices': typeof AppPurchaseInvoicesRoute
  '/purchase/orders': typeof AppPurchaseOrdersRoute
  '/purchase/payments': typeof AppPurchasePaymentsRoute
  '/purchase/quotations': typeof AppPurchaseQuotationsRoute
  '/purchase/receipts': typeof AppPurchaseReceiptsRoute
  '/purchase/requisitions': typeof AppPurchaseRequisitionsRoute
  '/purchase/returns': typeof AppPurchaseReturnsRoute
  '/purchase/rfqs': typeof AppPurchaseRfqsRoute
  '/purchase/suppliers': typeof AppPurchaseSuppliersRoute
  '/restaurant/analytics': typeof AppRestaurantAnalyticsRoute
  '/restaurant/catering': typeof AppRestaurantCateringRoute
  '/restaurant/dashboard': typeof AppRestaurantDashboardRoute
  '/restaurant/delivery': typeof AppRestaurantDeliveryRoute
  '/restaurant/events': typeof AppRestaurantEventsRoute
  '/restaurant/floor-plan': typeof AppRestaurantFloorPlanRoute
  '/restaurant/gift-cards': typeof AppRestaurantGiftCardsRoute
  '/restaurant/kitchen': typeof AppRestaurantKitchenRoute
  '/restaurant/menu': typeof AppRestaurantMenuRoute
  '/restaurant/promotions': typeof AppRestaurantPromotionsRoute
  '/restaurant/qr': typeof AppRestaurantQrRoute
  '/restaurant/reports': typeof AppRestaurantReportsRoute
  '/restaurant/reservations': typeof AppRestaurantReservationsRoute
  '/restaurant/settings': typeof AppRestaurantSettingsRoute
  '/restaurant/tables': typeof AppRestaurantTablesRoute
  '/restaurant/takeaway': typeof AppRestaurantTakeawayRoute
  '/restaurant/waitlist': typeof AppRestaurantWaitlistRoute
  '/settings/access': typeof AppSettingsAccessRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/modules': typeof AppSettingsModulesRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/hr/': typeof AppHrIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/outlets/': typeof AppOutletsIndexRoute
  '/pos/': typeof AppPosIndexRoute
  '/purchase/': typeof AppPurchaseIndexRoute
  '/hr/employees/$employeeId': typeof AppHrEmployeesEmployeeIdRoute
  '/inventory/catalog/$productId': typeof AppInventoryCatalogProductIdRoute
  '/restaurant/orders/$orderId': typeof AppRestaurantOrdersOrderIdRoute
  '/restaurant/orders/': typeof AppRestaurantOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/complete-account': typeof AuthCompleteAccountRoute
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/select-tenant': typeof AuthSelectTenantRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/crm/analytics': typeof AppCrmAnalyticsRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/loyalty': typeof AppCrmLoyaltyRoute
  '/crm/segments': typeof AppCrmSegmentsRoute
  '/hr/analytics': typeof AppHrAnalyticsRoute
  '/hr/assets': typeof AppHrAssetsRoute
  '/hr/attendance': typeof AppHrAttendanceRoute
  '/hr/budgeting': typeof AppHrBudgetingRoute
  '/hr/career': typeof AppHrCareerRoute
  '/hr/cost-centers': typeof AppHrCostCentersRoute
  '/hr/departments': typeof AppHrDepartmentsRoute
  '/hr/employees': typeof AppHrEmployeesRoute
  '/hr/expenses': typeof AppHrExpensesRoute
  '/hr/job-grades': typeof AppHrJobGradesRoute
  '/hr/leave': typeof AppHrLeaveRoute
  '/hr/onboarding': typeof AppHrOnboardingRoute
  '/hr/organization': typeof AppHrOrganizationRoute
  '/hr/payroll': typeof AppHrPayrollRoute
  '/hr/performance': typeof AppHrPerformanceRoute
  '/hr/positions': typeof AppHrPositionsRoute
  '/hr/recruitment': typeof AppHrRecruitmentRoute
  '/hr/self-service': typeof AppHrSelfServiceRoute
  '/hr/training': typeof AppHrTrainingRoute
  '/hr/workforce': typeof AppHrWorkforceRoute
  '/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/inventory/brands': typeof AppInventoryBrandsRoute
  '/inventory/catalog': typeof AppInventoryCatalogRoute
  '/inventory/categories': typeof AppInventoryCategoriesRoute
  '/inventory/counts': typeof AppInventoryCountsRoute
  '/inventory/locations': typeof AppInventoryLocationsRoute
  '/inventory/movements': typeof AppInventoryMovementsRoute
  '/inventory/pricing': typeof AppInventoryPricingRoute
  '/inventory/reports': typeof AppInventoryReportsRoute
  '/inventory/reservations': typeof AppInventoryReservationsRoute
  '/inventory/settings': typeof AppInventorySettingsRoute
  '/inventory/stock': typeof AppInventoryStockRoute
  '/inventory/transfers': typeof AppInventoryTransfersRoute
  '/inventory/units': typeof AppInventoryUnitsRoute
  '/pos/orders': typeof AppPosOrdersRoute
  '/pos/returns': typeof AppPosReturnsRoute
  '/purchase/approvals': typeof AppPurchaseApprovalsRoute
  '/purchase/invoices': typeof AppPurchaseInvoicesRoute
  '/purchase/orders': typeof AppPurchaseOrdersRoute
  '/purchase/payments': typeof AppPurchasePaymentsRoute
  '/purchase/quotations': typeof AppPurchaseQuotationsRoute
  '/purchase/receipts': typeof AppPurchaseReceiptsRoute
  '/purchase/requisitions': typeof AppPurchaseRequisitionsRoute
  '/purchase/returns': typeof AppPurchaseReturnsRoute
  '/purchase/rfqs': typeof AppPurchaseRfqsRoute
  '/purchase/suppliers': typeof AppPurchaseSuppliersRoute
  '/restaurant/analytics': typeof AppRestaurantAnalyticsRoute
  '/restaurant/catering': typeof AppRestaurantCateringRoute
  '/restaurant/dashboard': typeof AppRestaurantDashboardRoute
  '/restaurant/delivery': typeof AppRestaurantDeliveryRoute
  '/restaurant/events': typeof AppRestaurantEventsRoute
  '/restaurant/floor-plan': typeof AppRestaurantFloorPlanRoute
  '/restaurant/gift-cards': typeof AppRestaurantGiftCardsRoute
  '/restaurant/kitchen': typeof AppRestaurantKitchenRoute
  '/restaurant/menu': typeof AppRestaurantMenuRoute
  '/restaurant/promotions': typeof AppRestaurantPromotionsRoute
  '/restaurant/qr': typeof AppRestaurantQrRoute
  '/restaurant/reports': typeof AppRestaurantReportsRoute
  '/restaurant/reservations': typeof AppRestaurantReservationsRoute
  '/restaurant/settings': typeof AppRestaurantSettingsRoute
  '/restaurant/tables': typeof AppRestaurantTablesRoute
  '/restaurant/takeaway': typeof AppRestaurantTakeawayRoute
  '/restaurant/waitlist': typeof AppRestaurantWaitlistRoute
  '/settings/access': typeof AppSettingsAccessRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/modules': typeof AppSettingsModulesRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/hr': typeof AppHrIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/outlets': typeof AppOutletsIndexRoute
  '/pos': typeof AppPosIndexRoute
  '/purchase': typeof AppPurchaseIndexRoute
  '/hr/employees/$employeeId': typeof AppHrEmployeesEmployeeIdRoute
  '/inventory/catalog/$productId': typeof AppInventoryCatalogProductIdRoute
  '/restaurant/orders/$orderId': typeof AppRestaurantOrdersOrderIdRoute
  '/restaurant/orders': typeof AppRestaurantOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_auth/complete-account': typeof AuthCompleteAccountRoute
  '/_auth/complete-profile': typeof AuthCompleteProfileRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/select-tenant': typeof AuthSelectTenantRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/crm/analytics': typeof AppCrmAnalyticsRoute
  '/_app/crm/customers': typeof AppCrmCustomersRoute
  '/_app/crm/loyalty': typeof AppCrmLoyaltyRoute
  '/_app/crm/segments': typeof AppCrmSegmentsRoute
  '/_app/hr/analytics': typeof AppHrAnalyticsRoute
  '/_app/hr/assets': typeof AppHrAssetsRoute
  '/_app/hr/attendance': typeof AppHrAttendanceRoute
  '/_app/hr/budgeting': typeof AppHrBudgetingRoute
  '/_app/hr/career': typeof AppHrCareerRoute
  '/_app/hr/cost-centers': typeof AppHrCostCentersRoute
  '/_app/hr/departments': typeof AppHrDepartmentsRoute
  '/_app/hr/employees': typeof AppHrEmployeesRoute
  '/_app/hr/expenses': typeof AppHrExpensesRoute
  '/_app/hr/job-grades': typeof AppHrJobGradesRoute
  '/_app/hr/leave': typeof AppHrLeaveRoute
  '/_app/hr/onboarding': typeof AppHrOnboardingRoute
  '/_app/hr/organization': typeof AppHrOrganizationRoute
  '/_app/hr/payroll': typeof AppHrPayrollRoute
  '/_app/hr/performance': typeof AppHrPerformanceRoute
  '/_app/hr/positions': typeof AppHrPositionsRoute
  '/_app/hr/recruitment': typeof AppHrRecruitmentRoute
  '/_app/hr/self-service': typeof AppHrSelfServiceRoute
  '/_app/hr/training': typeof AppHrTrainingRoute
  '/_app/hr/workforce': typeof AppHrWorkforceRoute
  '/_app/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/_app/inventory/brands': typeof AppInventoryBrandsRoute
  '/_app/inventory/catalog': typeof AppInventoryCatalogRoute
  '/_app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/_app/inventory/counts': typeof AppInventoryCountsRoute
  '/_app/inventory/locations': typeof AppInventoryLocationsRoute
  '/_app/inventory/movements': typeof AppInventoryMovementsRoute
  '/_app/inventory/pricing': typeof AppInventoryPricingRoute
  '/_app/inventory/reports': typeof AppInventoryReportsRoute
  '/_app/inventory/reservations': typeof AppInventoryReservationsRoute
  '/_app/inventory/settings': typeof AppInventorySettingsRoute
  '/_app/inventory/stock': typeof AppInventoryStockRoute
  '/_app/inventory/transfers': typeof AppInventoryTransfersRoute
  '/_app/inventory/units': typeof AppInventoryUnitsRoute
  '/_app/pos/orders': typeof AppPosOrdersRoute
  '/_app/pos/returns': typeof AppPosReturnsRoute
  '/_app/purchase/approvals': typeof AppPurchaseApprovalsRoute
  '/_app/purchase/invoices': typeof AppPurchaseInvoicesRoute
  '/_app/purchase/orders': typeof AppPurchaseOrdersRoute
  '/_app/purchase/payments': typeof AppPurchasePaymentsRoute
  '/_app/purchase/quotations': typeof AppPurchaseQuotationsRoute
  '/_app/purchase/receipts': typeof AppPurchaseReceiptsRoute
  '/_app/purchase/requisitions': typeof AppPurchaseRequisitionsRoute
  '/_app/purchase/returns': typeof AppPurchaseReturnsRoute
  '/_app/purchase/rfqs': typeof AppPurchaseRfqsRoute
  '/_app/purchase/suppliers': typeof AppPurchaseSuppliersRoute
  '/_app/restaurant/analytics': typeof AppRestaurantAnalyticsRoute
  '/_app/restaurant/catering': typeof AppRestaurantCateringRoute
  '/_app/restaurant/dashboard': typeof AppRestaurantDashboardRoute
  '/_app/restaurant/delivery': typeof AppRestaurantDeliveryRoute
  '/_app/restaurant/events': typeof AppRestaurantEventsRoute
  '/_app/restaurant/floor-plan': typeof AppRestaurantFloorPlanRoute
  '/_app/restaurant/gift-cards': typeof AppRestaurantGiftCardsRoute
  '/_app/restaurant/kitchen': typeof AppRestaurantKitchenRoute
  '/_app/restaurant/menu': typeof AppRestaurantMenuRoute
  '/_app/restaurant/promotions': typeof AppRestaurantPromotionsRoute
  '/_app/restaurant/qr': typeof AppRestaurantQrRoute
  '/_app/restaurant/reports': typeof AppRestaurantReportsRoute
  '/_app/restaurant/reservations': typeof AppRestaurantReservationsRoute
  '/_app/restaurant/settings': typeof AppRestaurantSettingsRoute
  '/_app/restaurant/tables': typeof AppRestaurantTablesRoute
  '/_app/restaurant/takeaway': typeof AppRestaurantTakeawayRoute
  '/_app/restaurant/waitlist': typeof AppRestaurantWaitlistRoute
  '/_app/settings/access': typeof AppSettingsAccessRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/modules': typeof AppSettingsModulesRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/hr/': typeof AppHrIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/outlets/': typeof AppOutletsIndexRoute
  '/_app/pos/': typeof AppPosIndexRoute
  '/_app/purchase/': typeof AppPurchaseIndexRoute
  '/_app/hr/employees_/$employeeId': typeof AppHrEmployeesEmployeeIdRoute
  '/_app/inventory/catalog_/$productId': typeof AppInventoryCatalogProductIdRoute
  '/_app/restaurant/orders/$orderId': typeof AppRestaurantOrdersOrderIdRoute
  '/_app/restaurant/orders/': typeof AppRestaurantOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/profile'
    | '/complete-account'
    | '/complete-profile'
    | '/forgot-password'
    | '/reset-password'
    | '/select-tenant'
    | '/sign-in'
    | '/sign-up'
    | '/crm/analytics'
    | '/crm/customers'
    | '/crm/loyalty'
    | '/crm/segments'
    | '/hr/analytics'
    | '/hr/assets'
    | '/hr/attendance'
    | '/hr/budgeting'
    | '/hr/career'
    | '/hr/cost-centers'
    | '/hr/departments'
    | '/hr/employees'
    | '/hr/expenses'
    | '/hr/job-grades'
    | '/hr/leave'
    | '/hr/onboarding'
    | '/hr/organization'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/positions'
    | '/hr/recruitment'
    | '/hr/self-service'
    | '/hr/training'
    | '/hr/workforce'
    | '/inventory/adjustments'
    | '/inventory/brands'
    | '/inventory/catalog'
    | '/inventory/categories'
    | '/inventory/counts'
    | '/inventory/locations'
    | '/inventory/movements'
    | '/inventory/pricing'
    | '/inventory/reports'
    | '/inventory/reservations'
    | '/inventory/settings'
    | '/inventory/stock'
    | '/inventory/transfers'
    | '/inventory/units'
    | '/pos/orders'
    | '/pos/returns'
    | '/purchase/approvals'
    | '/purchase/invoices'
    | '/purchase/orders'
    | '/purchase/payments'
    | '/purchase/quotations'
    | '/purchase/receipts'
    | '/purchase/requisitions'
    | '/purchase/returns'
    | '/purchase/rfqs'
    | '/purchase/suppliers'
    | '/restaurant/analytics'
    | '/restaurant/catering'
    | '/restaurant/dashboard'
    | '/restaurant/delivery'
    | '/restaurant/events'
    | '/restaurant/floor-plan'
    | '/restaurant/gift-cards'
    | '/restaurant/kitchen'
    | '/restaurant/menu'
    | '/restaurant/promotions'
    | '/restaurant/qr'
    | '/restaurant/reports'
    | '/restaurant/reservations'
    | '/restaurant/settings'
    | '/restaurant/tables'
    | '/restaurant/takeaway'
    | '/restaurant/waitlist'
    | '/settings/access'
    | '/settings/integrations'
    | '/settings/modules'
    | '/settings/notifications'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/users'
    | '/hr/'
    | '/inventory/'
    | '/outlets/'
    | '/pos/'
    | '/purchase/'
    | '/hr/employees/$employeeId'
    | '/inventory/catalog/$productId'
    | '/restaurant/orders/$orderId'
    | '/restaurant/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/profile'
    | '/complete-account'
    | '/complete-profile'
    | '/forgot-password'
    | '/reset-password'
    | '/select-tenant'
    | '/sign-in'
    | '/sign-up'
    | '/crm/analytics'
    | '/crm/customers'
    | '/crm/loyalty'
    | '/crm/segments'
    | '/hr/analytics'
    | '/hr/assets'
    | '/hr/attendance'
    | '/hr/budgeting'
    | '/hr/career'
    | '/hr/cost-centers'
    | '/hr/departments'
    | '/hr/employees'
    | '/hr/expenses'
    | '/hr/job-grades'
    | '/hr/leave'
    | '/hr/onboarding'
    | '/hr/organization'
    | '/hr/payroll'
    | '/hr/performance'
    | '/hr/positions'
    | '/hr/recruitment'
    | '/hr/self-service'
    | '/hr/training'
    | '/hr/workforce'
    | '/inventory/adjustments'
    | '/inventory/brands'
    | '/inventory/catalog'
    | '/inventory/categories'
    | '/inventory/counts'
    | '/inventory/locations'
    | '/inventory/movements'
    | '/inventory/pricing'
    | '/inventory/reports'
    | '/inventory/reservations'
    | '/inventory/settings'
    | '/inventory/stock'
    | '/inventory/transfers'
    | '/inventory/units'
    | '/pos/orders'
    | '/pos/returns'
    | '/purchase/approvals'
    | '/purchase/invoices'
    | '/purchase/orders'
    | '/purchase/payments'
    | '/purchase/quotations'
    | '/purchase/receipts'
    | '/purchase/requisitions'
    | '/purchase/returns'
    | '/purchase/rfqs'
    | '/purchase/suppliers'
    | '/restaurant/analytics'
    | '/restaurant/catering'
    | '/restaurant/dashboard'
    | '/restaurant/delivery'
    | '/restaurant/events'
    | '/restaurant/floor-plan'
    | '/restaurant/gift-cards'
    | '/restaurant/kitchen'
    | '/restaurant/menu'
    | '/restaurant/promotions'
    | '/restaurant/qr'
    | '/restaurant/reports'
    | '/restaurant/reservations'
    | '/restaurant/settings'
    | '/restaurant/tables'
    | '/restaurant/takeaway'
    | '/restaurant/waitlist'
    | '/settings/access'
    | '/settings/integrations'
    | '/settings/modules'
    | '/settings/notifications'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/users'
    | '/hr'
    | '/inventory'
    | '/outlets'
    | '/pos'
    | '/purchase'
    | '/hr/employees/$employeeId'
    | '/inventory/catalog/$productId'
    | '/restaurant/orders/$orderId'
    | '/restaurant/orders'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/about'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_auth/complete-account'
    | '/_auth/complete-profile'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/select-tenant'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/crm/analytics'
    | '/_app/crm/customers'
    | '/_app/crm/loyalty'
    | '/_app/crm/segments'
    | '/_app/hr/analytics'
    | '/_app/hr/assets'
    | '/_app/hr/attendance'
    | '/_app/hr/budgeting'
    | '/_app/hr/career'
    | '/_app/hr/cost-centers'
    | '/_app/hr/departments'
    | '/_app/hr/employees'
    | '/_app/hr/expenses'
    | '/_app/hr/job-grades'
    | '/_app/hr/leave'
    | '/_app/hr/onboarding'
    | '/_app/hr/organization'
    | '/_app/hr/payroll'
    | '/_app/hr/performance'
    | '/_app/hr/positions'
    | '/_app/hr/recruitment'
    | '/_app/hr/self-service'
    | '/_app/hr/training'
    | '/_app/hr/workforce'
    | '/_app/inventory/adjustments'
    | '/_app/inventory/brands'
    | '/_app/inventory/catalog'
    | '/_app/inventory/categories'
    | '/_app/inventory/counts'
    | '/_app/inventory/locations'
    | '/_app/inventory/movements'
    | '/_app/inventory/pricing'
    | '/_app/inventory/reports'
    | '/_app/inventory/reservations'
    | '/_app/inventory/settings'
    | '/_app/inventory/stock'
    | '/_app/inventory/transfers'
    | '/_app/inventory/units'
    | '/_app/pos/orders'
    | '/_app/pos/returns'
    | '/_app/purchase/approvals'
    | '/_app/purchase/invoices'
    | '/_app/purchase/orders'
    | '/_app/purchase/payments'
    | '/_app/purchase/quotations'
    | '/_app/purchase/receipts'
    | '/_app/purchase/requisitions'
    | '/_app/purchase/returns'
    | '/_app/purchase/rfqs'
    | '/_app/purchase/suppliers'
    | '/_app/restaurant/analytics'
    | '/_app/restaurant/catering'
    | '/_app/restaurant/dashboard'
    | '/_app/restaurant/delivery'
    | '/_app/restaurant/events'
    | '/_app/restaurant/floor-plan'
    | '/_app/restaurant/gift-cards'
    | '/_app/restaurant/kitchen'
    | '/_app/restaurant/menu'
    | '/_app/restaurant/promotions'
    | '/_app/restaurant/qr'
    | '/_app/restaurant/reports'
    | '/_app/restaurant/reservations'
    | '/_app/restaurant/settings'
    | '/_app/restaurant/tables'
    | '/_app/restaurant/takeaway'
    | '/_app/restaurant/waitlist'
    | '/_app/settings/access'
    | '/_app/settings/integrations'
    | '/_app/settings/modules'
    | '/_app/settings/notifications'
    | '/_app/settings/roles'
    | '/_app/settings/security'
    | '/_app/settings/users'
    | '/_app/hr/'
    | '/_app/inventory/'
    | '/_app/outlets/'
    | '/_app/pos/'
    | '/_app/purchase/'
    | '/_app/hr/employees_/$employeeId'
    | '/_app/inventory/catalog_/$productId'
    | '/_app/restaurant/orders/$orderId'
    | '/_app/restaurant/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/select-tenant': {
      id: '/_auth/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof AuthSelectTenantRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/complete-profile': {
      id: '/_auth/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/complete-account': {
      id: '/_auth/complete-account'
      path: '/complete-account'
      fullPath: '/complete-account'
      preLoaderRoute: typeof AuthCompleteAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/': {
      id: '/_app/purchase/'
      path: '/purchase'
      fullPath: '/purchase/'
      preLoaderRoute: typeof AppPurchaseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos/': {
      id: '/_app/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof AppPosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outlets/': {
      id: '/_app/outlets/'
      path: '/outlets'
      fullPath: '/outlets/'
      preLoaderRoute: typeof AppOutletsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/': {
      id: '/_app/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof AppHrIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/modules': {
      id: '/_app/settings/modules'
      path: '/settings/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof AppSettingsModulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/access': {
      id: '/_app/settings/access'
      path: '/settings/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof AppSettingsAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/waitlist': {
      id: '/_app/restaurant/waitlist'
      path: '/restaurant/waitlist'
      fullPath: '/restaurant/waitlist'
      preLoaderRoute: typeof AppRestaurantWaitlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/takeaway': {
      id: '/_app/restaurant/takeaway'
      path: '/restaurant/takeaway'
      fullPath: '/restaurant/takeaway'
      preLoaderRoute: typeof AppRestaurantTakeawayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/tables': {
      id: '/_app/restaurant/tables'
      path: '/restaurant/tables'
      fullPath: '/restaurant/tables'
      preLoaderRoute: typeof AppRestaurantTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/settings': {
      id: '/_app/restaurant/settings'
      path: '/restaurant/settings'
      fullPath: '/restaurant/settings'
      preLoaderRoute: typeof AppRestaurantSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/reservations': {
      id: '/_app/restaurant/reservations'
      path: '/restaurant/reservations'
      fullPath: '/restaurant/reservations'
      preLoaderRoute: typeof AppRestaurantReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/reports': {
      id: '/_app/restaurant/reports'
      path: '/restaurant/reports'
      fullPath: '/restaurant/reports'
      preLoaderRoute: typeof AppRestaurantReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/qr': {
      id: '/_app/restaurant/qr'
      path: '/restaurant/qr'
      fullPath: '/restaurant/qr'
      preLoaderRoute: typeof AppRestaurantQrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/promotions': {
      id: '/_app/restaurant/promotions'
      path: '/restaurant/promotions'
      fullPath: '/restaurant/promotions'
      preLoaderRoute: typeof AppRestaurantPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/menu': {
      id: '/_app/restaurant/menu'
      path: '/restaurant/menu'
      fullPath: '/restaurant/menu'
      preLoaderRoute: typeof AppRestaurantMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/kitchen': {
      id: '/_app/restaurant/kitchen'
      path: '/restaurant/kitchen'
      fullPath: '/restaurant/kitchen'
      preLoaderRoute: typeof AppRestaurantKitchenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/gift-cards': {
      id: '/_app/restaurant/gift-cards'
      path: '/restaurant/gift-cards'
      fullPath: '/restaurant/gift-cards'
      preLoaderRoute: typeof AppRestaurantGiftCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/floor-plan': {
      id: '/_app/restaurant/floor-plan'
      path: '/restaurant/floor-plan'
      fullPath: '/restaurant/floor-plan'
      preLoaderRoute: typeof AppRestaurantFloorPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/events': {
      id: '/_app/restaurant/events'
      path: '/restaurant/events'
      fullPath: '/restaurant/events'
      preLoaderRoute: typeof AppRestaurantEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/delivery': {
      id: '/_app/restaurant/delivery'
      path: '/restaurant/delivery'
      fullPath: '/restaurant/delivery'
      preLoaderRoute: typeof AppRestaurantDeliveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/dashboard': {
      id: '/_app/restaurant/dashboard'
      path: '/restaurant/dashboard'
      fullPath: '/restaurant/dashboard'
      preLoaderRoute: typeof AppRestaurantDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/catering': {
      id: '/_app/restaurant/catering'
      path: '/restaurant/catering'
      fullPath: '/restaurant/catering'
      preLoaderRoute: typeof AppRestaurantCateringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/analytics': {
      id: '/_app/restaurant/analytics'
      path: '/restaurant/analytics'
      fullPath: '/restaurant/analytics'
      preLoaderRoute: typeof AppRestaurantAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/suppliers': {
      id: '/_app/purchase/suppliers'
      path: '/purchase/suppliers'
      fullPath: '/purchase/suppliers'
      preLoaderRoute: typeof AppPurchaseSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/rfqs': {
      id: '/_app/purchase/rfqs'
      path: '/purchase/rfqs'
      fullPath: '/purchase/rfqs'
      preLoaderRoute: typeof AppPurchaseRfqsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/returns': {
      id: '/_app/purchase/returns'
      path: '/purchase/returns'
      fullPath: '/purchase/returns'
      preLoaderRoute: typeof AppPurchaseReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/requisitions': {
      id: '/_app/purchase/requisitions'
      path: '/purchase/requisitions'
      fullPath: '/purchase/requisitions'
      preLoaderRoute: typeof AppPurchaseRequisitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/receipts': {
      id: '/_app/purchase/receipts'
      path: '/purchase/receipts'
      fullPath: '/purchase/receipts'
      preLoaderRoute: typeof AppPurchaseReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/quotations': {
      id: '/_app/purchase/quotations'
      path: '/purchase/quotations'
      fullPath: '/purchase/quotations'
      preLoaderRoute: typeof AppPurchaseQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/payments': {
      id: '/_app/purchase/payments'
      path: '/purchase/payments'
      fullPath: '/purchase/payments'
      preLoaderRoute: typeof AppPurchasePaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/orders': {
      id: '/_app/purchase/orders'
      path: '/purchase/orders'
      fullPath: '/purchase/orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/invoices': {
      id: '/_app/purchase/invoices'
      path: '/purchase/invoices'
      fullPath: '/purchase/invoices'
      preLoaderRoute: typeof AppPurchaseInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/approvals': {
      id: '/_app/purchase/approvals'
      path: '/purchase/approvals'
      fullPath: '/purchase/approvals'
      preLoaderRoute: typeof AppPurchaseApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos/returns': {
      id: '/_app/pos/returns'
      path: '/pos/returns'
      fullPath: '/pos/returns'
      preLoaderRoute: typeof AppPosReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos/orders': {
      id: '/_app/pos/orders'
      path: '/pos/orders'
      fullPath: '/pos/orders'
      preLoaderRoute: typeof AppPosOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/units': {
      id: '/_app/inventory/units'
      path: '/inventory/units'
      fullPath: '/inventory/units'
      preLoaderRoute: typeof AppInventoryUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/transfers': {
      id: '/_app/inventory/transfers'
      path: '/inventory/transfers'
      fullPath: '/inventory/transfers'
      preLoaderRoute: typeof AppInventoryTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/stock': {
      id: '/_app/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof AppInventoryStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/settings': {
      id: '/_app/inventory/settings'
      path: '/inventory/settings'
      fullPath: '/inventory/settings'
      preLoaderRoute: typeof AppInventorySettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/reservations': {
      id: '/_app/inventory/reservations'
      path: '/inventory/reservations'
      fullPath: '/inventory/reservations'
      preLoaderRoute: typeof AppInventoryReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/reports': {
      id: '/_app/inventory/reports'
      path: '/inventory/reports'
      fullPath: '/inventory/reports'
      preLoaderRoute: typeof AppInventoryReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/pricing': {
      id: '/_app/inventory/pricing'
      path: '/inventory/pricing'
      fullPath: '/inventory/pricing'
      preLoaderRoute: typeof AppInventoryPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/movements': {
      id: '/_app/inventory/movements'
      path: '/inventory/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof AppInventoryMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/locations': {
      id: '/_app/inventory/locations'
      path: '/inventory/locations'
      fullPath: '/inventory/locations'
      preLoaderRoute: typeof AppInventoryLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/counts': {
      id: '/_app/inventory/counts'
      path: '/inventory/counts'
      fullPath: '/inventory/counts'
      preLoaderRoute: typeof AppInventoryCountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/categories': {
      id: '/_app/inventory/categories'
      path: '/inventory/categories'
      fullPath: '/inventory/categories'
      preLoaderRoute: typeof AppInventoryCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/catalog': {
      id: '/_app/inventory/catalog'
      path: '/inventory/catalog'
      fullPath: '/inventory/catalog'
      preLoaderRoute: typeof AppInventoryCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/brands': {
      id: '/_app/inventory/brands'
      path: '/inventory/brands'
      fullPath: '/inventory/brands'
      preLoaderRoute: typeof AppInventoryBrandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/adjustments': {
      id: '/_app/inventory/adjustments'
      path: '/inventory/adjustments'
      fullPath: '/inventory/adjustments'
      preLoaderRoute: typeof AppInventoryAdjustmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/workforce': {
      id: '/_app/hr/workforce'
      path: '/hr/workforce'
      fullPath: '/hr/workforce'
      preLoaderRoute: typeof AppHrWorkforceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/training': {
      id: '/_app/hr/training'
      path: '/hr/training'
      fullPath: '/hr/training'
      preLoaderRoute: typeof AppHrTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/self-service': {
      id: '/_app/hr/self-service'
      path: '/hr/self-service'
      fullPath: '/hr/self-service'
      preLoaderRoute: typeof AppHrSelfServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/recruitment': {
      id: '/_app/hr/recruitment'
      path: '/hr/recruitment'
      fullPath: '/hr/recruitment'
      preLoaderRoute: typeof AppHrRecruitmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/positions': {
      id: '/_app/hr/positions'
      path: '/hr/positions'
      fullPath: '/hr/positions'
      preLoaderRoute: typeof AppHrPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/performance': {
      id: '/_app/hr/performance'
      path: '/hr/performance'
      fullPath: '/hr/performance'
      preLoaderRoute: typeof AppHrPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/payroll': {
      id: '/_app/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AppHrPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/organization': {
      id: '/_app/hr/organization'
      path: '/hr/organization'
      fullPath: '/hr/organization'
      preLoaderRoute: typeof AppHrOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/onboarding': {
      id: '/_app/hr/onboarding'
      path: '/hr/onboarding'
      fullPath: '/hr/onboarding'
      preLoaderRoute: typeof AppHrOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/leave': {
      id: '/_app/hr/leave'
      path: '/hr/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof AppHrLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/job-grades': {
      id: '/_app/hr/job-grades'
      path: '/hr/job-grades'
      fullPath: '/hr/job-grades'
      preLoaderRoute: typeof AppHrJobGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/expenses': {
      id: '/_app/hr/expenses'
      path: '/hr/expenses'
      fullPath: '/hr/expenses'
      preLoaderRoute: typeof AppHrExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/employees': {
      id: '/_app/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AppHrEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/departments': {
      id: '/_app/hr/departments'
      path: '/hr/departments'
      fullPath: '/hr/departments'
      preLoaderRoute: typeof AppHrDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/cost-centers': {
      id: '/_app/hr/cost-centers'
      path: '/hr/cost-centers'
      fullPath: '/hr/cost-centers'
      preLoaderRoute: typeof AppHrCostCentersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/career': {
      id: '/_app/hr/career'
      path: '/hr/career'
      fullPath: '/hr/career'
      preLoaderRoute: typeof AppHrCareerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/budgeting': {
      id: '/_app/hr/budgeting'
      path: '/hr/budgeting'
      fullPath: '/hr/budgeting'
      preLoaderRoute: typeof AppHrBudgetingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/attendance': {
      id: '/_app/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AppHrAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/assets': {
      id: '/_app/hr/assets'
      path: '/hr/assets'
      fullPath: '/hr/assets'
      preLoaderRoute: typeof AppHrAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/analytics': {
      id: '/_app/hr/analytics'
      path: '/hr/analytics'
      fullPath: '/hr/analytics'
      preLoaderRoute: typeof AppHrAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/segments': {
      id: '/_app/crm/segments'
      path: '/crm/segments'
      fullPath: '/crm/segments'
      preLoaderRoute: typeof AppCrmSegmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/loyalty': {
      id: '/_app/crm/loyalty'
      path: '/crm/loyalty'
      fullPath: '/crm/loyalty'
      preLoaderRoute: typeof AppCrmLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/customers': {
      id: '/_app/crm/customers'
      path: '/crm/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof AppCrmCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/analytics': {
      id: '/_app/crm/analytics'
      path: '/crm/analytics'
      fullPath: '/crm/analytics'
      preLoaderRoute: typeof AppCrmAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/orders/': {
      id: '/_app/restaurant/orders/'
      path: '/restaurant/orders'
      fullPath: '/restaurant/orders/'
      preLoaderRoute: typeof AppRestaurantOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurant/orders/$orderId': {
      id: '/_app/restaurant/orders/$orderId'
      path: '/restaurant/orders/$orderId'
      fullPath: '/restaurant/orders/$orderId'
      preLoaderRoute: typeof AppRestaurantOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/catalog_/$productId': {
      id: '/_app/inventory/catalog_/$productId'
      path: '/inventory/catalog/$productId'
      fullPath: '/inventory/catalog/$productId'
      preLoaderRoute: typeof AppInventoryCatalogProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/employees_/$employeeId': {
      id: '/_app/hr/employees_/$employeeId'
      path: '/hr/employees/$employeeId'
      fullPath: '/hr/employees/$employeeId'
      preLoaderRoute: typeof AppHrEmployeesEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppCrmAnalyticsRoute: typeof AppCrmAnalyticsRoute
  AppCrmCustomersRoute: typeof AppCrmCustomersRoute
  AppCrmLoyaltyRoute: typeof AppCrmLoyaltyRoute
  AppCrmSegmentsRoute: typeof AppCrmSegmentsRoute
  AppHrAnalyticsRoute: typeof AppHrAnalyticsRoute
  AppHrAssetsRoute: typeof AppHrAssetsRoute
  AppHrAttendanceRoute: typeof AppHrAttendanceRoute
  AppHrBudgetingRoute: typeof AppHrBudgetingRoute
  AppHrCareerRoute: typeof AppHrCareerRoute
  AppHrCostCentersRoute: typeof AppHrCostCentersRoute
  AppHrDepartmentsRoute: typeof AppHrDepartmentsRoute
  AppHrEmployeesRoute: typeof AppHrEmployeesRoute
  AppHrExpensesRoute: typeof AppHrExpensesRoute
  AppHrJobGradesRoute: typeof AppHrJobGradesRoute
  AppHrLeaveRoute: typeof AppHrLeaveRoute
  AppHrOnboardingRoute: typeof AppHrOnboardingRoute
  AppHrOrganizationRoute: typeof AppHrOrganizationRoute
  AppHrPayrollRoute: typeof AppHrPayrollRoute
  AppHrPerformanceRoute: typeof AppHrPerformanceRoute
  AppHrPositionsRoute: typeof AppHrPositionsRoute
  AppHrRecruitmentRoute: typeof AppHrRecruitmentRoute
  AppHrSelfServiceRoute: typeof AppHrSelfServiceRoute
  AppHrTrainingRoute: typeof AppHrTrainingRoute
  AppHrWorkforceRoute: typeof AppHrWorkforceRoute
  AppInventoryAdjustmentsRoute: typeof AppInventoryAdjustmentsRoute
  AppInventoryBrandsRoute: typeof AppInventoryBrandsRoute
  AppInventoryCatalogRoute: typeof AppInventoryCatalogRoute
  AppInventoryCategoriesRoute: typeof AppInventoryCategoriesRoute
  AppInventoryCountsRoute: typeof AppInventoryCountsRoute
  AppInventoryLocationsRoute: typeof AppInventoryLocationsRoute
  AppInventoryMovementsRoute: typeof AppInventoryMovementsRoute
  AppInventoryPricingRoute: typeof AppInventoryPricingRoute
  AppInventoryReportsRoute: typeof AppInventoryReportsRoute
  AppInventoryReservationsRoute: typeof AppInventoryReservationsRoute
  AppInventorySettingsRoute: typeof AppInventorySettingsRoute
  AppInventoryStockRoute: typeof AppInventoryStockRoute
  AppInventoryTransfersRoute: typeof AppInventoryTransfersRoute
  AppInventoryUnitsRoute: typeof AppInventoryUnitsRoute
  AppPosOrdersRoute: typeof AppPosOrdersRoute
  AppPosReturnsRoute: typeof AppPosReturnsRoute
  AppPurchaseApprovalsRoute: typeof AppPurchaseApprovalsRoute
  AppPurchaseInvoicesRoute: typeof AppPurchaseInvoicesRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppPurchasePaymentsRoute: typeof AppPurchasePaymentsRoute
  AppPurchaseQuotationsRoute: typeof AppPurchaseQuotationsRoute
  AppPurchaseReceiptsRoute: typeof AppPurchaseReceiptsRoute
  AppPurchaseRequisitionsRoute: typeof AppPurchaseRequisitionsRoute
  AppPurchaseReturnsRoute: typeof AppPurchaseReturnsRoute
  AppPurchaseRfqsRoute: typeof AppPurchaseRfqsRoute
  AppPurchaseSuppliersRoute: typeof AppPurchaseSuppliersRoute
  AppRestaurantAnalyticsRoute: typeof AppRestaurantAnalyticsRoute
  AppRestaurantCateringRoute: typeof AppRestaurantCateringRoute
  AppRestaurantDashboardRoute: typeof AppRestaurantDashboardRoute
  AppRestaurantDeliveryRoute: typeof AppRestaurantDeliveryRoute
  AppRestaurantEventsRoute: typeof AppRestaurantEventsRoute
  AppRestaurantFloorPlanRoute: typeof AppRestaurantFloorPlanRoute
  AppRestaurantGiftCardsRoute: typeof AppRestaurantGiftCardsRoute
  AppRestaurantKitchenRoute: typeof AppRestaurantKitchenRoute
  AppRestaurantMenuRoute: typeof AppRestaurantMenuRoute
  AppRestaurantPromotionsRoute: typeof AppRestaurantPromotionsRoute
  AppRestaurantQrRoute: typeof AppRestaurantQrRoute
  AppRestaurantReportsRoute: typeof AppRestaurantReportsRoute
  AppRestaurantReservationsRoute: typeof AppRestaurantReservationsRoute
  AppRestaurantSettingsRoute: typeof AppRestaurantSettingsRoute
  AppRestaurantTablesRoute: typeof AppRestaurantTablesRoute
  AppRestaurantTakeawayRoute: typeof AppRestaurantTakeawayRoute
  AppRestaurantWaitlistRoute: typeof AppRestaurantWaitlistRoute
  AppSettingsAccessRoute: typeof AppSettingsAccessRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsModulesRoute: typeof AppSettingsModulesRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppHrIndexRoute: typeof AppHrIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppOutletsIndexRoute: typeof AppOutletsIndexRoute
  AppPosIndexRoute: typeof AppPosIndexRoute
  AppPurchaseIndexRoute: typeof AppPurchaseIndexRoute
  AppHrEmployeesEmployeeIdRoute: typeof AppHrEmployeesEmployeeIdRoute
  AppInventoryCatalogProductIdRoute: typeof AppInventoryCatalogProductIdRoute
  AppRestaurantOrdersOrderIdRoute: typeof AppRestaurantOrdersOrderIdRoute
  AppRestaurantOrdersIndexRoute: typeof AppRestaurantOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppCrmAnalyticsRoute: AppCrmAnalyticsRoute,
  AppCrmCustomersRoute: AppCrmCustomersRoute,
  AppCrmLoyaltyRoute: AppCrmLoyaltyRoute,
  AppCrmSegmentsRoute: AppCrmSegmentsRoute,
  AppHrAnalyticsRoute: AppHrAnalyticsRoute,
  AppHrAssetsRoute: AppHrAssetsRoute,
  AppHrAttendanceRoute: AppHrAttendanceRoute,
  AppHrBudgetingRoute: AppHrBudgetingRoute,
  AppHrCareerRoute: AppHrCareerRoute,
  AppHrCostCentersRoute: AppHrCostCentersRoute,
  AppHrDepartmentsRoute: AppHrDepartmentsRoute,
  AppHrEmployeesRoute: AppHrEmployeesRoute,
  AppHrExpensesRoute: AppHrExpensesRoute,
  AppHrJobGradesRoute: AppHrJobGradesRoute,
  AppHrLeaveRoute: AppHrLeaveRoute,
  AppHrOnboardingRoute: AppHrOnboardingRoute,
  AppHrOrganizationRoute: AppHrOrganizationRoute,
  AppHrPayrollRoute: AppHrPayrollRoute,
  AppHrPerformanceRoute: AppHrPerformanceRoute,
  AppHrPositionsRoute: AppHrPositionsRoute,
  AppHrRecruitmentRoute: AppHrRecruitmentRoute,
  AppHrSelfServiceRoute: AppHrSelfServiceRoute,
  AppHrTrainingRoute: AppHrTrainingRoute,
  AppHrWorkforceRoute: AppHrWorkforceRoute,
  AppInventoryAdjustmentsRoute: AppInventoryAdjustmentsRoute,
  AppInventoryBrandsRoute: AppInventoryBrandsRoute,
  AppInventoryCatalogRoute: AppInventoryCatalogRoute,
  AppInventoryCategoriesRoute: AppInventoryCategoriesRoute,
  AppInventoryCountsRoute: AppInventoryCountsRoute,
  AppInventoryLocationsRoute: AppInventoryLocationsRoute,
  AppInventoryMovementsRoute: AppInventoryMovementsRoute,
  AppInventoryPricingRoute: AppInventoryPricingRoute,
  AppInventoryReportsRoute: AppInventoryReportsRoute,
  AppInventoryReservationsRoute: AppInventoryReservationsRoute,
  AppInventorySettingsRoute: AppInventorySettingsRoute,
  AppInventoryStockRoute: AppInventoryStockRoute,
  AppInventoryTransfersRoute: AppInventoryTransfersRoute,
  AppInventoryUnitsRoute: AppInventoryUnitsRoute,
  AppPosOrdersRoute: AppPosOrdersRoute,
  AppPosReturnsRoute: AppPosReturnsRoute,
  AppPurchaseApprovalsRoute: AppPurchaseApprovalsRoute,
  AppPurchaseInvoicesRoute: AppPurchaseInvoicesRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppPurchasePaymentsRoute: AppPurchasePaymentsRoute,
  AppPurchaseQuotationsRoute: AppPurchaseQuotationsRoute,
  AppPurchaseReceiptsRoute: AppPurchaseReceiptsRoute,
  AppPurchaseRequisitionsRoute: AppPurchaseRequisitionsRoute,
  AppPurchaseReturnsRoute: AppPurchaseReturnsRoute,
  AppPurchaseRfqsRoute: AppPurchaseRfqsRoute,
  AppPurchaseSuppliersRoute: AppPurchaseSuppliersRoute,
  AppRestaurantAnalyticsRoute: AppRestaurantAnalyticsRoute,
  AppRestaurantCateringRoute: AppRestaurantCateringRoute,
  AppRestaurantDashboardRoute: AppRestaurantDashboardRoute,
  AppRestaurantDeliveryRoute: AppRestaurantDeliveryRoute,
  AppRestaurantEventsRoute: AppRestaurantEventsRoute,
  AppRestaurantFloorPlanRoute: AppRestaurantFloorPlanRoute,
  AppRestaurantGiftCardsRoute: AppRestaurantGiftCardsRoute,
  AppRestaurantKitchenRoute: AppRestaurantKitchenRoute,
  AppRestaurantMenuRoute: AppRestaurantMenuRoute,
  AppRestaurantPromotionsRoute: AppRestaurantPromotionsRoute,
  AppRestaurantQrRoute: AppRestaurantQrRoute,
  AppRestaurantReportsRoute: AppRestaurantReportsRoute,
  AppRestaurantReservationsRoute: AppRestaurantReservationsRoute,
  AppRestaurantSettingsRoute: AppRestaurantSettingsRoute,
  AppRestaurantTablesRoute: AppRestaurantTablesRoute,
  AppRestaurantTakeawayRoute: AppRestaurantTakeawayRoute,
  AppRestaurantWaitlistRoute: AppRestaurantWaitlistRoute,
  AppSettingsAccessRoute: AppSettingsAccessRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsModulesRoute: AppSettingsModulesRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppHrIndexRoute: AppHrIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppOutletsIndexRoute: AppOutletsIndexRoute,
  AppPosIndexRoute: AppPosIndexRoute,
  AppPurchaseIndexRoute: AppPurchaseIndexRoute,
  AppHrEmployeesEmployeeIdRoute: AppHrEmployeesEmployeeIdRoute,
  AppInventoryCatalogProductIdRoute: AppInventoryCatalogProductIdRoute,
  AppRestaurantOrdersOrderIdRoute: AppRestaurantOrdersOrderIdRoute,
  AppRestaurantOrdersIndexRoute: AppRestaurantOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCompleteAccountRoute: typeof AuthCompleteAccountRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSelectTenantRoute: typeof AuthSelectTenantRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCompleteAccountRoute: AuthCompleteAccountRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSelectTenantRoute: AuthSelectTenantRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
