import type { LucideIcon } from 'lucide-react'
import {
  ArrowLeftRight,
  Award,
  BadgePercent,
  Banknote,
  BellRing,
  Bike,
  Boxes,
  CalendarClock,
  ChartSpline,
  Gift,
  ChefHat,
  Circle,
  ClipboardCheck,
  ClipboardList,
  FileBarChart,
  FileQuestion,
  FileText,
  HeartHandshake,
  Landmark,
  LayoutDashboard,
  ListOrdered,
  MapPinned,
  PackageCheck,
  PackageSearch,
  PlugZap,
  PartyPopper,
  QrCode,
  ReceiptText,
  RotateCcw,
  ScrollText,
  ShieldCheck,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  SlidersHorizontal,
  SquareStack,
  TrendingUp,
  Truck,
  Undo2,
  UsersRound,
  UtensilsCrossed,
} from 'lucide-react'

// Maps DB-stored icon *names* to Lucide components for DB-driven navigation.
// Unknown names fall back to a neutral placeholder rather than throwing.
const ICON_BY_NAME: Record<string, LucideIcon> = {
  ArrowLeftRight,
  Award,
  BadgePercent,
  Banknote,
  BellRing,
  Bike,
  Boxes,
  CalendarClock,
  ChartSpline,
  Gift,
  ChefHat,
  ClipboardCheck,
  ClipboardList,
  FileBarChart,
  FileQuestion,
  FileText,
  HeartHandshake,
  Landmark,
  LayoutDashboard,
  ListOrdered,
  PartyPopper,
  QrCode,
  ShoppingBag,
  MapPinned,
  PackageCheck,
  PackageSearch,
  PlugZap,
  ReceiptText,
  RotateCcw,
  ScrollText,
  ShieldCheck,
  ShoppingBasket,
  ShoppingCart,
  SlidersHorizontal,
  SquareStack,
  TrendingUp,
  Truck,
  Undo2,
  UsersRound,
  UtensilsCrossed,
}

export function resolveNavIcon(name: string | null | undefined): LucideIcon {
  if (name && name in ICON_BY_NAME) {
    return ICON_BY_NAME[name]
  }

  return Circle
}
